import { isUuid } from "./validation.ts";

export type HybridPaperClaim = { winnerSide: "a" | "b"; margin: number; evidenceReference: string };
export type CreateHybridCaseRequest = { caseId: string; eventId: string; gameId: string; expectedGameVersion: number; digitalSubmissionId: string; paperClaim: HybridPaperClaim; idempotencyKey: string };
export type ReviewHybridCaseRequest = { expectedGameVersion: number; digitalSubmissionId: string; digitalWinnerSide: "a" | "b"; digitalMargin: number; paperClaim: HybridPaperClaim; decision: "approve" | "reject"; idempotencyKey: string };
export type ReconcileHybridRequest = { operationType: "create_hybrid_digital_paper_case_v1" | "review_hybrid_digital_paper_case_v1"; targetId: string; idempotencyKey: string };

const exact=(value:object,keys:string[])=>Object.keys(value).length===keys.length&&keys.every((key)=>key in value);
export function isHybridPaperClaim(value:unknown):value is HybridPaperClaim{if(!value||typeof value!=="object"||Array.isArray(value)||!exact(value,["winnerSide","margin","evidenceReference"]))return false;const v=value as Record<string,unknown>;return(v.winnerSide==="a"||v.winnerSide==="b")&&Number.isInteger(v.margin)&&Number(v.margin)>=1&&Number(v.margin)<=121&&typeof v.evidenceReference==="string"&&v.evidenceReference.trim().length>0&&v.evidenceReference.length<=200&&!/[\u0000-\u001f\u007f]/.test(v.evidenceReference)}
export function isCreateHybridCaseRequest(value:unknown):value is CreateHybridCaseRequest{if(!value||typeof value!=="object"||Array.isArray(value)||!exact(value,["caseId","eventId","gameId","expectedGameVersion","digitalSubmissionId","paperClaim","idempotencyKey"]))return false;const v=value as Record<string,unknown>;return isUuid(v.caseId)&&isUuid(v.eventId)&&isUuid(v.gameId)&&isUuid(v.digitalSubmissionId)&&isUuid(v.idempotencyKey)&&Number.isInteger(v.expectedGameVersion)&&Number(v.expectedGameVersion)>0&&isHybridPaperClaim(v.paperClaim)}
export function isReviewHybridCaseRequest(value:unknown):value is ReviewHybridCaseRequest{if(!value||typeof value!=="object"||Array.isArray(value)||!exact(value,["expectedGameVersion","digitalSubmissionId","digitalWinnerSide","digitalMargin","paperClaim","decision","idempotencyKey"]))return false;const v=value as Record<string,unknown>;return Number.isInteger(v.expectedGameVersion)&&Number(v.expectedGameVersion)>0&&isUuid(v.digitalSubmissionId)&&(v.digitalWinnerSide==="a"||v.digitalWinnerSide==="b")&&Number.isInteger(v.digitalMargin)&&Number(v.digitalMargin)>=1&&Number(v.digitalMargin)<=121&&isHybridPaperClaim(v.paperClaim)&&(v.decision==="approve"||v.decision==="reject")&&isUuid(v.idempotencyKey)}
export function isReconcileHybridRequest(value:unknown):value is ReconcileHybridRequest{if(!value||typeof value!=="object"||Array.isArray(value)||!exact(value,["operationType","targetId","idempotencyKey"]))return false;const v=value as Record<string,unknown>;return(v.operationType==="create_hybrid_digital_paper_case_v1"||v.operationType==="review_hybrid_digital_paper_case_v1")&&isUuid(v.targetId)&&isUuid(v.idempotencyKey)}
const rejected=new Set(["invalid_request","not_cross_checker","official_identity_unconfirmed","game_unavailable","event_unavailable","tournament_closed","stale_game_version","game_already_claimed","digital_submission_unavailable","not_hybrid_pair","self_cross_check_denied","game_progression_locked","digital_paper_mismatch","not_eligible_reviewer","case_unavailable","review_closed","first_official_identity_changed","scorecard_preference_changed","review_evidence_mismatch","idempotency_conflict"]);
export function isRejectedHybrid(value:unknown,caseId:string){if(!value||typeof value!=="object"||Array.isArray(value)||!exact(value,["status","code","caseId"]))return false;const v=value as Record<string,unknown>;return v.status==="rejected"&&v.caseId===caseId&&rejected.has(v.code as string)}
export function isAcceptedHybridCreate(value:unknown,request:CreateHybridCaseRequest){if(!value||typeof value!=="object"||Array.isArray(value)||!exact(value,["status","caseId","gameId","gameVersion","digitalSubmissionId","winnerSide","margin","authoritative"]))return false;const v=value as Record<string,unknown>;return v.status==="pending_review"&&v.caseId===request.caseId&&v.gameId===request.gameId&&v.gameVersion===request.expectedGameVersion&&v.digitalSubmissionId===request.digitalSubmissionId&&v.winnerSide===request.paperClaim.winnerSide&&v.margin===request.paperClaim.margin&&v.authoritative===false}
export function isAcceptedHybridReview(value:unknown,caseId:string,request:ReviewHybridCaseRequest){if(!value||typeof value!=="object"||Array.isArray(value)||!exact(value,["status","decision","caseId","gameId","gameVersion","authoritative","scorelinesCreated"]))return false;const v=value as Record<string,unknown>;return v.status===(request.decision==="approve"?"approved":"rejected")&&v.decision===request.decision&&v.caseId===caseId&&isUuid(v.gameId)&&v.gameVersion===request.expectedGameVersion+(request.decision==="approve"?1:0)&&v.authoritative===(request.decision==="approve")&&v.scorelinesCreated===(request.decision==="approve")}
