export type PaymentEvent = { paymentEventId: string; version: number; eventType: "received" | "voided"; amountMinor: number; currencyCode: "USD"; paymentMethod: "cash" | "check" | "other"; paymentReceivedAt: string; paymentVoidedAt: string | null; receiptNote: string | null; voidReason: string | null; recorderDisplayName: string; recordedAt: string };
export type PaymentRosterEntry = { rosterEntryId: string; displayName: string; paymentVersion: number; paymentState: "unrecorded" | "received" | "voided"; currentReceiptEventId: string | null; history: PaymentEvent[] };
export type PaymentWorkspace = { rosterEntries: PaymentRosterEntry[] };
const uuid = (value: unknown): value is string => typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const text = (value: unknown): value is string => typeof value === "string";
const timestamp = (value: unknown): value is string => text(value) && !Number.isNaN(Date.parse(value));
function event(value: unknown): value is PaymentEvent { if (!value || typeof value !== "object") return false; const item = value as Record<string, unknown>; const received = item.eventType === "received"; const voided = item.eventType === "voided"; return uuid(item.paymentEventId) && Number.isInteger(item.version) && (item.version as number) > 0 && ["received", "voided"].includes(item.eventType as string) && Number.isInteger(item.amountMinor) && (item.amountMinor as number) > 0 && item.currencyCode === "USD" && ["cash", "check", "other"].includes(item.paymentMethod as string) && timestamp(item.paymentReceivedAt) && (item.paymentVoidedAt === null || timestamp(item.paymentVoidedAt)) && (item.receiptNote === null || text(item.receiptNote)) && (item.voidReason === null || text(item.voidReason)) && text(item.recorderDisplayName) && timestamp(item.recordedAt) && ((received && item.paymentVoidedAt === null && item.voidReason === null) || (voided && item.paymentVoidedAt !== null && text(item.voidReason) && item.receiptNote === null)); }
function entry(value: unknown): value is PaymentRosterEntry { if (!value || typeof value !== "object") return false; const item = value as Record<string, unknown>; const state = item.paymentState; if (!(uuid(item.rosterEntryId) && text(item.displayName) && Number.isInteger(item.paymentVersion) && (item.paymentVersion as number) >= 0 && ["unrecorded", "received", "voided"].includes(state as string) && (item.currentReceiptEventId === null || uuid(item.currentReceiptEventId)) && Array.isArray(item.history) && item.history.every(event))) return false; const history = item.history as PaymentEvent[]; const version = item.paymentVersion as number; if (version === 0) return state === "unrecorded" && item.currentReceiptEventId === null && history.length === 0; if (history.length !== version || history[0]?.version !== version || history[0]?.eventType !== state) return false; if (history.some((payment, index) => payment.version !== version - index || payment.eventType !== ((payment.version % 2 === 1) ? "received" : "voided"))) return false; return state === "received" ? item.currentReceiptEventId === history[0]?.paymentEventId : item.currentReceiptEventId === null; }
export function isPaymentWorkspace(value: unknown): value is PaymentWorkspace { return !!value && typeof value === "object" && Array.isArray((value as Record<string, unknown>).rosterEntries) && ((value as Record<string, unknown>).rosterEntries as unknown[]).every(entry); }
