export type PaymentEvent = { paymentEventId: string; version: number; eventType: "received" | "voided"; amountMinor: number; currencyCode: "USD"; paymentMethod: "cash" | "check" | "other"; paymentReceivedAt: string; paymentVoidedAt: string | null; receiptNote: string | null; voidReason: string | null; recorderDisplayName: string; recordedAt: string };
export type PaymentRosterEntry = { rosterEntryId: string; displayName: string; plannedPaymentMethod: "cash" | "check" | null; paymentVersion: number; paymentState: "unrecorded" | "received" | "voided"; currentReceiptEventId: string | null; history: PaymentEvent[] };
export type PaymentWorkspace = { rosterEntries: PaymentRosterEntry[] };
export type PaymentRecordRequest = { rosterEntryId: string; expectedPaymentVersion: number; amountMinor: number; paymentMethod: "cash" | "check"; paymentReceivedAt: string; note: string; idempotencyKey: string };
export type PaymentVoidRequest = { rosterEntryId: string; expectedPaymentVersion: number; paymentEventId: string; voidReason: string; idempotencyKey: string };
export type PaymentRecoveryRequest = { rosterEntryId: string; operationType: "record_manual_roster_payment" | "void_manual_roster_payment"; expectedPaymentVersion: number; paymentEventId: string | null; idempotencyKey: string };
const uuid = (value: unknown): value is string => typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const text = (value: unknown): value is string => typeof value === "string";
const timestamp = (value: unknown): value is string => text(value) && !Number.isNaN(Date.parse(value));
const receivedTimestamp = (value: unknown): value is string => text(value) && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) && !Number.isNaN(Date.parse(value)) && new Date(value).toISOString() === value;
const bounded = (value: unknown, required = false) => text(value) && value.length <= 500 && new TextEncoder().encode(value).length <= 2000 && (!required || value.trim().length > 0);
const operation = (value: unknown): value is PaymentRecoveryRequest["operationType"] => value === "record_manual_roster_payment" || value === "void_manual_roster_payment";
export function isPaymentRecordRequest(value: unknown): value is PaymentRecordRequest { if (!value || typeof value !== "object") return false; const item = value as Record<string, unknown>; return uuid(item.rosterEntryId) && Number.isSafeInteger(item.expectedPaymentVersion) && (item.expectedPaymentVersion as number) >= 0 && Number.isSafeInteger(item.amountMinor) && (item.amountMinor as number) > 0 && (item.amountMinor as number) <= 2147483647 && ["cash", "check"].includes(item.paymentMethod as string) && receivedTimestamp(item.paymentReceivedAt) && bounded(item.note) && uuid(item.idempotencyKey); }
export function isPaymentVoidRequest(value: unknown): value is PaymentVoidRequest { if (!value || typeof value !== "object") return false; const item = value as Record<string, unknown>; return uuid(item.rosterEntryId) && Number.isSafeInteger(item.expectedPaymentVersion) && (item.expectedPaymentVersion as number) >= 1 && uuid(item.paymentEventId) && bounded(item.voidReason, true) && uuid(item.idempotencyKey); }
export function isPaymentRecoveryRequest(value: unknown): value is PaymentRecoveryRequest { if (!value || typeof value !== "object") return false; const item = value as Record<string, unknown>; return uuid(item.rosterEntryId) && operation(item.operationType) && Number.isSafeInteger(item.expectedPaymentVersion) && (item.expectedPaymentVersion as number) >= (item.operationType === "void_manual_roster_payment" ? 1 : 0) && (item.operationType === "void_manual_roster_payment" ? uuid(item.paymentEventId) : item.paymentEventId === null) && uuid(item.idempotencyKey); }
type PaymentOutcome = { status: "payment_recorded" | "payment_voided"; paymentEventId: string; rosterEntryId: string; paymentVersion: number; paymentState: "received" | "voided"; paymentRecorded: boolean; paidInFull: false; reconciled: false; voidedPaymentEventId?: string };
function outcome(value: unknown, rosterEntryId: string, status: PaymentOutcome["status"], expectedVersion: number): value is PaymentOutcome { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const item = value as Record<string, unknown>; const voided = status === "payment_voided"; return Object.keys(item).length === (voided ? 9 : 8) && item.status === status && uuid(item.paymentEventId) && item.rosterEntryId === rosterEntryId && item.paymentVersion === expectedVersion + 1 && item.paymentState === (voided ? "voided" : "received") && item.paymentRecorded === !voided && item.paidInFull === false && item.reconciled === false && (voided ? uuid(item.voidedPaymentEventId) : !("voidedPaymentEventId" in item)); }
export function isRecordedPayment(value: unknown, request: PaymentRecordRequest) { return outcome(value, request.rosterEntryId, "payment_recorded", request.expectedPaymentVersion); }
export function isVoidedPayment(value: unknown, request: PaymentVoidRequest) { return outcome(value, request.rosterEntryId, "payment_voided", request.expectedPaymentVersion) && (value as PaymentOutcome).voidedPaymentEventId === request.paymentEventId; }
export function isRecoveredPayment(value: unknown, request: PaymentRecoveryRequest) { return request.operationType === "record_manual_roster_payment" ? outcome(value, request.rosterEntryId, "payment_recorded", request.expectedPaymentVersion) : outcome(value, request.rosterEntryId, "payment_voided", request.expectedPaymentVersion) && (value as PaymentOutcome).voidedPaymentEventId === request.paymentEventId; }
export function isRejectedPayment(value: unknown, rosterEntryId: string, operationType: PaymentRecoveryRequest["operationType"]) { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const item = value as Record<string, unknown>; const codes = operationType === "record_manual_roster_payment" ? ["authentication_required", "not_director", "idempotency_conflict", "stale_payment_history", "active_payment_receipt_exists", "roster_entry_unavailable", "tournament_unavailable", "invalid_request", "payment_recording_rejected"] : ["authentication_required", "not_director", "idempotency_conflict", "stale_payment_history", "current_payment_receipt_required", "roster_entry_unavailable", "tournament_unavailable", "invalid_request", "payment_void_rejected"]; return Object.keys(item).length === 3 && item.status === "rejected" && item.rosterEntryId === rosterEntryId && typeof item.code === "string" && codes.includes(item.code); }
function event(value: unknown): value is PaymentEvent { if (!value || typeof value !== "object") return false; const item = value as Record<string, unknown>; const received = item.eventType === "received"; const voided = item.eventType === "voided"; return uuid(item.paymentEventId) && Number.isInteger(item.version) && (item.version as number) > 0 && ["received", "voided"].includes(item.eventType as string) && Number.isInteger(item.amountMinor) && (item.amountMinor as number) > 0 && item.currencyCode === "USD" && ["cash", "check", "other"].includes(item.paymentMethod as string) && timestamp(item.paymentReceivedAt) && (item.paymentVoidedAt === null || timestamp(item.paymentVoidedAt)) && (item.receiptNote === null || text(item.receiptNote)) && (item.voidReason === null || text(item.voidReason)) && text(item.recorderDisplayName) && timestamp(item.recordedAt) && ((received && item.paymentVoidedAt === null && item.voidReason === null) || (voided && item.paymentVoidedAt !== null && text(item.voidReason) && item.receiptNote === null)); }
function entry(value: unknown): value is PaymentRosterEntry { if (!value || typeof value !== "object") return false; const item = value as Record<string, unknown>; const state = item.paymentState; if (!(uuid(item.rosterEntryId) && text(item.displayName) && (item.plannedPaymentMethod === null || item.plannedPaymentMethod === "cash" || item.plannedPaymentMethod === "check") && Number.isInteger(item.paymentVersion) && (item.paymentVersion as number) >= 0 && ["unrecorded", "received", "voided"].includes(state as string) && (item.currentReceiptEventId === null || uuid(item.currentReceiptEventId)) && Array.isArray(item.history) && item.history.every(event))) return false; const history = item.history as PaymentEvent[]; const version = item.paymentVersion as number; if (version === 0) return state === "unrecorded" && item.currentReceiptEventId === null && history.length === 0; if (history.length !== version || history[0]?.version !== version || history[0]?.eventType !== state) return false; if (history.some((payment, index) => payment.version !== version - index || payment.eventType !== ((payment.version % 2 === 1) ? "received" : "voided"))) return false; return state === "received" ? item.currentReceiptEventId === history[0]?.paymentEventId : item.currentReceiptEventId === null; }
export function isPaymentWorkspace(value: unknown): value is PaymentWorkspace { return !!value && typeof value === "object" && Array.isArray((value as Record<string, unknown>).rosterEntries) && ((value as Record<string, unknown>).rosterEntries as unknown[]).every(entry); }
