import { isEventScheduleWorkspace } from "./event-schedule.ts";
import { isUuid } from "./validation.ts";

export const amendmentKinds = ["omitted_player_before_play", "late_player_before_game_two", "odd_field_first_sitout_makeup", "early_departure_substitute", "odd_field_extra_games", "mixed_rotation_repair", "reinstatement_future_games"] as const;
export type ScheduleAmendmentKind = typeof amendmentKinds[number];
export type AmendmentGame = { gameId: string; gameNumber: number; sideAParticipantId: string; sideBParticipantId: string; sideATableSeat: string; sideBTableSeat: string; standingsEligible: boolean; state: string };
export type ScheduleAmendmentWorkspace = ReturnType<typeof normalizeWorkspace>;
export type ScheduleAmendmentRequest = { eventId: string; amendmentId: string; operationKind: ScheduleAmendmentKind; ruleBasis: string; directorReason: string; proposedSchedule: AmendmentGame[]; expectedVersion: number; idempotencyKey: string };

const rec = (value: unknown): value is Record<string, unknown> => !!value && typeof value === "object" && !Array.isArray(value);
const exact = (value: Record<string, unknown>, keys: string[]) => Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key));
const seat = (value: unknown): value is string => typeof value === "string" && /^[A-Z]-[1-9][0-9]*$/.test(value);
function isGame(value: unknown): value is AmendmentGame { return rec(value) && exact(value, ["gameId", "gameNumber", "sideAParticipantId", "sideBParticipantId", "sideATableSeat", "sideBTableSeat", "standingsEligible", "state"]) && isUuid(value.gameId) && Number.isSafeInteger(value.gameNumber) && (value.gameNumber as number) > 0 && isUuid(value.sideAParticipantId) && isUuid(value.sideBParticipantId) && value.sideAParticipantId !== value.sideBParticipantId && seat(value.sideATableSeat) && seat(value.sideBTableSeat) && typeof value.standingsEligible === "boolean" && typeof value.state === "string"; }

function normalizeWorkspace(value: unknown) {
  if (!rec(value)) return null;
  const base = { tournamentName: value.tournamentName, registrationClosed: value.registrationClosed, tableCount: value.tableCount, seatsPerTable: value.seatsPerTable, events: value.events, participants: value.participants, matches: value.matches };
  if (!isEventScheduleWorkspace(base) || !rec(value.amendmentVersions) || !Array.isArray(value.amendmentSchedule) || !Array.isArray(value.ruleCases) || !Array.isArray(value.forfeits)) return null;
  if (!value.amendmentSchedule.every((item) => rec(item) && exact(item, ["eventId", "games"]) && isUuid(item.eventId) && Array.isArray(item.games) && item.games.every(isGame))) return null;
  if (!value.ruleCases.every((item) => rec(item) && exact(item, ["code", "label", "rule"]) && amendmentKinds.includes(item.code as ScheduleAmendmentKind) && typeof item.label === "string" && typeof item.rule === "string")) return null;
  return { ...base, amendmentVersions: value.amendmentVersions as Record<string, number>, amendmentSchedule: value.amendmentSchedule as Array<{ eventId: string; games: AmendmentGame[] }>, ruleCases: value.ruleCases as Array<{ code: ScheduleAmendmentKind; label: string; rule: string }>, forfeits: value.forfeits as unknown[] };
}
export function isScheduleAmendmentWorkspace(value: unknown): value is NonNullable<ScheduleAmendmentWorkspace> { return normalizeWorkspace(value) !== null; }
export function parseScheduleAmendmentWorkspace(value: unknown): NonNullable<ScheduleAmendmentWorkspace> | null { return normalizeWorkspace(value); }
export function isScheduleAmendmentRequest(value: unknown): value is ScheduleAmendmentRequest { return rec(value) && exact(value, ["eventId", "amendmentId", "operationKind", "ruleBasis", "directorReason", "proposedSchedule", "expectedVersion", "idempotencyKey"]) && isUuid(value.eventId) && isUuid(value.amendmentId) && amendmentKinds.includes(value.operationKind as ScheduleAmendmentKind) && typeof value.ruleBasis === "string" && value.ruleBasis.trim().length > 0 && value.ruleBasis.length <= 500 && typeof value.directorReason === "string" && value.directorReason.trim().length > 0 && value.directorReason.length <= 1000 && Array.isArray(value.proposedSchedule) && value.proposedSchedule.length > 0 && value.proposedSchedule.length <= 5000 && value.proposedSchedule.every(isGame) && Number.isSafeInteger(value.expectedVersion) && (value.expectedVersion as number) >= 0 && isUuid(value.idempotencyKey); }
export function isAmendmentPreview(value: unknown) { return rec(value) && value.status === "schedule_amendment_preview" && isUuid(value.eventId) && Number.isSafeInteger(value.affectedGameCount) && Number.isSafeInteger(value.unaffectedGameCount) && Array.isArray(value.priorSchedule) && Array.isArray(value.proposedSchedule); }
export function isAmendmentApplied(value: unknown, request: ScheduleAmendmentRequest) { return rec(value) && value.status === "schedule_amendment_applied" && value.eventId === request.eventId && value.amendmentId === request.amendmentId && value.version === request.expectedVersion + 1; }
export function isScheduleAmendmentRejected(value: unknown): value is { status: "rejected"; code: string } { return rec(value) && value.status === "rejected" && typeof value.code === "string"; }

export type OperationalForfeitRequest = { eventId: string; gameId: string; forfeitId: string; winnerParticipantId: string; departingParticipantId: string; ruleCase: "early_departure_current_game"; directorReason: string; idempotencyKey: string };
export function isOperationalForfeitRequest(value: unknown): value is OperationalForfeitRequest { return rec(value) && exact(value, ["eventId", "gameId", "forfeitId", "winnerParticipantId", "departingParticipantId", "ruleCase", "directorReason", "idempotencyKey"]) && [value.eventId, value.gameId, value.forfeitId, value.winnerParticipantId, value.departingParticipantId, value.idempotencyKey].every(isUuid) && value.winnerParticipantId !== value.departingParticipantId && value.ruleCase === "early_departure_current_game" && typeof value.directorReason === "string" && value.directorReason.trim().length > 0 && value.directorReason.length <= 1000; }
export function isOperationalForfeitRecorded(value: unknown, request: OperationalForfeitRequest) { return rec(value) && value.status === "operational_forfeit_recorded" && value.gameId === request.gameId && value.forfeitId === request.forfeitId && value.gamePoints === 2 && value.spreadPoints === 10; }
export type PlayerExceptionRequest =
  | { action: "playoff_absence"; eventId: string; participantId: string; decisionId: string; elapsedMinutes: number; reason: string; idempotencyKey: string }
  | { action: "late_refund"; eventId: string; participantId: string; decisionId: string; committedCharges: Array<{ label: string; amountMinor: number }>; reason: string; idempotencyKey: string }
  | { action: "excluded_extra_game"; eventId: string; recordId: string; participantAId: string; participantBId: string; winnerParticipantId: string; margin: number; crossCheckEvidence: Array<{ type: string; ref: string }>; reason: string; idempotencyKey: string };
export function isPlayerExceptionRequest(value: unknown): value is PlayerExceptionRequest {
  if (!rec(value) || typeof value.action !== "string") return false;
  if (value.action === "playoff_absence") return exact(value,["action","eventId","participantId","decisionId","elapsedMinutes","reason","idempotencyKey"]) && [value.eventId,value.participantId,value.decisionId,value.idempotencyKey].every(isUuid) && Number.isSafeInteger(value.elapsedMinutes) && (value.elapsedMinutes as number)>=5 && typeof value.reason==="string" && value.reason.trim().length>0 && value.reason.length<=1000;
  if (value.action === "late_refund") return exact(value,["action","eventId","participantId","decisionId","committedCharges","reason","idempotencyKey"]) && [value.eventId,value.participantId,value.decisionId,value.idempotencyKey].every(isUuid) && Array.isArray(value.committedCharges) && value.committedCharges.length<=100 && value.committedCharges.every((item)=>rec(item)&&exact(item,["label","amountMinor"])&&typeof item.label==="string"&&item.label.trim().length>0&&item.label.length<=100&&Number.isSafeInteger(item.amountMinor)&&(item.amountMinor as number)>=0) && typeof value.reason==="string"&&value.reason.trim().length>0&&value.reason.length<=1000;
  return value.action === "excluded_extra_game" && exact(value,["action","eventId","recordId","participantAId","participantBId","winnerParticipantId","margin","crossCheckEvidence","reason","idempotencyKey"]) && [value.eventId,value.recordId,value.participantAId,value.participantBId,value.winnerParticipantId,value.idempotencyKey].every(isUuid) && value.participantAId!==value.participantBId && [value.participantAId,value.participantBId].includes(value.winnerParticipantId as string) && Number.isSafeInteger(value.margin)&&(value.margin as number)>=1&&(value.margin as number)<=121 && Array.isArray(value.crossCheckEvidence)&&value.crossCheckEvidence.length>=2&&value.crossCheckEvidence.length<=20&&value.crossCheckEvidence.every((item)=>rec(item)&&exact(item,["type","ref"])&&typeof item.type==="string"&&item.type.trim().length>0&&typeof item.ref==="string"&&item.ref.trim().length>0&&item.ref.length<=500) && typeof value.reason==="string"&&value.reason.trim().length>0&&value.reason.length<=1000;
}
export function isPlayerExceptionRecorded(value:unknown,request:PlayerExceptionRequest){if(!rec(value))return false;if(request.action==="playoff_absence")return value.status==="playoff_absence_recorded"&&value.participantId===request.participantId;if(request.action==="late_refund")return value.status==="late_player_refund_decision_recorded"&&value.participantId===request.participantId&&value.ordinaryAdmissionRejected===true;return value.status==="excluded_extra_game_recorded"&&value.recordId===request.recordId&&value.standingsEligible===false;}
