import { isUuid } from "./validation.ts";

export type SidePoolPolicy = { version: number; payoutRatioDenominator: number; postedPayoutSchedule: Array<{ placement: number; amountMinor: number }>; postedBeforePlay: boolean };
export type SidePoolElection = { electionId: string; participantId: string; displayName: string; version: number; elected: boolean; amountDueMinor: number; amountReceivedMinor: number; amountRemainingMinor: number; paymentMethod: "cash" | "check" | null; paymentReference: string | null };
export type SidePoolPayout = { payoutId: string; participantId: string; displayName: string; version: number; placement: number; amountMinor: number; voided: boolean };
export type SidePool = { poolId: string; version: number; categoryCode: string; displayName: string; entryFeeMinor: number; policy: SidePoolPolicy | null; elections: SidePoolElection[]; payouts: SidePoolPayout[]; collectedMinor: number; paidMinor: number; finalized: boolean };
export type SidePoolTeamElection = { poolId:string;electionId:string;version:number;elected:boolean;amountDueMinor:number;amountReceivedMinor:number;amountRemainingMinor:number;paymentMethod:"cash"|"check"|null;paymentReference:string|null };
export type SidePoolTeamPayout = { poolId:string;payoutId:string;version:number;placement:number;amountMinor:number;voided:boolean };
export type SidePoolTeamBeneficiary = { teamEntryId: string; displayName: string; elections:SidePoolTeamElection[]; payouts:SidePoolTeamPayout[] };
export type SidePoolWorkspace = { tournamentName: string; events: Array<{ eventId: string; name: string; eventType: string; pools: SidePool[]; participants: Array<{ participantId: string; displayName: string }>; teamBeneficiaries: SidePoolTeamBeneficiary[] }> };
export type AddSidePoolRequest = { action: "add_pool"; eventId: string; poolId: string; categoryCode: string; displayName: string; entryFeeMinor: number; idempotencyKey: string };
export type SidePoolPolicyRequest = { action: "configure_policy"; eventId: string; poolId: string; payoutRatioDenominator: number; postedPayoutSchedule: Array<{ placement: number; amountMinor: number }>; reason: string; idempotencyKey: string };
export type SidePoolElectionRequest = { action: "set_election"; eventId: string; poolId: string; participantId: string; electionId: string; elected: boolean; amountReceivedMinor: number; paymentMethod: "cash" | "check"; paymentReference: string; reason: string; idempotencyKey: string };
export type SidePoolPayoutRequest = { action: "set_payout"; eventId: string; poolId: string; participantId: string; payoutId: string; placement: number; amountMinor: number; voided: boolean; reason: string; idempotencyKey: string };
export type SidePoolFinalizeRequest = { action: "finalize"; eventId: string; poolId: string; reconciliationId: string; idempotencyKey: string };
export type SidePoolTeamElectionRequest = { action: "set_team_election"; eventId: string; poolId: string; teamEntryId: string; electionId: string; elected: boolean; amountReceivedMinor: number; paymentMethod: "cash" | "check"; paymentReference: string; reason: string; idempotencyKey: string };
export type SidePoolTeamPayoutRequest = { action: "set_team_payout"; eventId: string; poolId: string; teamEntryId: string; payoutId: string; placement: number; amountMinor: number; voided: boolean; reason: string; idempotencyKey: string };
export type SidePoolPayoutReviewRequest = { action: "review_payout"; eventId: string; payoutId: string; beneficiaryKind: "participant" | "team_entry"; approved: boolean; evidenceReference: string; idempotencyKey: string };
export type SidePoolMutation = AddSidePoolRequest | SidePoolPolicyRequest | SidePoolElectionRequest | SidePoolPayoutRequest | SidePoolTeamElectionRequest | SidePoolTeamPayoutRequest | SidePoolPayoutReviewRequest | SidePoolFinalizeRequest;

const record = (value: unknown): value is Record<string, unknown> => !!value && typeof value === "object" && !Array.isArray(value);
const exact = (value: Record<string, unknown>, keys: string[]) => Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key));
const minor = (value: unknown) => Number.isSafeInteger(value) && (value as number) >= 0 && (value as number) <= 100_000_000;
const positive = (value: unknown, max = 10000) => Number.isSafeInteger(value) && (value as number) > 0 && (value as number) <= max;
const reason = (value: unknown) => typeof value === "string" && value.trim().length > 0 && value.length <= 500;
const schedule = (value: unknown): value is Array<{ placement: number; amountMinor: number }> => Array.isArray(value) && value.length > 0 && value.length <= 100 && value.every((item) => record(item) && exact(item, ["placement", "amountMinor"]) && positive(item.placement, 100) && minor(item.amountMinor));
const election = (value: unknown): value is SidePoolElection => record(value) && exact(value, ["electionId", "participantId", "displayName", "version", "elected", "amountDueMinor", "amountReceivedMinor", "amountRemainingMinor", "paymentMethod", "paymentReference"]) && isUuid(value.electionId) && isUuid(value.participantId) && typeof value.displayName === "string" && positive(value.version) && typeof value.elected === "boolean" && minor(value.amountDueMinor) && minor(value.amountReceivedMinor) && minor(value.amountRemainingMinor) && (value.paymentMethod === null || ["cash", "check"].includes(value.paymentMethod as string)) && (value.paymentReference === null || typeof value.paymentReference === "string");
const payout = (value: unknown): value is SidePoolPayout => record(value) && exact(value, ["payoutId", "participantId", "displayName", "version", "placement", "amountMinor", "voided"]) && isUuid(value.payoutId) && isUuid(value.participantId) && typeof value.displayName === "string" && positive(value.version) && positive(value.placement, 10000) && minor(value.amountMinor) && typeof value.voided === "boolean";
export function isSidePoolWorkspace(value: unknown): value is SidePoolWorkspace {
  if (!record(value) || !exact(value, ["tournamentName", "events"]) || typeof value.tournamentName !== "string" || !Array.isArray(value.events)) return false;
  return value.events.every((event) => record(event) && exact(event,["eventId", "name", "eventType", "pools", "participants","teamBeneficiaries"]) && isUuid(event.eventId) && typeof event.name === "string" && typeof event.eventType === "string" && Array.isArray(event.participants) && event.participants.every((p) => record(p) && exact(p, ["participantId", "displayName"]) && isUuid(p.participantId) && typeof p.displayName === "string") && Array.isArray(event.teamBeneficiaries) && event.teamBeneficiaries.every((team)=>record(team)&&exact(team,["teamEntryId","displayName","elections","payouts"])&&isUuid(team.teamEntryId)&&typeof team.displayName==="string"&&Array.isArray(team.elections)&&team.elections.every((item)=>record(item)&&exact(item,["poolId","electionId","version","elected","amountDueMinor","amountReceivedMinor","amountRemainingMinor","paymentMethod","paymentReference"])&&isUuid(item.poolId)&&isUuid(item.electionId)&&positive(item.version)&&typeof item.elected==="boolean"&&minor(item.amountDueMinor)&&minor(item.amountReceivedMinor)&&minor(item.amountRemainingMinor)&&(item.paymentMethod===null||["cash","check"].includes(item.paymentMethod as string))&&(item.paymentReference===null||typeof item.paymentReference==="string"))&&Array.isArray(team.payouts)&&team.payouts.every((item)=>record(item)&&exact(item,["poolId","payoutId","version","placement","amountMinor","voided"])&&isUuid(item.poolId)&&isUuid(item.payoutId)&&positive(item.version)&&positive(item.placement)&&minor(item.amountMinor)&&typeof item.voided==="boolean")) && Array.isArray(event.pools) && event.pools.length <= 6 && event.pools.every((pool) => record(pool) && exact(pool, ["poolId", "version", "categoryCode", "displayName", "entryFeeMinor", "policy", "elections", "payouts", "collectedMinor", "paidMinor", "finalized"]) && isUuid(pool.poolId) && positive(pool.version) && typeof pool.categoryCode === "string" && pool.categoryCode.trim().length > 0 && pool.categoryCode.length <= 100 && typeof pool.displayName === "string" && pool.displayName.trim().length > 0 && minor(pool.entryFeeMinor) && (pool.policy === null || (record(pool.policy) && exact(pool.policy, ["version", "payoutRatioDenominator", "postedPayoutSchedule", "postedBeforePlay"]) && positive(pool.policy.version) && positive(pool.policy.payoutRatioDenominator, 100) && schedule(pool.policy.postedPayoutSchedule) && pool.policy.postedBeforePlay === true)) && Array.isArray(pool.elections) && pool.elections.every(election) && Array.isArray(pool.payouts) && pool.payouts.every(payout) && minor(pool.collectedMinor) && minor(pool.paidMinor) && typeof pool.finalized === "boolean"));
}
export function isAddSidePoolRequest(value: unknown): value is AddSidePoolRequest { return record(value) && exact(value, ["action", "eventId", "poolId", "categoryCode", "displayName", "entryFeeMinor", "idempotencyKey"]) && value.action === "add_pool" && isUuid(value.eventId) && isUuid(value.poolId) && typeof value.categoryCode === "string" && value.categoryCode.trim().length > 0 && value.categoryCode.length <= 100 && typeof value.displayName === "string" && value.displayName.trim().length > 0 && value.displayName.length <= 100 && minor(value.entryFeeMinor) && isUuid(value.idempotencyKey); }
export function isSidePoolMutation(value: unknown): value is SidePoolMutation {
  if (isAddSidePoolRequest(value)) return true; if (!record(value) || typeof value.action !== "string") return false;
  if (value.action === "configure_policy") return exact(value, ["action", "eventId", "poolId", "payoutRatioDenominator", "postedPayoutSchedule", "reason", "idempotencyKey"]) && isUuid(value.eventId) && isUuid(value.poolId) && positive(value.payoutRatioDenominator, 100) && schedule(value.postedPayoutSchedule) && reason(value.reason) && isUuid(value.idempotencyKey);
  if (value.action === "set_election") return exact(value, ["action", "eventId", "poolId", "participantId", "electionId", "elected", "amountReceivedMinor", "paymentMethod", "paymentReference", "reason", "idempotencyKey"]) && [value.eventId, value.poolId, value.participantId, value.electionId, value.idempotencyKey].every(isUuid) && typeof value.elected === "boolean" && minor(value.amountReceivedMinor) && ["cash", "check"].includes(value.paymentMethod as string) && typeof value.paymentReference === "string" && value.paymentReference.length <= 100 && reason(value.reason);
  if (value.action === "set_payout") return exact(value, ["action", "eventId", "poolId", "participantId", "payoutId", "placement", "amountMinor", "voided", "reason", "idempotencyKey"]) && [value.eventId, value.poolId, value.participantId, value.payoutId, value.idempotencyKey].every(isUuid) && positive(value.placement, 10000) && minor(value.amountMinor) && typeof value.voided === "boolean" && reason(value.reason);
  if (value.action === "set_team_election") return exact(value, ["action", "eventId", "poolId", "teamEntryId", "electionId", "elected", "amountReceivedMinor", "paymentMethod", "paymentReference", "reason", "idempotencyKey"]) && [value.eventId, value.poolId, value.teamEntryId, value.electionId, value.idempotencyKey].every(isUuid) && typeof value.elected === "boolean" && minor(value.amountReceivedMinor) && ["cash", "check"].includes(value.paymentMethod as string) && typeof value.paymentReference === "string" && value.paymentReference.length <= 100 && reason(value.reason);
  if (value.action === "set_team_payout") return exact(value, ["action", "eventId", "poolId", "teamEntryId", "payoutId", "placement", "amountMinor", "voided", "reason", "idempotencyKey"]) && [value.eventId, value.poolId, value.teamEntryId, value.payoutId, value.idempotencyKey].every(isUuid) && positive(value.placement, 10000) && minor(value.amountMinor) && typeof value.voided === "boolean" && reason(value.reason);
  if (value.action === "review_payout") return exact(value, ["action", "eventId", "payoutId", "beneficiaryKind", "approved", "evidenceReference", "idempotencyKey"]) && [value.eventId, value.payoutId, value.idempotencyKey].every(isUuid) && ["participant", "team_entry"].includes(value.beneficiaryKind as string) && typeof value.approved === "boolean" && typeof value.evidenceReference === "string" && value.evidenceReference.trim().length > 0 && value.evidenceReference.length <= 500;
  return value.action === "finalize" && exact(value, ["action", "eventId", "poolId", "reconciliationId", "idempotencyKey"]) && [value.eventId, value.poolId, value.reconciliationId, value.idempotencyKey].every(isUuid);
}
export function isAddedSidePool(value: unknown, request: AddSidePoolRequest) { return record(value) && value.status === "side_pool_added" && value.eventId === request.eventId && value.poolId === request.poolId && value.version === 1; }
export function isSidePoolMutationResult(value: unknown, request: SidePoolMutation) { if (!record(value)) return false; if (request.action === "add_pool") return isAddedSidePool(value, request); if (request.action === "configure_policy") return value.status === "side_pool_policy_configured" && value.poolId === request.poolId; if (request.action === "set_election") return value.status === "side_pool_election_recorded" && value.poolId === request.poolId && value.participantId === request.participantId; if (request.action === "set_payout") return value.status === "side_pool_payout_recorded" && value.poolId === request.poolId && value.participantId === request.participantId; if (request.action === "set_team_election") return value.status === "side_pool_team_election_recorded" && value.poolId === request.poolId && value.teamEntryId === request.teamEntryId; if (request.action === "set_team_payout") return value.status === "side_pool_team_payout_recorded" && value.poolId === request.poolId && value.teamEntryId === request.teamEntryId; if (request.action === "review_payout") return value.status === "side_pool_payout_reviewed" && value.payoutId === request.payoutId; return value.status === "side_pool_finalized" && value.poolId === request.poolId && value.remainingMinor === 0; }
export function isRejectedSidePool(value: unknown): value is { status: "rejected"; code: string } { return record(value) && value.status === "rejected" && typeof value.code === "string"; }
