import { isUuid } from "./validation.ts";

export type TeamMember = { rosterEntryId:string; displayName:string; accNumber:string; profileLinked:boolean; role:"captain"|"member" };
export type TeamEntry = { teamId:string; teamEntryId:string; displayName:string; members:TeamMember[]; scorecardType:"digital"|"paper"; designatedScorerProfileId:string|null; scorerResolutionStatus:"not_required"|"unresolved"|"resolved"; configurationVersion:number; verificationId:string|null; initialTableSeat:string|null };
export type TeamSubmission = { submissionId:string; side:"a"|"b"; winnerSide:"a"|"b"; margin:number; sourceMethod:"digital"|"paper_transcription"; own:boolean; confirmed:boolean; paperCardReference:string|null; paperReviewed:boolean; paperReviewMismatch:boolean };
export type TeamGameMember = {rosterEntryId:string;displayName:string;accNumber:string;currentTableSeat:string};
export type TeamGame = { gameId:string; gameNumber:number; state:string; version:number; sideATeamEntryId:string; sideBTeamEntryId:string; sideATableSeat:string; sideBTableSeat:string; sideAMembers:TeamGameMember[];sideBMembers:TeamGameMember[];winnerSide:"a"|"b"|null; margin:number|null; submissions:TeamSubmission[] };
export type PendingTeamCorrection = {correctionId:string;gameId:string;editorProfileId:string;winnerSide:"a"|"b";margin:number;reason:string|null;baseGameVersion:number};
export type PendingTeamMismatchResolution = {resolutionId:string;gameId:string;resolverProfileId:string;winnerSide:"a"|"b";margin:number;reason:string;baseGameVersion:number};
export type TeamEvent = { eventId:string; name:string; format:"doubles"|"canadian_doubles"; configuredGameCount:number; started:boolean; schedulePublicationId:string|null; teams:TeamEntry[]; games:TeamGame[]; standings:Array<{teamEntryId:string;displayName:string;gamePoints:number;gamesWon:number;plusPoints:number;minusPoints:number;netSpreadPoints:number}>;pendingCorrections:PendingTeamCorrection[];pendingMismatchResolutions:PendingTeamMismatchResolution[] };
export type TeamWorkspace = { tournamentId:string;tournamentName:string;canManage:boolean;canCrossCheck:boolean;actorId:string;events:TeamEvent[];roster:Array<{rosterEntryId:string;displayName:string;accNumber:string;profileId:string|null;personalScorecardType:"digital"|"paper"}> };
export type TeamMutation =
 | {action:"create_team";eventId:string;teamId:string;teamEntryId:string;captainRosterEntryId:string;partnerRosterEntryId:string;scorecardType:"digital"|"paper";operationId:string}
 | {action:"claim_partner";eventId:string;teamId:string;rosterEntryId:string;claimId:string;operationId:string}
 | {action:"configure_team";eventId:string;teamEntryId:string;scorecardType:"digital"|"paper";designatedScorerProfileId:string|null;expectedVersion:number;reason:string;operationId:string}
 | {action:"publish_seating";eventId:string;publicationId:string;assignments:Array<{teamEntryId:string;tableSeat:string}>;operationId:string}
 | {action:"publish_schedule";eventId:string;publicationId:string;gameCount:number;games:Array<{gameId:string;gameNumber:number;matchInstance:number;sideATeamEntryId:string;sideBTeamEntryId:string;sideATableSeat:string;sideBTableSeat:string}>;operationId:string}
 | {action:"start_play";eventId:string;startId:string;schedulePublicationId:string;operationId:string}
 | {action:"submit_score";eventId:string;gameId:string;submissionId:string;winnerSide:"a"|"b";margin:number;operationId:string}
 | {action:"submit_paper_score";eventId:string;gameId:string;submissionId:string;side:"a"|"b";paperCardReference:string;winnerSide:"a"|"b";margin:number;operationId:string}
 | {action:"review_paper_score";eventId:string;gameId:string;submissionId:string;reviewId:string;paperCardReference:string;winnerSide:"a"|"b";margin:number;operationId:string}
 | {action:"confirm_score";eventId:string;gameId:string;submissionId:string;confirmationId:string;operationId:string}
 | {action:"correct_score";eventId:string;gameId:string;correctionId:string;expectedGameVersion:number;winnerSide:"a"|"b";margin:number;reason:string;operationId:string}
 | {action:"review_correction";eventId:string;correctionId:string;reviewId:string;approved:boolean;operationId:string}
 | {action:"resolve_mismatch";eventId:string;gameId:string;resolutionId:string;expectedGameVersion:number;winnerSide:"a"|"b";margin:number;reason:string;operationId:string}
 | {action:"review_mismatch";eventId:string;resolutionId:string;reviewId:string;approved:boolean;operationId:string};

const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
const exact=(v:Record<string,unknown>,keys:string[])=>Object.keys(v).length===keys.length&&keys.every((key)=>key in v);
const seat=(v:unknown)=>typeof v==="string"&&/^[A-Z]-[1-9][0-9]*$/.test(v);
const ids=(v:unknown[])=>v.every(isUuid);
const nonnegative=(v:unknown)=>Number.isSafeInteger(v)&&(v as number)>=0;
const member=(v:unknown)=>object(v)&&exact(v,["rosterEntryId","displayName","accNumber","profileLinked","role"])&&isUuid(v.rosterEntryId)&&typeof v.displayName==="string"&&typeof v.accNumber==="string"&&typeof v.profileLinked==="boolean"&&["captain","member"].includes(String(v.role));
const gameMember=(v:unknown)=>object(v)&&exact(v,["rosterEntryId","displayName","accNumber","currentTableSeat"])&&isUuid(v.rosterEntryId)&&typeof v.displayName==="string"&&typeof v.accNumber==="string"&&seat(v.currentTableSeat);
const team=(v:unknown)=>object(v)&&exact(v,["teamId","teamEntryId","displayName","members","scorecardType","designatedScorerProfileId","scorerResolutionStatus","configurationVersion","verificationId","initialTableSeat"])&&ids([v.teamId,v.teamEntryId])&&typeof v.displayName==="string"&&Array.isArray(v.members)&&v.members.length===2&&v.members.every(member)&&new Set(v.members.map((item)=>(item as TeamMember).rosterEntryId)).size===2&&["digital","paper"].includes(String(v.scorecardType))&&(v.designatedScorerProfileId===null||isUuid(v.designatedScorerProfileId))&&["not_required","unresolved","resolved"].includes(String(v.scorerResolutionStatus))&&Number.isSafeInteger(v.configurationVersion)&&(v.configurationVersion as number)>0&&(v.verificationId===null||seat(v.verificationId))&&(v.initialTableSeat===null||seat(v.initialTableSeat));
const submission=(v:unknown)=>object(v)&&exact(v,["submissionId","side","winnerSide","margin","sourceMethod","own","confirmed","paperCardReference","paperReviewed","paperReviewMismatch"])&&isUuid(v.submissionId)&&["a","b"].includes(String(v.side))&&["a","b"].includes(String(v.winnerSide))&&Number.isSafeInteger(v.margin)&&(v.margin as number)>=1&&(v.margin as number)<=121&&["digital","paper_transcription"].includes(String(v.sourceMethod))&&typeof v.own==="boolean"&&typeof v.confirmed==="boolean"&&(v.paperCardReference===null||typeof v.paperCardReference==="string")&&typeof v.paperReviewed==="boolean"&&typeof v.paperReviewMismatch==="boolean";
const game=(v:unknown)=>object(v)&&exact(v,["gameId","gameNumber","state","version","sideATeamEntryId","sideBTeamEntryId","sideATableSeat","sideBTableSeat","sideAMembers","sideBMembers","winnerSide","margin","submissions"])&&ids([v.gameId,v.sideATeamEntryId,v.sideBTeamEntryId])&&v.sideATeamEntryId!==v.sideBTeamEntryId&&Number.isSafeInteger(v.gameNumber)&&(v.gameNumber as number)>0&&typeof v.state==="string"&&Number.isSafeInteger(v.version)&&(v.version as number)>0&&seat(v.sideATableSeat)&&seat(v.sideBTableSeat)&&Array.isArray(v.sideAMembers)&&v.sideAMembers.length===2&&v.sideAMembers.every(gameMember)&&Array.isArray(v.sideBMembers)&&v.sideBMembers.length===2&&v.sideBMembers.every(gameMember)&&(v.winnerSide===null||["a","b"].includes(String(v.winnerSide)))&&(v.margin===null||(Number.isSafeInteger(v.margin)&&(v.margin as number)>=1&&(v.margin as number)<=121))&&Array.isArray(v.submissions)&&v.submissions.every(submission);
const standing=(v:unknown)=>object(v)&&exact(v,["teamEntryId","displayName","gamePoints","gamesWon","plusPoints","minusPoints","netSpreadPoints"])&&isUuid(v.teamEntryId)&&typeof v.displayName==="string"&&[v.gamePoints,v.gamesWon,v.plusPoints,v.minusPoints].every(nonnegative)&&Number.isSafeInteger(v.netSpreadPoints);
const pendingCorrection=(v:unknown)=>object(v)&&exact(v,["correctionId","gameId","editorProfileId","winnerSide","margin","reason","baseGameVersion"])&&ids([v.correctionId,v.gameId,v.editorProfileId])&&["a","b"].includes(String(v.winnerSide))&&Number.isSafeInteger(v.margin)&&(v.margin as number)>=1&&(v.margin as number)<=121&&(v.reason===null||typeof v.reason==="string")&&Number.isSafeInteger(v.baseGameVersion)&&(v.baseGameVersion as number)>0;
const pendingMismatch=(v:unknown)=>object(v)&&exact(v,["resolutionId","gameId","resolverProfileId","winnerSide","margin","reason","baseGameVersion"])&&ids([v.resolutionId,v.gameId,v.resolverProfileId])&&["a","b"].includes(String(v.winnerSide))&&Number.isSafeInteger(v.margin)&&(v.margin as number)>=1&&(v.margin as number)<=121&&typeof v.reason==="string"&&Number.isSafeInteger(v.baseGameVersion)&&(v.baseGameVersion as number)>0;
const event=(v:unknown)=>object(v)&&exact(v,["eventId","name","format","configuredGameCount","started","schedulePublicationId","teams","games","standings","pendingCorrections","pendingMismatchResolutions"])&&isUuid(v.eventId)&&typeof v.name==="string"&&["doubles","canadian_doubles"].includes(String(v.format))&&Number.isSafeInteger(v.configuredGameCount)&&(v.configuredGameCount as number)>0&&typeof v.started==="boolean"&&(v.schedulePublicationId===null||isUuid(v.schedulePublicationId))&&Array.isArray(v.teams)&&v.teams.every(team)&&Array.isArray(v.games)&&v.games.every(game)&&Array.isArray(v.standings)&&v.standings.every(standing)&&Array.isArray(v.pendingCorrections)&&v.pendingCorrections.every(pendingCorrection)&&Array.isArray(v.pendingMismatchResolutions)&&v.pendingMismatchResolutions.every(pendingMismatch);
const roster=(v:unknown)=>object(v)&&exact(v,["rosterEntryId","displayName","accNumber","profileId","personalScorecardType"])&&isUuid(v.rosterEntryId)&&typeof v.displayName==="string"&&typeof v.accNumber==="string"&&(v.profileId===null||isUuid(v.profileId))&&["digital","paper"].includes(String(v.personalScorecardType));
export function isTeamMutation(v:unknown):v is TeamMutation { if(!object(v)||typeof v.action!=="string"||!isUuid(v.eventId)||!isUuid(v.operationId))return false;
 if(v.action==="create_team")return ids([v.teamId,v.teamEntryId,v.captainRosterEntryId,v.partnerRosterEntryId])&&v.captainRosterEntryId!==v.partnerRosterEntryId&&["digital","paper"].includes(String(v.scorecardType));
 if(v.action==="claim_partner")return ids([v.teamId,v.rosterEntryId,v.claimId]);
 if(v.action==="configure_team")return isUuid(v.teamEntryId)&&["digital","paper"].includes(String(v.scorecardType))&&(v.designatedScorerProfileId===null||isUuid(v.designatedScorerProfileId))&&Number.isSafeInteger(v.expectedVersion)&&(v.expectedVersion as number)>0&&typeof v.reason==="string"&&v.reason.length<=500;
 if(v.action==="publish_seating")return isUuid(v.publicationId)&&Array.isArray(v.assignments)&&v.assignments.length>1&&v.assignments.every(a=>object(a)&&isUuid(a.teamEntryId)&&seat(a.tableSeat));
 if(v.action==="publish_schedule")return isUuid(v.publicationId)&&Number.isSafeInteger(v.gameCount)&&(v.gameCount as number)>0&&(v.gameCount as number)<=99&&Array.isArray(v.games)&&v.games.length>0&&v.games.every(g=>object(g)&&isUuid(g.gameId)&&Number.isSafeInteger(g.gameNumber)&&Number.isSafeInteger(g.matchInstance)&&isUuid(g.sideATeamEntryId)&&isUuid(g.sideBTeamEntryId)&&g.sideATeamEntryId!==g.sideBTeamEntryId&&seat(g.sideATableSeat)&&seat(g.sideBTableSeat));
 if(v.action==="start_play")return ids([v.startId,v.schedulePublicationId]);
 if(v.action==="submit_score")return ids([v.gameId,v.submissionId])&&["a","b"].includes(String(v.winnerSide))&&Number.isSafeInteger(v.margin)&&(v.margin as number)>=1&&(v.margin as number)<=121;
 if(v.action==="submit_paper_score")return ids([v.gameId,v.submissionId])&&["a","b"].includes(String(v.side))&&typeof v.paperCardReference==="string"&&v.paperCardReference.length<=100&&["a","b"].includes(String(v.winnerSide))&&Number.isSafeInteger(v.margin)&&(v.margin as number)>=1&&(v.margin as number)<=121;
 if(v.action==="review_paper_score")return ids([v.gameId,v.submissionId,v.reviewId])&&typeof v.paperCardReference==="string"&&v.paperCardReference.length<=100&&["a","b"].includes(String(v.winnerSide))&&Number.isSafeInteger(v.margin)&&(v.margin as number)>=1&&(v.margin as number)<=121;
 if(v.action==="confirm_score")return ids([v.gameId,v.submissionId,v.confirmationId]);
 if(v.action==="correct_score")return ids([v.gameId,v.correctionId])&&Number.isSafeInteger(v.expectedGameVersion)&&(v.expectedGameVersion as number)>0&&["a","b"].includes(String(v.winnerSide))&&Number.isSafeInteger(v.margin)&&(v.margin as number)>=1&&(v.margin as number)<=121&&typeof v.reason==="string"&&v.reason.length<=500;
 if(v.action==="review_correction")return ids([v.correctionId,v.reviewId])&&typeof v.approved==="boolean";
 if(v.action==="resolve_mismatch")return ids([v.gameId,v.resolutionId])&&Number.isSafeInteger(v.expectedGameVersion)&&(v.expectedGameVersion as number)>0&&["a","b"].includes(String(v.winnerSide))&&Number.isSafeInteger(v.margin)&&(v.margin as number)>=1&&(v.margin as number)<=121&&typeof v.reason==="string"&&v.reason.trim().length>0&&v.reason.length<=500;
 if(v.action==="review_mismatch")return ids([v.resolutionId,v.reviewId])&&typeof v.approved==="boolean";
 return false; }

export function isTeamWorkspace(v:unknown):v is TeamWorkspace { return object(v)&&exact(v,["tournamentId","tournamentName","canManage","canCrossCheck","actorId","events","roster"])&&isUuid(v.tournamentId)&&typeof v.tournamentName==="string"&&typeof v.canManage==="boolean"&&typeof v.canCrossCheck==="boolean"&&isUuid(v.actorId)&&Array.isArray(v.events)&&v.events.every(event)&&Array.isArray(v.roster)&&v.roster.every(roster); }
export function isTeamMutationResult(v:unknown):v is Record<string,unknown>&{status:string}{return object(v)&&typeof v.status==="string"&&v.status!=="rejected";}
export function isRejectedTeamMutation(v:unknown):v is {status:"rejected";code:string}{return object(v)&&v.status==="rejected"&&typeof v.code==="string";}

export type SeatingDirectory = {tournamentId:string;tournamentName:string;entries:Array<{entryKind:"player"|"team_member";eventId:string;eventName:string;displayName:string;teamName:string|null;scorecardType:"digital"|"paper";assignedTableSeat:string;verificationId:string;currentTableSeat:string|null;isSelf:boolean}>};
export function isSeatingDirectory(v:unknown):v is SeatingDirectory{return object(v)&&exact(v,["tournamentId","tournamentName","entries"])&&isUuid(v.tournamentId)&&typeof v.tournamentName==="string"&&Array.isArray(v.entries)&&v.entries.every((entry)=>object(entry)&&exact(entry,["entryKind","eventId","eventName","displayName","teamName","scorecardType","assignedTableSeat","verificationId","currentTableSeat","isSelf"])&&["player","team_member"].includes(String(entry.entryKind))&&isUuid(entry.eventId)&&typeof entry.eventName==="string"&&typeof entry.displayName==="string"&&(entry.teamName===null||typeof entry.teamName==="string")&&["digital","paper"].includes(String(entry.scorecardType))&&seat(entry.assignedTableSeat)&&seat(entry.verificationId)&&(entry.currentTableSeat===null||seat(entry.currentTableSeat))&&typeof entry.isSelf==="boolean");}
