import "server-only";
import { isAccepted, isOfficialRejection, isOfficialsWorkspace, type OfficialsWorkspace } from "./api/officials.ts";
type Client = { rpc(name: string, args: Record<string, unknown>): PromiseLike<{ data: unknown; error: unknown }> };
export async function getOfficialsWorkspace(admin: Client, actorId: string, tournamentId: string): Promise<OfficialsWorkspace | null> { const { data, error } = await admin.rpc("get_tournament_officials_workspace_v1", { p_actor_id: actorId, p_tournament_id: tournamentId }); if (error) throw new Error("Officials workspace is unavailable."); return data === null ? null : isOfficialsWorkspace(data) ? data : (() => { throw new Error("Officials workspace is unavailable."); })(); }
export async function inviteCoDirector(admin: Client, input: { actorId: string; tournamentId: string; email: string; secret: string; operationId: string }) { const { data, error } = await admin.rpc("invite_tournament_co_director_v1", { p_actor_id: input.actorId, p_tournament_id: input.tournamentId, p_email: input.email, p_secret: input.secret, p_operation_id: input.operationId }); if (error || (!isAccepted(data) && !isOfficialRejection(data))) throw new Error("Co-director invitation was not accepted."); return data; }
export async function acceptCoDirector(admin: Client, input: { actorId: string; secret: string; operationId: string }) { const { data, error } = await admin.rpc("accept_tournament_co_director_invite_v1", { p_actor_id: input.actorId, p_secret: input.secret, p_operation_id: input.operationId }); if (error || (!isAccepted(data) && !isOfficialRejection(data))) throw new Error("Co-director acceptance was not accepted."); return data; }
export async function acceptSetupOfficial(admin: Client, input: { actorId: string; secret: string; operationId: string }) { const { data, error } = await admin.rpc("accept_tournament_setup_official_nomination_v1", { p_actor_id: input.actorId, p_secret: input.secret, p_operation_id: input.operationId }); if (error || !data || typeof data !== "object") throw new Error("Official invitation was not accepted."); return data as Record<string, unknown>; }
export async function acceptSetupOfficialById(admin: Client, input: { actorId: string; nominationId: string; operationId: string }) { const { data, error } = await admin.rpc("accept_tournament_setup_official_nomination_by_id_v1", { p_actor_id: input.actorId, p_nomination_id: input.nominationId, p_operation_id: input.operationId }); if (error || !data || typeof data !== "object") throw new Error("Official invitation was not accepted."); return data as Record<string, unknown>; }
export async function manageCoDirector(admin: Client, input: { actorId: string; tournamentId: string; invitationId: string; action: string; reason: string; emergency: boolean; operationId: string }) { const { data, error } = await admin.rpc("manage_tournament_co_director_v1", { p_actor_id: input.actorId, p_tournament_id: input.tournamentId, p_invitation_id: input.invitationId, p_action: input.action, p_reason: input.reason, p_emergency: input.emergency, p_operation_id: input.operationId }); if (error || (!isAccepted(data) && !isOfficialRejection(data))) throw new Error("Co-director change was not accepted."); return data; }
