import "server-only";
import { notFound } from "next/navigation";
import { isUuid } from "../api/validation";
import { createServerOnlyAdminClient } from "../supabase/private-admin";

export type HybridGameItem={gameId:string;eventId?:string;caseId?:string;eventName:string;gameNumber:number;gameVersion:number;digitalSubmissionId:string;digitalWinnerSide:"a"|"b";digitalMargin:number;digitalSide:"a"|"b";digitalPlayerName:string;paperPlayerName:string;paperVerificationId:string};
export type HybridWorkspace={tournamentId:string;tournamentName:string;actorRole:"director"|"co_director"|"cross_checker";actorIdentityConfirmed:boolean;candidates:HybridGameItem[];reviewCases:HybridGameItem[]};
const keys=(v:object,k:string[])=>Object.keys(v).length===k.length&&k.every(x=>x in v);
function item(value:unknown,review:boolean):value is HybridGameItem{if(!value||typeof value!=="object"||Array.isArray(value))return false;const v=value as Record<string,unknown>;const expected=review?["caseId","gameId","eventName","gameNumber","gameVersion","digitalSubmissionId","digitalWinnerSide","digitalMargin","digitalSide","digitalPlayerName","paperPlayerName","paperVerificationId"]:["gameId","eventId","eventName","gameNumber","gameVersion","digitalSubmissionId","digitalWinnerSide","digitalMargin","digitalSide","digitalPlayerName","paperPlayerName","paperVerificationId"];return keys(value,expected)&&(!review||isUuid(v.caseId))&&isUuid(v.gameId)&&(!("eventId" in v)||isUuid(v.eventId))&&isUuid(v.digitalSubmissionId)&&typeof v.eventName==="string"&&Number.isInteger(v.gameNumber)&&Number.isInteger(v.gameVersion)&&(v.digitalWinnerSide==="a"||v.digitalWinnerSide==="b")&&Number.isInteger(v.digitalMargin)&&(v.digitalSide==="a"||v.digitalSide==="b")&&typeof v.digitalPlayerName==="string"&&typeof v.paperPlayerName==="string"&&typeof v.paperVerificationId==="string"}
function valid(value:unknown):value is HybridWorkspace{if(!value||typeof value!=="object"||Array.isArray(value)||!keys(value,["tournamentId","tournamentName","actorRole","actorIdentityConfirmed","candidates","reviewCases"]))return false;const v=value as Record<string,unknown>;return isUuid(v.tournamentId)&&typeof v.tournamentName==="string"&&["director","co_director","cross_checker"].includes(v.actorRole as string)&&typeof v.actorIdentityConfirmed==="boolean"&&Array.isArray(v.candidates)&&v.candidates.every(x=>item(x,false))&&Array.isArray(v.reviewCases)&&v.reviewCases.every(x=>item(x,true))}
export async function getHybridWorkspace(actorId:string,tournamentId:string){const{data,error}=await createServerOnlyAdminClient().rpc("get_hybrid_game_workspace_v1",{p_actor_id:actorId,p_tournament_id:tournamentId});if(error||!valid(data)||data.tournamentId!==tournamentId)notFound();return data}
