"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import type { CorrectionNoticeTarget, CorrectionProposalCandidate, PendingCorrectionReview } from "../../../../lib/corrections/types";

type Claim = { outcome: "win" | "loss"; margin: string; column: "plus" | "minus" | "blank"; apparentQualifier: boolean };
type SavedProposal = { correctionId:string; idempotencyKey:string; expectedGameVersion:number; expectedCorrectionSequence:number; ruleCase:string; claimA:{outcome:"win"|"loss";margin:number|null;column:"plus"|"minus"|"blank";apparentQualifier:boolean}; claimB:{outcome:"win"|"loss";margin:number|null;column:"plus"|"minus"|"blank";apparentQualifier:boolean}; qualificationChanged:boolean; affectedParticipantId:string|null; reason?:string };
type SavedReview = { decision:"approve"|"reject"; idempotencyKey:string };
const ruleLabels={a:"12.2(a) — one apparent qualifier, different spreads",b:"12.2(b) — two apparent qualifiers, different spreads",c:"12.2(c) — one spread is blank",d:"12.2(d) — same result, opposite columns",e:"12.2(e) — same result, same column",f:"12.2(f) — one win, same column",h:"12.2(h) — adverse discrepancy stands"} as const;
function stored<T>(key:string):T|null{try{return JSON.parse(sessionStorage.getItem(key)??"null") as T|null}catch{return null}}

function ClaimEditor({name,claim,setClaim}:{name:string;claim:Claim;setClaim:(v:Claim)=>void}){return <fieldset><legend>{name}&apos;s original card</legend><label>Result<select value={claim.outcome} onChange={e=>setClaim({...claim,outcome:e.target.value as Claim["outcome"]})}><option value="win">Win</option><option value="loss">Loss</option></select></label><label>Spread<input inputMode="numeric" value={claim.margin} disabled={claim.column==="blank"} onChange={e=>setClaim({...claim,margin:e.target.value.replace(/\D/g,"").slice(0,3)})}/></label><label>Column<select value={claim.column} onChange={e=>setClaim({...claim,column:e.target.value as Claim["column"],margin:e.target.value==="blank"?"":claim.margin})}><option value="plus">Plus (+)</option><option value="minus">Minus (−)</option><option value="blank">Blank</option></select></label><label><input type="checkbox" checked={claim.apparentQualifier} onChange={e=>setClaim({...claim,apparentQualifier:e.target.checked})}/> Apparent qualifier</label></fieldset>}

function Proposal({actorId,item,noticeTargets}:{actorId:string;item:CorrectionProposalCandidate;noticeTargets:CorrectionNoticeTarget[]}){
 const router=useRouter(),key=`acc-correction:proposal:${actorId}:${item.gameId}`,targets=noticeTargets.filter(t=>t.eventId===item.eventId);const[ruleCase,setRuleCase]=useState<keyof typeof ruleLabels>("a"),[a,setA]=useState<Claim>({outcome:item.sideA.isWinner?"win":"loss",margin:String(item.sideA.margin),column:item.sideA.isWinner?"plus":"minus",apparentQualifier:false}),[b,setB]=useState<Claim>({outcome:item.sideB.isWinner?"win":"loss",margin:String(item.sideB.margin),column:item.sideB.isWinner?"plus":"minus",apparentQualifier:false}),[qualificationChanged,setQualificationChanged]=useState(false),[affectedParticipantId,setAffectedParticipantId]=useState(targets[0]?.participantId??""),[reason,setReason]=useState(""),[locked,setLocked]=useState<SavedProposal|null>(null),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
 const reconcile=useCallback(async(p:SavedProposal)=>{try{const r=await fetch(`/api/v1/corrections/${p.correctionId}/reconciliation`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({idempotencyKey:p.idempotencyKey})});return r.ok?await r.json():null}catch{return undefined}},[]);
 useEffect(()=>{void(async()=>{const p=stored<SavedProposal>(key);if(!p){setBusy(false);return}const result=await reconcile(p);if(result?.state==="resolved"){sessionStorage.removeItem(key);router.refresh();return}setLocked(p);setMessage("The prior correction is unresolved. Retry sends the exact saved card evidence.");setBusy(false)})()},[key,reconcile,router]);
 async function save(){const fresh:SavedProposal={correctionId:crypto.randomUUID(),idempotencyKey:crypto.randomUUID(),expectedGameVersion:item.gameVersion,expectedCorrectionSequence:item.correctionSequence,ruleCase:`12.2${ruleCase}`,claimA:{...a,margin:a.column==="blank"?null:Number(a.margin)},claimB:{...b,margin:b.column==="blank"?null:Number(b.margin)},qualificationChanged,affectedParticipantId:qualificationChanged?affectedParticipantId:null,...(reason?{reason}:{})};const payload=locked??fresh;sessionStorage.setItem(key,JSON.stringify(payload));setLocked(payload);setBusy(true);setMessage("");try{const response=await fetch(`/api/v1/games/${item.gameId}/corrections`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json().catch(()=>null);if(!response.ok){if(response.status<500){sessionStorage.removeItem(key);setLocked(null)}setMessage(response.status===400?"These card entries do not match the selected Rule 12.2 case.":"The correction was not accepted. Refresh, or retry the exact saved request.");return}sessionStorage.removeItem(key);setLocked(null);setMessage(result.status==="pending"?"Correction saved for independent approval.":"Correction applied. Scorecard totals and preliminary standings now use the adjudicated card values.");router.refresh()}catch{setMessage("Network issue. Retry sends the exact saved correction.")}finally{setBusy(false)}}
 return <li className="correction-item"><p><strong>{item.eventName}</strong> · Game {item.matchInstance} · {item.sideA.displayName} / {item.sideB.displayName}</p><fieldset disabled={!!locked}><label>Rulebook disposition<select value={ruleCase} onChange={e=>setRuleCase(e.target.value as keyof typeof ruleLabels)}>{Object.entries(ruleLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><ClaimEditor name={item.sideA.displayName} claim={a} setClaim={setA}/><ClaimEditor name={item.sideB.displayName} claim={b} setClaim={setB}/><label><input type="checkbox" checked={qualificationChanged} onChange={e=>setQualificationChanged(e.target.checked)}/> This correction changes who qualifies or their qualifying position</label>{qualificationChanged?<label>Affected player<select value={affectedParticipantId} onChange={e=>setAffectedParticipantId(e.target.value)}>{targets.map(t=><option key={t.participantId} value={t.participantId}>{t.displayName}</option>)}</select></label>:null}<label>Reason (optional unless required by tournament policy)<textarea maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label></fieldset><button className="primary full" type="button" disabled={busy||(qualificationChanged&&!affectedParticipantId)} onClick={save}>{busy?"Checking…":locked?"Retry exact saved correction":"Review and save correction"}</button>{message?<p role="status">{message}</p>:null}</li>;
}

function Review({actorId,item}:{actorId:string;item:PendingCorrectionReview}){const router=useRouter(),key=`acc-correction:review:${actorId}:${item.correctionId}`;const[busy,setBusy]=useState(true),[locked,setLocked]=useState<SavedReview|null>(null),[message,setMessage]=useState("");useEffect(()=>{void(async()=>{const p=stored<SavedReview>(key);if(!p){setBusy(false);return}try{const r=await fetch(`/api/v1/corrections/${item.correctionId}/reconciliation`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({idempotencyKey:p.idempotencyKey})});const result=r.ok?await r.json():null;if(result?.state==="resolved"){sessionStorage.removeItem(key);router.refresh();return}}catch{}setLocked(p);setMessage("The prior review is unresolved. Retry sends the exact saved decision.");setBusy(false)})()},[item.correctionId,key,router]);async function decide(decision:"approve"|"reject"){const payload=locked??{decision,idempotencyKey:crypto.randomUUID()};sessionStorage.setItem(key,JSON.stringify(payload));setLocked(payload);setBusy(true);try{const response=await fetch(`/api/v1/corrections/${item.correctionId}/reviews`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!response.ok){if(response.status<500){sessionStorage.removeItem(key);setLocked(null)}setMessage("This review was not accepted. Refresh, or retry the exact saved decision.");return}sessionStorage.removeItem(key);setLocked(null);setMessage(payload.decision==="approve"?"Correction approved and applied.":"Correction rejected; original scorecard values remain authoritative.");router.refresh()}catch{setMessage("Network issue. Retry sends the exact saved decision.")}finally{setBusy(false)}}const line=(label:string,side:PendingCorrectionReview["sideA"])=><p><strong>{label}: {side.displayName}</strong> · original {side.original.outcome}, {side.original.margin??"blank"} in {side.original.column} column{side.original.apparentQualifier?" · apparent qualifier":""} → adjudicated {side.adjudicated.isWinner?"win":"loss"} by {side.adjudicated.margin}</p>;return <li className="correction-item"><p><strong>{item.eventName}</strong> · Game {item.matchInstance} · Rule {item.ruleCase}</p>{line("Card A",item.sideA)}{line("Card B",item.sideB)}{item.reason?<p>Reason: {item.reason}</p>:null}{item.qualificationChanged?<p><strong>Approval will queue a qualification-position notice for {item.affectedNoticeTarget?.displayName??"the recorded affected player"}.</strong></p>:null}<button className="primary" disabled={busy||locked?.decision==="reject"} onClick={()=>decide("approve")}>Approve correction</button><button className="secondary" disabled={busy||locked?.decision==="approve"} onClick={()=>decide("reject")}>Reject correction</button>{message?<p role="status">{message}</p>:null}</li>}

export default function CorrectionsClient({actorId,proposalCandidates,noticeTargets,pendingReviews}:{actorId:string;proposalCandidates:CorrectionProposalCandidate[];noticeTargets:CorrectionNoticeTarget[];pendingReviews:PendingCorrectionReview[]}){return <><h2>Corrections you may record</h2>{proposalCandidates.length?<ul className="correction-list">{proposalCandidates.map(i=><Proposal actorId={actorId} item={i} noticeTargets={noticeTargets} key={i.gameId}/>)}</ul>:<p>No eligible scorecards need a correction.</p>}<h2>Independent approvals waiting for you</h2>{pendingReviews.length?<ul className="correction-list">{pendingReviews.map(i=><Review actorId={actorId} item={i} key={i.correctionId}/>)}</ul>:<p>No correction approvals are waiting.</p>}</>}
