"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import type { CorrectionProposalCandidate, PendingCorrectionReview } from "../../../../lib/corrections/types";
import { clearOtherCorrectionActors, proposalOperationKey, reviewOperationKey } from "../../../../lib/corrections/operation-envelope";

type Status = { text: string; kind: "error" | "success" } | null;
type ProposalEnvelope = { kind: "proposal"; digest: string; correctionId: string; idempotencyKey: string; expectedGameVersion: number; winnerSide: "a" | "b"; margin: number };
type ReviewEnvelope = { kind: "review"; digest: string; idempotencyKey: string; decision: "approve" | "reject" };
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function nameFor(side: "a" | "b", item: { sideA: { displayName: string }; sideB: { displayName: string } }) { return side === "a" ? item.sideA.displayName : item.sideB.displayName; }
function readableFailure(status: number, payload: unknown) {
  if (status === 401) return "Sign in again before making a correction.";
  if (status === 400) return "Check the proposed result and try again.";
  const code = payload && typeof payload === "object" ? (payload as Record<string, unknown>).code : undefined;
  if (code === "reason_required") return "The director requires a reason for this correction.";
  if (code === "stale_game_version" || code === "not_pending_review") return "This item changed. Refresh the correction list before trying again.";
  if (code === "not_authorized" || code === "reviewer_not_independent") return "The tournament server does not authorize this action for your account.";
  return "This action was not accepted. Refresh the correction list before trying again.";
}
function parseEnvelope<T>(value: string | null, valid: (item: unknown) => item is T): T | null { if (!value) return null; try { const parsed: unknown = JSON.parse(value); return valid(parsed) ? parsed : null; } catch { return null; } }
function isProposalEnvelope(value: unknown): value is ProposalEnvelope { if (!value || typeof value !== "object") return false; const item = value as Record<string, unknown>; return item.kind === "proposal" && typeof item.digest === "string" && uuid.test(item.correctionId as string) && uuid.test(item.idempotencyKey as string) && Number.isSafeInteger(item.expectedGameVersion) && (item.winnerSide === "a" || item.winnerSide === "b") && Number.isInteger(item.margin); }
function isReviewEnvelope(value: unknown): value is ReviewEnvelope { if (!value || typeof value !== "object") return false; const item = value as Record<string, unknown>; return item.kind === "review" && typeof item.digest === "string" && uuid.test(item.idempotencyKey as string) && (item.decision === "approve" || item.decision === "reject"); }
async function digest(payload: unknown) { const bytes = new TextEncoder().encode(JSON.stringify(payload)); const hash = await crypto.subtle.digest("SHA-256", bytes); return Array.from(new Uint8Array(hash), (byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function reconciliation(correctionId: string, idempotencyKey: string) { try { const response = await fetch(`/api/v1/corrections/${encodeURIComponent(correctionId)}/reconciliation`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idempotencyKey }) }); const payload: unknown = await response.json().catch(() => null); return response.ok && !!payload && typeof payload === "object" && (payload as Record<string, unknown>).state === "resolved"; } catch { return false; } }

function CorrectionProposal({ actorId, item }: { actorId: string; item: CorrectionProposalCandidate }) {
  const router = useRouter(); const storageKey = proposalOperationKey(actorId, item.gameId);
  const [winnerSide, setWinnerSide] = useState<"a" | "b">(item.winnerSide); const [margin, setMargin] = useState(String(item.margin)); const [reason, setReason] = useState(""); const [locked, setLocked] = useState<ProposalEnvelope | null>(null); const [hydrated, setHydrated] = useState(false); const [busy, setBusy] = useState(false); const [status, setStatus] = useState<Status>(null);
  useEffect(() => { const timer = window.setTimeout(async () => { const existing = parseEnvelope(window.sessionStorage.getItem(storageKey), isProposalEnvelope); if (existing) { if (existing.expectedGameVersion !== item.gameVersion || await reconciliation(existing.correctionId, existing.idempotencyKey)) { window.sessionStorage.removeItem(storageKey); router.refresh(); return; } setWinnerSide(existing.winnerSide); setMargin(String(existing.margin)); setLocked(existing); setStatus({ text: "A previous correction request is awaiting a safe retry. Re-enter its original reason exactly, then retry; the result itself is locked.", kind: "error" }); } setHydrated(true); }); return () => window.clearTimeout(timer); }, [storageKey, item.gameVersion, router]);
  const formId = `correction-${item.gameId}`; const numericMargin = Number(margin); const changed = winnerSide !== item.winnerSide || numericMargin !== item.margin; const valid = Number.isInteger(numericMargin) && numericMargin >= 1 && numericMargin <= 121 && changed;
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!valid || busy) return; const canonical = [item.gameId, item.gameVersion, winnerSide, numericMargin, reason]; const operationDigest = await digest(canonical); let envelope = locked;
    if (envelope && envelope.digest !== operationDigest) { setStatus({ text: "A previous correction request is awaiting a safe retry. Refresh before changing this result.", kind: "error" }); return; }
    if (!envelope) { envelope = { kind: "proposal", digest: operationDigest, correctionId: crypto.randomUUID(), idempotencyKey: crypto.randomUUID(), expectedGameVersion: item.gameVersion, winnerSide, margin: numericMargin }; window.sessionStorage.setItem(storageKey, JSON.stringify(envelope)); }
    setBusy(true); setStatus(null);
    try {
      const response = await fetch(`/api/v1/games/${encodeURIComponent(item.gameId)}/corrections`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ correctionId: envelope.correctionId, expectedGameVersion: item.gameVersion, winnerSide: envelope.winnerSide, margin: envelope.margin, reason: reason || undefined, idempotencyKey: envelope.idempotencyKey }) }); const payload: unknown = await response.json().catch(() => null);
      if (!response.ok) { if (response.status < 500) window.sessionStorage.removeItem(storageKey); else setLocked(envelope); setStatus({ text: readableFailure(response.status, payload), kind: "error" }); return; }
      if (!payload || typeof payload !== "object" || !["applied", "pending"].includes((payload as Record<string, unknown>).status as string)) { setLocked(envelope); setStatus({ text: "The server response was incomplete. Try again; this correction will safely retry with the same request ID.", kind: "error" }); return; }
      window.sessionStorage.removeItem(storageKey); const isPending = (payload as Record<string, unknown>).status === "pending"; setStatus({ text: isPending ? "Correction submitted for independent review. It does not affect scorecards, standings, or exports yet." : "Correction applied by the tournament server.", kind: "success" }); router.refresh();
    } catch { setLocked(envelope); setStatus({ text: "Network issue. Try again; this correction will safely retry with the same request ID.", kind: "error" }); } finally { setBusy(false); }
  }
  return <li className="correction-item"><p><strong>{item.eventName}</strong> · Game {item.matchInstance} · {item.sideA.displayName} / {item.sideB.displayName}</p><p className="auth-note">Recorded: {nameFor(item.winnerSide, item)} won by {item.margin}.</p><form id={formId} onSubmit={submit}><fieldset disabled={!hydrated || busy || !!locked}><legend>Corrected winner</legend><label><input type="radio" name={`${formId}-winner`} checked={winnerSide === "a"} onChange={() => setWinnerSide("a")} /> {item.sideA.displayName}</label><label><input type="radio" name={`${formId}-winner`} checked={winnerSide === "b"} onChange={() => setWinnerSide("b")} /> {item.sideB.displayName}</label></fieldset><label htmlFor={`${formId}-margin`}>Corrected spread points</label><input id={`${formId}-margin`} inputMode="numeric" pattern="[0-9]*" value={margin} maxLength={3} onChange={(event) => setMargin(event.target.value.replace(/\D/g, "").slice(0, 3))} disabled={!hydrated || busy || !!locked} aria-describedby={`${formId}-help`} /><p id={`${formId}-help`} className="auth-note">Enter a possible spread point number.</p><label htmlFor={`${formId}-reason`}>Reason (optional unless the director requires it)</label><textarea id={`${formId}-reason`} value={reason} onChange={(event) => setReason(event.target.value.slice(0, 500))} maxLength={500} disabled={!hydrated || busy} /><button className="primary full" type="submit" disabled={!hydrated || !valid || busy}>{busy ? "Saving correction…" : locked ? "Retry locked correction" : "Save correction"}</button></form>{status ? <p className={status.kind === "error" ? "error-text" : "success-text"} role={status.kind === "error" ? "alert" : "status"}>{status.text}</p> : null}</li>;
}

function PendingReview({ actorId, item }: { actorId: string; item: PendingCorrectionReview }) {
  const router = useRouter(); const storageKey = reviewOperationKey(actorId, item.correctionId); const [locked, setLocked] = useState<ReviewEnvelope | null>(null); const [hydrated, setHydrated] = useState(false); const [busy, setBusy] = useState(false); const [status, setStatus] = useState<Status>(null);
  useEffect(() => { const timer = window.setTimeout(async () => { const existing = parseEnvelope(window.sessionStorage.getItem(storageKey), isReviewEnvelope); if (existing) { if (await reconciliation(item.correctionId, existing.idempotencyKey)) { window.sessionStorage.removeItem(storageKey); router.refresh(); return; } setLocked(existing); setStatus({ text: "A previous review is awaiting a safe retry. Its decision is locked until it is retried or you refresh the list.", kind: "error" }); } setHydrated(true); }); return () => window.clearTimeout(timer); }, [storageKey, item.correctionId, router]);
  async function review(decision: "approve" | "reject") {
    if (busy) return; const operationDigest = await digest([item.correctionId, decision]); let envelope = locked; if (envelope && envelope.digest !== operationDigest) { setStatus({ text: "A previous review is awaiting a safe retry. Refresh before changing its decision.", kind: "error" }); return; }
    if (!envelope) { envelope = { kind: "review", digest: operationDigest, idempotencyKey: crypto.randomUUID(), decision }; window.sessionStorage.setItem(storageKey, JSON.stringify(envelope)); }
    setBusy(true); setStatus(null);
    try {
      const response = await fetch(`/api/v1/corrections/${encodeURIComponent(item.correctionId)}/reviews`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision: envelope.decision, idempotencyKey: envelope.idempotencyKey }) }); const payload: unknown = await response.json().catch(() => null);
      if (!response.ok) { if (response.status < 500) window.sessionStorage.removeItem(storageKey); else setLocked(envelope); setStatus({ text: readableFailure(response.status, payload), kind: "error" }); return; }
      if (!payload || typeof payload !== "object" || (payload as Record<string, unknown>).decision !== envelope.decision || !["approved", "rejected"].includes((payload as Record<string, unknown>).status as string)) { setLocked(envelope); setStatus({ text: "The server response was incomplete. Try again; this review will safely retry with the same request ID.", kind: "error" }); return; }
      window.sessionStorage.removeItem(storageKey); setStatus({ text: envelope.decision === "approve" ? "Correction approved by the tournament server." : "Correction rejected by the tournament server.", kind: "success" }); router.refresh();
    } catch { setLocked(envelope); setStatus({ text: "Network issue. Try again; this review will safely retry with the same request ID.", kind: "error" }); } finally { setBusy(false); }
  }
  const fixedDecision = locked?.decision;
  return <li className="correction-item"><p><strong>{item.eventName}</strong> · Game {item.matchInstance}</p><p>Recorded: {nameFor(item.previousWinnerSide, item)} won by {item.previousMargin}. Proposed: {nameFor(item.correctedWinnerSide, item)} won by {item.correctedMargin}.</p>{item.reason ? <p className="auth-note">Reason: {item.reason}</p> : <p className="auth-note">No reason was provided.</p>}<div className="correction-actions"><button type="button" className="primary" onClick={() => review("approve")} disabled={!hydrated || busy || (!!fixedDecision && fixedDecision !== "approve")}>{busy && fixedDecision === "approve" ? "Approving…" : fixedDecision === "approve" ? "Retry approval" : "Approve correction"}</button><button type="button" className="secondary" onClick={() => review("reject")} disabled={!hydrated || busy || (!!fixedDecision && fixedDecision !== "reject")}>{busy && fixedDecision === "reject" ? "Rejecting…" : fixedDecision === "reject" ? "Retry rejection" : "Reject correction"}</button></div>{status ? <p className={status.kind === "error" ? "error-text" : "success-text"} role={status.kind === "error" ? "alert" : "status"}>{status.text}</p> : null}</li>;
}

export default function CorrectionsClient({ actorId, proposalCandidates, pendingReviews }: { actorId: string; proposalCandidates: CorrectionProposalCandidate[]; pendingReviews: PendingCorrectionReview[] }) {
  useEffect(() => { clearOtherCorrectionActors(window.sessionStorage, actorId); }, [actorId]);
  return <><h2>Corrections you may propose</h2>{proposalCandidates.length ? <ul className="correction-list">{proposalCandidates.map((item) => <CorrectionProposal actorId={actorId} key={item.gameId} item={item} />)}</ul> : <p className="auth-note">No correction proposals are available to you.</p>}<h2>Independent reviews waiting for you</h2>{pendingReviews.length ? <ul className="correction-list">{pendingReviews.map((item) => <PendingReview actorId={actorId} key={item.correctionId} item={item} />)}</ul> : <p className="auth-note">No independent reviews are waiting for you.</p>}</>;
}
