import { NextRequest } from "next/server";
import { isInviteRequest, isManageRequest, isOfficialRejection } from "../../../../../../lib/api/officials";
import { apiJson, readSmallJson, requireVerifiedSubject, withApiFailureBoundary } from "../../../../../../lib/api/route-boundary";
import { isSameOriginRequest } from "../../../../../../lib/api/same-origin";
import { isUuid } from "../../../../../../lib/api/validation";
import { getOfficialsWorkspace, inviteCoDirector, manageCoDirector } from "../../../../../../lib/officials";
import { createServerOnlyAdminClient } from "../../../../../../lib/supabase/private-admin";
import { createClient } from "../../../../../../lib/supabase/server";
export const dynamic = "force-dynamic";
export async function GET(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) { return withApiFailureBoundary(async () => { const { id } = await params; const actorId = await requireVerifiedSubject(await createClient()); if (!actorId) return apiJson({ error: "unauthorized" }, { status: 401 }); if (!isUuid(id)) return apiJson({ error: "invalid_request" }, { status: 400 }); const workspace = await getOfficialsWorkspace(createServerOnlyAdminClient(), actorId, id); return workspace ? apiJson(workspace) : apiJson({ error: "not_found" }, { status: 404 }); }); }
export async function POST(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { return withApiFailureBoundary(async () => { if (!isSameOriginRequest(request)) return apiJson({ error: "invalid_origin" }, { status: 403 }); const { id } = await params; const body = await readSmallJson(request); const actorId = await requireVerifiedSubject(await createClient()); if (!actorId) return apiJson({ error: "unauthorized" }, { status: 401 }); if (!isUuid(id)) return apiJson({ error: "invalid_request" }, { status: 400 }); if (isInviteRequest(body)) { const secret = crypto.randomUUID() + crypto.randomUUID(); const result = await inviteCoDirector(createServerOnlyAdminClient(), { actorId, tournamentId: id, email: body.email, secret, operationId: body.operationId }) as Record<string, unknown>; return isOfficialRejection(result) ? apiJson({ error: result.code }, { status: 409 }) : apiJson({ ...result, acceptanceUrl: `/official-invitations/${encodeURIComponent(secret)}` }); } if (isManageRequest(body)) { const result = await manageCoDirector(createServerOnlyAdminClient(), { actorId, tournamentId: id, ...body }) as Record<string, unknown>; return isOfficialRejection(result) ? apiJson({ error: result.code }, { status: 409 }) : apiJson(result); } return apiJson({ error: "invalid_request" }, { status: 400 }); }); }
