"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { isRejectedSidePool, isSidePoolMutation, isSidePoolMutationResult, type SidePool, type SidePoolMutation, type SidePoolWorkspace } from "../../../../lib/api/side-pools";
const categories = ["10", "20", "50", "100"] as const;
const money = (minor: number) => `$${(minor / 100).toFixed(2)}`;
const cents = (value: string) => Math.round(Number(value || 0) * 100);
const errors: Record<string, string> = { policy_must_be_posted_before_play: "Post the payout ratio and schedule before starting play.", received_exceeds_due: "Received cannot exceed the election fee.", removed_election_requires_zero: "Refund or correct the received amount to zero before removing this election.", winner_not_elected: "A payout recipient must be an active pool participant.", payout_exceeds_collected: "Payouts cannot exceed funds collected.", unpaid_elections: "Every active election must be fully paid before finalization.", unreconciled: "Collected funds and payouts do not reconcile to exactly zero.", placement_exists: "That placement already has an active payout." };
export default function SidePoolsClient({ tournamentId, workspace }: { tournamentId: string; workspace: SidePoolWorkspace }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function mutate(request: SidePoolMutation) { if (!isSidePoolMutation(request) || busy) return; setBusy(true); setMessage(""); try { const response = await fetch(`/api/v1/tournaments/${tournamentId}/side-pools`, { method: "POST", headers: { "content-type": "application/json" }, credentials: "same-origin", body: JSON.stringify(request) }); const data: unknown = await response.json().catch(() => null); if (response.ok && isSidePoolMutationResult(data, request)) { setMessage("Side Pool record saved and audited."); router.refresh(); } else if (isRejectedSidePool(data)) setMessage(errors[data.code] ?? `Side Pool request rejected: ${data.code.replaceAll("_", " ")}.`); else setMessage("The Side Pool request is unresolved. Refresh before retrying."); } catch { setMessage("The Side Pool request is unresolved. Refresh before retrying."); } finally { setBusy(false); } }
  async function add(eventId: string, categoryCode: typeof categories[number]) { await mutate({ action: "add_pool", eventId, poolId: crypto.randomUUID(), categoryCode, displayName: `$${categoryCode} Side Pool`, entryFeeMinor: Number(categoryCode) * 100, idempotencyKey: crypto.randomUUID() }); }
  return <section className="policy-settings">{workspace.events.map((event) => <section className="correction-item" key={event.eventId}><h2>{event.name}</h2>{event.pools.length ? event.pools.map((pool) => <PoolOperations key={pool.poolId} eventId={event.eventId} pool={pool} participants={event.participants} busy={busy} mutate={mutate}/>) : <p>No Side Pools configured.</p>}<div className="setup-actions">{categories.filter((category) => !event.pools.some((pool) => pool.categoryCode === category)).map((category) => <button className="secondary" type="button" disabled={busy || event.pools.length >= 4} key={category} onClick={() => void add(event.eventId, category)}>Add ${category} Side Pool</button>)}</div></section>)}<p className="live-status" role="status">{message}</p></section>;
}
function PoolOperations({ eventId, pool, participants, busy, mutate }: { eventId: string; pool: SidePool; participants: Array<{ participantId: string; displayName: string }>; busy: boolean; mutate: (request: SidePoolMutation) => Promise<void> }) {
  const [ratio, setRatio] = useState("5"); const [schedule, setSchedule] = useState("1:0"); const [participantId, setParticipantId] = useState(participants[0]?.participantId ?? ""); const [received, setReceived] = useState((pool.entryFeeMinor / 100).toFixed(2)); const [method, setMethod] = useState<"cash" | "check">("cash"); const [reference, setReference] = useState(""); const [placement, setPlacement] = useState("1"); const [payout, setPayout] = useState("");
  const currentElection = pool.elections.find((item) => item.participantId === participantId); const proposed = schedule.split(",").map((row) => row.trim().split(":")); const payoutSchedule = proposed.map(([place, amount]) => ({ placement: Number(place), amountMinor: cents(amount ?? "0") })).filter((item) => Number.isSafeInteger(item.placement) && item.placement > 0 && Number.isSafeInteger(item.amountMinor) && item.amountMinor >= 0);
  const suggestedWinners = Math.max(1, Math.floor(pool.elections.filter((item) => item.elected).length / Number(ratio || 5))); const suggestedShare = suggestedWinners ? Math.floor(pool.collectedMinor / suggestedWinners) : 0;
  return <section className="registration-note"><h3>{pool.displayName} · {money(pool.entryFeeMinor)}</h3><p><strong>Collected {money(pool.collectedMinor)} · Payouts {money(pool.paidMinor)} · Remaining {money(pool.collectedMinor - pool.paidMinor)}</strong></p>{pool.finalized ? <p className="success-text">Finalized and reconciled.</p> : <>
    <fieldset disabled={busy || !!pool.policy}><legend>Post payout policy before play</legend><label>Pay approximately 1 in <input inputMode="numeric" value={ratio} onChange={(e) => setRatio(e.target.value)}/></label><label>Posted payout schedule <input value={schedule} onChange={(e) => setSchedule(e.target.value)} placeholder="1:50,2:30,3:20"/></label><p className="auth-note">Calculator estimate: {suggestedWinners} winner{suggestedWinners === 1 ? "" : "s"}, about {money(suggestedShare)} each. Edit the posted schedule before saving.</p><button className="secondary" type="button" disabled={busy || !!pool.policy || payoutSchedule.length === 0} onClick={() => void mutate({ action: "configure_policy", eventId, poolId: pool.poolId, payoutRatioDenominator: Number(ratio), postedPayoutSchedule: payoutSchedule, reason: "Director posted the payout ratio and schedule before play", idempotencyKey: crypto.randomUUID() })}>Post Payout Schedule</button></fieldset>
    {pool.policy ? <p>Payout ratio: 1 in {pool.policy.payoutRatioDenominator}. Posted schedule: {pool.policy.postedPayoutSchedule.map((item) => `${item.placement}: ${money(item.amountMinor)}`).join(" · ")}</p> : null}
    <fieldset disabled={busy || !participantId}><legend>Participant election and payment</legend><label>Participant<select value={participantId} onChange={(e) => setParticipantId(e.target.value)}>{participants.map((item) => <option key={item.participantId} value={item.participantId}>{item.displayName}</option>)}</select></label><label>Amount received<input inputMode="decimal" value={received} onChange={(e) => setReceived(e.target.value)}/></label><label>Method<select value={method} onChange={(e) => setMethod(e.target.value as "cash" | "check")}><option value="cash">Cash</option><option value="check">Check</option></select></label><label>Check number or reference (optional)<input maxLength={100} value={reference} onChange={(e) => setReference(e.target.value)}/></label><div className="setup-actions"><button className="secondary" type="button" onClick={() => void mutate({ action: "set_election", eventId, poolId: pool.poolId, participantId, electionId: currentElection?.electionId ?? crypto.randomUUID(), elected: true, amountReceivedMinor: cents(received), paymentMethod: method, paymentReference: reference, reason: currentElection ? "Director corrected Side Pool election or payment" : "Director recorded Side Pool election", idempotencyKey: crypto.randomUUID() })}>Save Election</button>{currentElection?.elected ? <button className="secondary" type="button" onClick={() => void mutate({ action: "set_election", eventId, poolId: pool.poolId, participantId, electionId: currentElection.electionId, elected: false, amountReceivedMinor: 0, paymentMethod: method, paymentReference: reference, reason: "Director removed or voided Side Pool election", idempotencyKey: crypto.randomUUID() })}>Remove / Void Election</button> : null}</div></fieldset>
    <ul>{pool.elections.filter((item) => item.elected).map((item) => <li key={item.electionId}>{item.displayName} · due {money(item.amountDueMinor)} · received {money(item.amountReceivedMinor)} · remaining {money(item.amountRemainingMinor)} · {item.paymentMethod ?? "method not recorded"}{item.paymentReference ? ` ${item.paymentReference}` : ""}</li>)}</ul>
    <fieldset disabled={busy || !pool.policy || !participantId}><legend>Cross-checked payout</legend><label>Placement<input inputMode="numeric" value={placement} onChange={(e) => setPlacement(e.target.value)}/></label><label>Payout amount<input inputMode="decimal" value={payout} onChange={(e) => setPayout(e.target.value)}/></label><button className="secondary" type="button" onClick={() => void mutate({ action: "set_payout", eventId, poolId: pool.poolId, participantId, payoutId: crypto.randomUUID(), placement: Number(placement), amountMinor: cents(payout), voided: false, reason: "Director recorded payout after cross-checking", idempotencyKey: crypto.randomUUID() })}>Record Payout</button></fieldset>
    <ol>{pool.payouts.map((item) => <li key={item.payoutId}>{item.displayName} · place {item.placement} · {money(item.amountMinor)} <button className="secondary" type="button" disabled={busy} onClick={() => void mutate({ action: "set_payout", eventId, poolId: pool.poolId, participantId: item.participantId, payoutId: item.payoutId, placement: item.placement, amountMinor: item.amountMinor, voided: true, reason: "Director voided payout", idempotencyKey: crypto.randomUUID() })}>Void</button></li>)}</ol>
    <button className="primary" type="button" disabled={busy || !pool.policy || pool.collectedMinor !== pool.paidMinor} onClick={() => void mutate({ action: "finalize", eventId, poolId: pool.poolId, reconciliationId: crypto.randomUUID(), idempotencyKey: crypto.randomUUID() })}>Finalize Reconciled Side Pool</button></>}</section>;
}
