"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { isRejectedSidePool, isSidePoolMutation, isSidePoolMutationResult, type SidePool, type SidePoolMutation, type SidePoolTeamBeneficiary, type SidePoolWorkspace } from "../../../../lib/api/side-pools";
const presetCodes = ["10", "20", "50", "100"] as const;
const presets = [{ code: presetCodes[0], name: "$10 Side Pool", fee: 1000 }, { code: presetCodes[1], name: "$20 Side Pool", fee: 2000 }, { code: presetCodes[2], name: "$50 Side Pool", fee: 5000 }, { code: presetCodes[3], name: "$100 Side Pool", fee: 10000 }] as const;
const money = (minor: number) => `$${(minor / 100).toFixed(2)}`;
const cents = (value: string) => Math.round(Number(value || 0) * 100);
const errors: Record<string, string> = { policy_must_be_posted_before_play: "Post the payout ratio and schedule before starting play.", received_exceeds_due: "Received cannot exceed the election fee.", removed_election_requires_zero: "Refund or correct the received amount to zero before removing this election.", winner_not_elected: "A payout recipient must be an active pool participant.", payout_exceeds_collected: "Payouts cannot exceed funds collected.", unpaid_elections: "Every active election must be fully paid before finalization.", unreconciled: "Collected funds and payouts do not reconcile to exactly zero.", placement_exists: "That placement already has an active payout." };
export default function SidePoolsClient({ tournamentId, workspace }: { tournamentId: string; workspace: SidePoolWorkspace }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function mutate(request: SidePoolMutation) { if (!isSidePoolMutation(request) || busy) return; setBusy(true); setMessage(""); try { const response = await fetch(`/api/v1/tournaments/${tournamentId}/side-pools`, { method: "POST", headers: { "content-type": "application/json" }, credentials: "same-origin", body: JSON.stringify(request) }); const data: unknown = await response.json().catch(() => null); if (response.ok && isSidePoolMutationResult(data, request)) { setMessage("Side Pool record saved and audited."); router.refresh(); } else if (isRejectedSidePool(data)) setMessage(errors[data.code] ?? `Side Pool request rejected: ${data.code.replaceAll("_", " ")}.`); else setMessage("The Side Pool request is unresolved. Refresh before retrying."); } catch { setMessage("The Side Pool request is unresolved. Refresh before retrying."); } finally { setBusy(false); } }
  async function add(eventId: string, name: string, fee: number) { await mutate({ action: "add_pool", eventId, poolId: crypto.randomUUID(), categoryCode: name, displayName: name, entryFeeMinor: fee, idempotencyKey: crypto.randomUUID() }); }
  async function addCustom(eventId: string, name: string, fee: string) { const trimmed = name.trim(); const amount = cents(fee); if (!trimmed || !Number.isSafeInteger(amount) || amount < 0) return; await add(eventId, trimmed, amount); }
  return <section className="policy-settings">{workspace.events.map((event) => <section className="correction-item" key={event.eventId}><h2>{event.name}</h2>{event.pools.length ? event.pools.map((pool) => <div key={pool.poolId}><PoolOperations eventId={event.eventId} pool={pool} participants={event.participants} busy={busy} mutate={mutate}/>{event.teamBeneficiaries.length ? <TeamPoolOperations eventId={event.eventId} pool={pool} teams={event.teamBeneficiaries} busy={busy} mutate={mutate}/> : null}</div>) : <p>No Side Pools configured.</p>}{event.pools.length < 6 ? <PoolAdder eventId={event.eventId} busy={busy} add={add} addCustom={addCustom}/> : <p>Maximum of six active Side Pools reached.</p>}</section>)}<p className="live-status" role="status">{message}</p></section>;
}
function PoolAdder({ eventId, busy, add, addCustom }: { eventId: string; busy: boolean; add: (eventId: string, name: string, fee: number) => Promise<void>; addCustom: (eventId: string, name: string, fee: string) => Promise<void> }) {
  const [name, setName] = useState(""); const [fee, setFee] = useState("");
  return <section className="setup-actions"><span>Quick add:</span>{presets.map((preset) => <button className="secondary" type="button" disabled={busy} key={preset.fee} onClick={() => void add(eventId, preset.name, preset.fee)}>{preset.name}</button>)}<label>Pool name<input value={name} maxLength={100} onChange={(e) => setName(e.target.value)} /></label><label>Entry fee<input inputMode="decimal" value={fee} onChange={(e) => setFee(e.target.value)} placeholder="25.00" /></label><button className="secondary" type="button" disabled={busy || !name.trim() || !fee} onClick={() => void addCustom(eventId, name, fee)}>Add Custom Side Pool</button></section>;
}
function PoolOperations({ eventId, pool, participants, busy, mutate }: { eventId: string; pool: SidePool; participants: Array<{ participantId: string; displayName: string }>; busy: boolean; mutate: (request: SidePoolMutation) => Promise<void> }) {
  const [ratio, setRatio] = useState("5"); const [schedule, setSchedule] = useState("1:0"); const [participantId, setParticipantId] = useState(participants[0]?.participantId ?? ""); const [received, setReceived] = useState((pool.entryFeeMinor / 100).toFixed(2)); const [method, setMethod] = useState<"cash" | "check">("cash"); const [reference, setReference] = useState(""); const [placement, setPlacement] = useState("1"); const [payout, setPayout] = useState("");
  const currentElection = pool.elections.find((item) => item.participantId === participantId); const proposed = schedule.split(",").map((row) => row.trim().split(":")); const payoutSchedule = proposed.map(([place, amount]) => ({ placement: Number(place), amountMinor: cents(amount ?? "0") })).filter((item) => Number.isSafeInteger(item.placement) && item.placement > 0 && Number.isSafeInteger(item.amountMinor) && item.amountMinor >= 0);
  const suggestedWinners = Math.max(1, Math.floor(pool.elections.filter((item) => item.elected).length / Number(ratio || 5))); const suggestedShare = suggestedWinners ? Math.floor(pool.collectedMinor / suggestedWinners) : 0;
  return <section className="registration-note"><h3>{pool.displayName} · {money(pool.entryFeeMinor)}</h3><p><strong>Collected {money(pool.collectedMinor)} · Payouts {money(pool.paidMinor)} · Remaining {money(pool.collectedMinor - pool.paidMinor)}</strong></p>{pool.finalized ? <p className="success-text">Finalized and reconciled.</p> : <>
    <fieldset disabled={busy || !!pool.policy}><legend>Post payout policy before play</legend><label>Pay approximately 1 in <input inputMode="numeric" value={ratio} onChange={(e) => setRatio(e.target.value)}/></label><label>Posted payout schedule <input value={schedule} onChange={(e) => setSchedule(e.target.value)} placeholder="1:50,2:30,3:20"/></label><p className="auth-note">Calculator estimate: {suggestedWinners} winner{suggestedWinners === 1 ? "" : "s"}, about {money(suggestedShare)} each. Edit the posted schedule before saving.</p><button className="secondary" type="button" disabled={busy || !!pool.policy || payoutSchedule.length === 0} onClick={() => void mutate({ action: "configure_policy", eventId, poolId: pool.poolId, payoutRatioDenominator: Number(ratio), postedPayoutSchedule: payoutSchedule, reason: "Director posted the payout ratio and schedule before play", idempotencyKey: crypto.randomUUID() })}>Post Payout Schedule</button></fieldset>
    {pool.policy ? <p>Payout ratio: 1 in {pool.policy.payoutRatioDenominator}. Posted schedule: {pool.policy.postedPayoutSchedule.map((item) => `${item.placement}: ${money(item.amountMinor)}`).join(" · ")}</p> : null}
    <fieldset disabled={busy || !participantId}><legend>Participant election and payment</legend><label>Participant<select value={participantId} onChange={(e) => setParticipantId(e.target.value)}>{participants.map((item) => <option key={item.participantId} value={item.participantId}>{item.displayName}</option>)}</select></label><label>Amount received<input inputMode="decimal" value={received} onChange={(e) => setReceived(e.target.value)}/></label><label>Method<select value={method} onChange={(e) => setMethod(e.target.value as "cash" | "check")}><option value="cash">Cash</option><option value="check">Check</option></select></label><label>Check number or reference (optional)<input maxLength={100} value={reference} onChange={(e) => setReference(e.target.value)}/></label><div className="setup-actions"><button className="secondary" type="button" onClick={() => void mutate({ action: "set_election", eventId, poolId: pool.poolId, participantId, electionId: currentElection?.electionId ?? crypto.randomUUID(), elected: true, amountReceivedMinor: cents(received), paymentMethod: method, paymentReference: reference, reason: currentElection ? "Director corrected Side Pool election or payment" : "Director recorded Side Pool election", idempotencyKey: crypto.randomUUID() })}>Save Election</button>{currentElection?.elected ? <button className="secondary" type="button" onClick={() => void mutate({ action: "set_election", eventId, poolId: pool.poolId, participantId, electionId: currentElection.electionId, elected: false, amountReceivedMinor: 0, paymentMethod: method, paymentReference: reference, reason: "Director removed or voided Side Pool election", idempotencyKey: crypto.randomUUID() })}>Remove / Void Election</button> : null}</div></fieldset>
    <ul>{pool.elections.filter((item) => item.elected).map((item) => <li key={item.electionId}>{item.displayName} · due {money(item.amountDueMinor)} · received {money(item.amountReceivedMinor)} · remaining {money(item.amountRemainingMinor)} · {item.paymentMethod ?? "method not recorded"}{item.paymentReference ? ` ${item.paymentReference}` : ""}</li>)}</ul>
    <fieldset disabled={busy || !pool.policy || !participantId}><legend>Cross-checked payout</legend><label>Placement<input inputMode="numeric" value={placement} onChange={(e) => setPlacement(e.target.value)}/></label><label>Payout amount<input inputMode="decimal" value={payout} onChange={(e) => setPayout(e.target.value)}/></label><button className="secondary" type="button" onClick={() => void mutate({ action: "set_payout", eventId, poolId: pool.poolId, participantId, payoutId: crypto.randomUUID(), placement: Number(placement), amountMinor: cents(payout), voided: false, reason: "Director recorded payout after cross-checking", idempotencyKey: crypto.randomUUID() })}>Record Payout</button></fieldset>
    <ol>{pool.payouts.map((item) => <li key={item.payoutId}>{item.displayName} · place {item.placement} · {money(item.amountMinor)} <button className="secondary" type="button" disabled={busy} onClick={() => void mutate({ action: "set_payout", eventId, poolId: pool.poolId, participantId: item.participantId, payoutId: item.payoutId, placement: item.placement, amountMinor: item.amountMinor, voided: true, reason: "Director voided payout", idempotencyKey: crypto.randomUUID() })}>Void</button></li>)}</ol>
    <button className="primary" type="button" disabled={busy || !pool.policy || pool.collectedMinor !== pool.paidMinor} onClick={() => void mutate({ action: "finalize", eventId, poolId: pool.poolId, reconciliationId: crypto.randomUUID(), idempotencyKey: crypto.randomUUID() })}>Finalize Reconciled Side Pool</button></>}</section>;
}

function TeamPoolOperations({eventId,pool,teams,busy,mutate}:{eventId:string;pool:SidePool;teams:SidePoolTeamBeneficiary[];busy:boolean;mutate:(request:SidePoolMutation)=>Promise<void>}) {
  const [teamEntryId,setTeamEntryId]=useState(teams[0]?.teamEntryId??"");
  const [received,setReceived]=useState((pool.entryFeeMinor/100).toFixed(2));
  const [method,setMethod]=useState<"cash"|"check">("cash");
  const [reference,setReference]=useState("");
  const [placement,setPlacement]=useState("1");
  const [payout,setPayout]=useState("");
  const team=teams.find((item)=>item.teamEntryId===teamEntryId);
  const election=team?.elections.find((item)=>item.poolId===pool.poolId);
  const payouts=teams.flatMap((item)=>item.payouts.filter((entry)=>entry.poolId===pool.poolId).map((entry)=>({...entry,displayName:item.displayName,teamEntryId:item.teamEntryId})));
  return <section className="registration-note"><h4>Team entries · {pool.displayName}</h4><fieldset disabled={busy||!teamEntryId||pool.finalized}><legend>Team election and payment</legend><label>Team<select value={teamEntryId} onChange={(event)=>setTeamEntryId(event.target.value)}>{teams.map((item)=><option key={item.teamEntryId} value={item.teamEntryId}>{item.displayName}</option>)}</select></label><label>Amount received<input inputMode="decimal" value={received} onChange={(event)=>setReceived(event.target.value)}/></label><label>Method<select value={method} onChange={(event)=>setMethod(event.target.value as "cash"|"check")}><option value="cash">Cash</option><option value="check">Check</option></select></label><label>Check number or reference (optional)<input maxLength={100} value={reference} onChange={(event)=>setReference(event.target.value)}/></label><div className="actions"><button className="secondary" type="button" onClick={()=>void mutate({action:"set_team_election",eventId,poolId:pool.poolId,teamEntryId,electionId:election?.electionId??crypto.randomUUID(),elected:true,amountReceivedMinor:cents(received),paymentMethod:method,paymentReference:reference,reason:election?"Director corrected team Side Pool election or payment":"Director recorded team Side Pool election",idempotencyKey:crypto.randomUUID()})}>Save Team Election</button>{election?.elected?<button className="secondary" type="button" onClick={()=>void mutate({action:"set_team_election",eventId,poolId:pool.poolId,teamEntryId,electionId:election.electionId,elected:false,amountReceivedMinor:0,paymentMethod:method,paymentReference:reference,reason:"Director removed or voided team Side Pool election",idempotencyKey:crypto.randomUUID()})}>Remove / Void Team Election</button>:null}</div></fieldset>
  <ul>{teams.flatMap((item)=>item.elections.filter((entry)=>entry.poolId===pool.poolId&&entry.elected).map((entry)=><li key={entry.electionId}>{item.displayName} · due {money(entry.amountDueMinor)} · received {money(entry.amountReceivedMinor)} · remaining {money(entry.amountRemainingMinor)}</li>))}</ul>
  <fieldset disabled={busy||!pool.policy||!teamEntryId||pool.finalized}><legend>Cross-checked team payout</legend><label>Placement<input inputMode="numeric" value={placement} onChange={(event)=>setPlacement(event.target.value)}/></label><label>Payout amount<input inputMode="decimal" value={payout} onChange={(event)=>setPayout(event.target.value)}/></label><button className="secondary" type="button" onClick={()=>void mutate({action:"set_team_payout",eventId,poolId:pool.poolId,teamEntryId,payoutId:crypto.randomUUID(),placement:Number(placement),amountMinor:cents(payout),voided:false,reason:"Director recorded team payout after cross-checking",idempotencyKey:crypto.randomUUID()})}>Record Team Payout</button></fieldset>
  <ol>{payouts.filter((item)=>!item.voided).map((item)=><li key={item.payoutId}>{item.displayName} · place {item.placement} · {money(item.amountMinor)} <button className="secondary" type="button" disabled={busy} onClick={()=>void mutate({action:"set_team_payout",eventId,poolId:pool.poolId,teamEntryId:item.teamEntryId,payoutId:item.payoutId,placement:item.placement,amountMinor:item.amountMinor,voided:true,reason:"Director voided team payout",idempotencyKey:crypto.randomUUID()})}>Void</button></li>)}</ol></section>;
}
