import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import { PDFDocument } from "pdf-lib";
import { isOperationalForfeitRequest, isScheduleAmendmentRequest } from "../src/lib/api/schedule-amendments.ts";
import { isSidePoolMutation } from "../src/lib/api/side-pools.ts";
import { isSatelliteSaveRequest } from "../src/lib/api/satellite-results.ts";
import { buildSatelliteResultsPdf } from "../src/lib/results/satellite-results-pdf.ts";
import { buildSidePoolDirectorCsv } from "../src/lib/results/side-pool-export.ts";
const read=(path)=>fs.readFileSync(path,"utf8");const id=(n)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;

test("schedule amendments preserve immutable before/after evidence and reject unsafe assignment changes",()=>{const sql=read("database/migrations/0169_late_player_schedule_amendments.sql");for(const token of ["event_schedule_amendment_versions","prior_schedule","proposed_schedule","unaffected_game_count","resolved_game_immutable","round_conflict","duplicate_opponent","final_game_requires_substitute","validated_schedule_amendment"])assert.match(sql,new RegExp(token));assert.match(sql,/mixed_rotation_repair/);assert.match(sql,/directorDecisionRequired/);assert.match(sql,/event_game_standings_eligibility_versions/);assert.match(sql,/current_effective_scorelines/);});

test("schedule amendment and forfeit API contracts are exact and bounded",()=>{const game={gameId:id(1),gameNumber:1,sideAParticipantId:id(2),sideBParticipantId:id(3),sideATableSeat:"A-1",sideBTableSeat:"A-2",standingsEligible:true,state:"pending"};const request={eventId:id(4),amendmentId:id(5),operationKind:"mixed_rotation_repair",ruleBasis:"ACC Director Manual: director decision",directorReason:"Correct the reviewed rotation",proposedSchedule:[game],expectedVersion:0,idempotencyKey:id(6)};assert.equal(isScheduleAmendmentRequest(request),true);assert.equal(isScheduleAmendmentRequest({...request,proposedSchedule:[{...game,sideBParticipantId:id(2)}]}),false);assert.equal(isOperationalForfeitRequest({eventId:id(4),gameId:id(1),forfeitId:id(7),winnerParticipantId:id(2),departingParticipantId:id(3),ruleCase:"early_departure_current_game",directorReason:"Player departed during current game",idempotencyKey:id(8)}),true);});

test("operational forfeits do not fabricate submissions and preserve the ACC 2/+10 rule",()=>{const sql=read("database/migrations/0169_late_player_schedule_amendments.sql");assert.match(sql,/game_points smallint not null default 2 check\(game_points=2\)/);assert.match(sql,/margin integer not null default 10 check\(margin=10\)/);assert.match(sql,/two-games-per-opponent/i);assert.doesNotMatch(sql,/insert into app\.score_submissions[\s\S]*operational_game_forfeits/);assert.match(sql,/playoff_absence_5/);assert.match(sql,/p_elapsed_minutes>=35 then 3 when p_elapsed_minutes>=20 then 2 else 1/);});

test("Side Pool operations enforce posted policy, event elections, immutable money history, and exact reconciliation",()=>{const sql=read("database/migrations/0170_operational_side_pools.sql");for(const token of ["event_side_pool_policy_versions","policy_must_be_posted_before_play","winner_not_elected","payout_exceeds_collected","unpaid_elections","event_side_pool_reconciliations","collected_minor=paid_minor\\+remaining_minor","remaining_minor=0"])assert.match(sql,new RegExp(token));for(const action of [
{action:"configure_policy",eventId:id(1),poolId:id(2),payoutRatioDenominator:5,postedPayoutSchedule:[{placement:1,amountMinor:1000}],reason:"Posted before play",idempotencyKey:id(3)},
{action:"set_election",eventId:id(1),poolId:id(2),participantId:id(4),electionId:id(5),elected:true,amountReceivedMinor:1000,paymentMethod:"cash",paymentReference:"",reason:"Election",idempotencyKey:id(6)},
{action:"set_payout",eventId:id(1),poolId:id(2),participantId:id(4),payoutId:id(7),placement:1,amountMinor:1000,voided:false,reason:"Cross checked",idempotencyKey:id(8)},
{action:"finalize",eventId:id(1),poolId:id(2),reconciliationId:id(9),idempotencyKey:id(10)}])assert.equal(isSidePoolMutation(action),true);});

test("Side Pool director export includes participant finance and reconciliation fields",()=>{const csv=buildSidePoolDirectorCsv({tournamentName:"Sample Tournament",events:[{eventId:id(1),name:"Main",eventType:"main",participants:[{participantId:id(2),displayName:"Sample Player"}],pools:[{poolId:id(3),version:1,categoryCode:"10",displayName:"$10 Side Pool",entryFeeMinor:1000,policy:null,elections:[{electionId:id(4),participantId:id(2),displayName:"Sample Player",version:1,elected:true,amountDueMinor:1000,amountReceivedMinor:1000,amountRemainingMinor:0,paymentMethod:"cash",paymentReference:null}],payouts:[{payoutId:id(5),participantId:id(2),displayName:"Sample Player",version:1,placement:1,amountMinor:1000,voided:false}],collectedMinor:1000,paidMinor:1000,finalized:true}]}]});assert.match(csv,/Sample Tournament,Main,\$10 Side Pool/);assert.match(csv,/Sample Player,true,1000,1000,0,cash/);assert.match(csv,/Pool Collected \(cents\).*Reconciled/);});

test("Satellite packages are versioned, evidence-gated, MRP-safe, qualification-isolated, and retained",()=>{const sql=read("database/migrations/0171_satellite_results_reporting.sql");for(const token of ["satellite_result_versions","cross_check_complete","Not applicable—Satellite event","qualification_effect='none'","retention_until","12 months","duplicate_placement","duplicate_entrant","winner_required","save_draft","finalize","reopen","correct"])assert.match(sql,new RegExp(token));const request={eventId:id(1),packageId:id(2),versionId:id(3),action:"finalize",placements:[{placement:1,entrantId:id(4),displayName:"Sample Player",prizeMinor:10000,qPoolMinor:2000,sidePoolMinor:3000,crossCheckEvidence:[{type:"cross_checked_scorecard",ref:"receipt-1"}]}],specialHands:[{entrantId:id(4),displayName:"Sample Player",hand:29,evidenceRef:"photo-1"}],directorNotes:"Reviewed",expectedVersion:1,idempotencyKey:id(5)};assert.equal(isSatelliteSaveRequest(request),true);assert.equal(isSatelliteSaveRequest({...request,placements:[{...request.placements[0],crossCheckEvidence:[]}]}),false,"final result submissions fail closed without cross-check evidence");assert.equal(isSatelliteSaveRequest({...request,action:"save_draft",placements:[{...request.placements[0],crossCheckEvidence:[]}]}),true,"drafts remain editable before evidence is complete");});

test("Satellite report is a printable PDF with required retained evidence",async()=>{const current={packageId:id(1),versionId:id(2),version:2,status:"finalized",placements:[{placement:1,entrantId:id(3),displayName:"Sample Winner",prizeMinor:10000,qPoolMinor:2000,sidePoolMinor:3000,crossCheckEvidence:[{type:"cross_checked_scorecard",ref:"receipt-1"}]}],specialHands:[{entrantId:id(3),displayName:"Sample Winner",hand:29,evidenceRef:"photo-1"}],directorNotes:"Reviewed",crossCheckComplete:true,mrpStatus:"Not applicable—Satellite event",qualificationEffect:"none",retentionUntil:"2027-09-14",approvedBy:"Sample Director",approvedAt:"2026-09-14T20:00:00Z"};const bytes=await buildSatelliteResultsPdf({tournamentName:"Sample Tournament",eventName:"Sample Satellite",format:"standard_singles",scoringMethod:"manual",current});const document=await PDFDocument.load(bytes);assert.ok(bytes.length>1000);assert.ok(document.getPageCount()>=1);});

test("new protected mutation routes retain verified identity, same-origin mutation, and service-only database authority",()=>{for(const path of ["src/app/api/v1/tournaments/[id]/schedule-amendments/route.ts","src/app/api/v1/tournaments/[id]/operational-forfeits/route.ts","src/app/api/v1/tournaments/[id]/player-exceptions/route.ts","src/app/api/v1/tournaments/[id]/satellite-results/route.ts"]){const source=read(path);assert.match(source,/isSameOriginRequest/);assert.match(source,/requireVerifiedSubject/);assert.match(source,/createServerOnlyAdminClient/);assert.match(source,/readLargeJson/);}});

test("remaining operations foreign keys have covering indexes",()=>{const sql=read("database/migrations/0172_remaining_operations_foreign_key_indexes.sql");for(const token of ["event_schedule_amendments_receipt_scope_idx","operational_forfeits_winner_scope_idx","late_refund_roster_scope_idx","excluded_extra_game_b_scope_idx","side_pool_reconciliation_receipt_scope_idx","satellite_result_versions_package_scope_idx","satellite_result_versions_supersedes_idx"])assert.match(sql,new RegExp(token));});

test("hosted rollback fixture covers every schedule case and new service-only boundary",()=>{const sql=read("tests/remaining-tournament-operations.sql");for(const token of ["omitted_player_before_play","late_player_before_game_two","odd_field_first_sitout_makeup","early_departure_substitute","odd_field_extra_games","mixed_rotation_repair","reinstatement_future_games","configure_event_side_pool_policy_v1","validate_satellite_result_document_v1","has_function_privilege","rollback;"])assert.match(sql,new RegExp(token));});

test("release repair permits final-game substitutes and locks forfeits to both players' current game",()=>{const sql=read("database/migrations/0173_operational_forfeit_progression_repairs.sql");assert.doesNotMatch(sql,/p_operation_kind='early_departure_substitute'[\s\S]{0,600}final_game_requires_substitute/);assert.match(sql,/participant_game_progression_v1\(p_game_id,p_winner_participant_id\).*distinct from'current'/);assert.match(sql,/participant_game_progression_v1\(p_game_id,p_departing_participant_id\).*distinct from'current'/);assert.match(sql,/when progress.status='completed'then'view_scorecard'/);});
