import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import { rule12CorrectionEnabled } from "../src/lib/api/rule12-correction-release.ts";
import { createRule12Correction } from "../src/lib/corrections/independent-lifecycle.ts";

const migration=fs.readFileSync("database/migrations/0140_rule12_independent_card_correction_release.sql","utf8");
const id=(n)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
test("reviewed migration 0140 workflow is available without a deployment token",()=>{assert.equal(rule12CorrectionEnabled({}),true);assert.equal(rule12CorrectionEnabled({ACC_RULE12_CORRECTION_ENABLED:"true"}),true);assert.equal(rule12CorrectionEnabled({ACC_RULE12_CORRECTION_ENABLED:"approved-0140"}),true)});
test("migration covers every corrective Rule 12 case and preserves separate originals",()=>{for(const c of ["12.2a","12.2b","12.2c","12.2d","12.2e","12.2f","12.2h"])assert.match(migration,new RegExp(c.replace(".","\\.")));assert.match(migration,/create table app\.independent_card_correction_claims/);assert.match(migration,/recorded_column text/);assert.match(migration,/create table app\.rule12_affected_player_notices/);assert.match(migration,/queue_rule12_affected_player_notice/);assert.doesNotMatch(migration,/update app\.(canonical_games|card_scorelines)/i)});
test("writer is service-only, role scoped, non-self, policy aware, serialized, and idempotent",()=>{assert.match(migration,/coalesce\(auth\.role\(\),''\)<>'service_role'/);assert.match(migration,/r\.role='cross_checker'/);assert.match(migration,/self_correction_denied/);assert.match(migration,/reason_required/);assert.match(migration,/required_approvals/);assert.match(migration,/pg_advisory_xact_lock/);assert.match(migration,/idempotency_conflict/);assert.match(migration,/grant execute on function public\.create_rule12_correction_v2[^;]+to service_role/);assert.doesNotMatch(migration,/grant execute on function public\.create_rule12_correction_v2[^;]+to authenticated/)});
test("policy, workspace, review reconciliation, and notices are rebound to service-only functions",()=>{for(const name of ["get_rule12_correction_workspace_v2","get_rule12_correction_policy_v1","configure_rule12_correction_policy_v1","get_rule12_correction_policy_reconciliation_v1","get_rule12_correction_reconciliation_v1","get_rule12_player_notices_v1"]){assert.match(migration,new RegExp(`grant execute on function public\\.${name}[^;]+to service_role`));assert.doesNotMatch(migration,new RegExp(`grant execute on function public\\.${name}[^;]+to authenticated`))}assert.match(fs.readFileSync("src/app/api/v1/tournaments/[id]/correction-policy/route.ts","utf8"),/configure_rule12_correction_policy_v1/);assert.match(fs.readFileSync("src/lib/corrections/workspace.ts","utf8"),/get_rule12_correction_workspace_v2/)});
test("review authority, replay order, qualification guard, actionable UI, and uncertain retries are release bounded",()=>{assert.match(migration,/review_rule12_correction_v2/);assert.match(migration,/authorized boolean:=false/);assert.match(migration,/authorized:=true;[\s\S]*select \* into prior from app\.operation_receipts[\s\S]*if found then[\s\S]*perform 1 from app\.tournaments where id=c\.tournament_id and status='open'/);assert.match(migration,/if authorized then[\s\S]*pg_advisory_xact_lock[\s\S]*select \* into c from app\.independent_card_corrections[\s\S]*c\.editor_profile_id=p_actor_id/);assert.match(migration,/policy snapshot invalid/);assert.match(migration,/latest\.state='applied'[\s\S]*rule12_affected_player_notices/);assert.match(migration,/if strpos\(definition,new_guard\)>0 then[\s\S]*elsif strpos\(definition,old_guard\)>0 then[\s\S]*raise exception '0131 qualification notice guard shape unavailable'/);const workspace=fs.readFileSync("src/lib/corrections/workspace.ts","utf8"),client=fs.readFileSync("src/app/tournament/[tournamentId]/corrections/corrections-client.tsx","utf8"),home=fs.readFileSync("src/app/tournament/[tournamentId]/page.tsx","utf8");for(const marker of ["original","adjudicated","apparentQualifier","affectedNoticeTarget"])assert.match(workspace,new RegExp(marker));assert.match(client,/acc-correction:proposal:\$\{actorId\}/);assert.match(client,/acc-correction:review:\$\{actorId\}/);assert.match(client,/Retry exact saved correction/);assert.match(client,/Retry sends the exact saved decision/);assert.match(home,/rule12CorrectionEnabled\(\) && isCrossCheckOfficial[\s\S]*Independent scorecard corrections/)});
test("scorecard and standings projections select applied adjudicated values once",()=>{for(const file of ["database/migrations/0125_hybrid_scorecard_reconstruction_repair.sql","database/migrations/0107_preliminary_event_standings_reader.sql"]){const text=fs.readFileSync(file,"utf8");assert.match(text,/adjudicated_game_points/);assert.match(text,/state = 'applied'/);assert.match(text,/order by correction\.correction_sequence desc[\s\S]*limit 1/)}});
test("rollback lifecycle fixture covers both policies, decisions, notices, retries, projections, and grants",()=>{const fixture=fs.readFileSync("tests/rule12b-correction-lifecycle.sql","utf8");for(const marker of ["create_rule12_correction_v2","review_rule12_correction_v2","'immediate'","'pending'","'approved'","'review_rejected'","'changed_retry'","'changed_review_retry'","rule12_affected_player_notices","corrected_scorecard","adjudicated","rollback;"])assert.match(fixture,new RegExp(marker));assert.match(fixture,/required_approvals[\s\S]*1/);assert.match(fixture,/service_role'[\s\S]*review_rule12_correction_v1[\s\S]*'EXECUTE'/)});
test("adapter binds the complete independent-card RPC contract",async()=>{const calls=[];const input={actorId:id(1),gameId:id(2),correctionId:id(3),expectedGameVersion:2,expectedCorrectionSequence:1,ruleCase:"12.2c",claimA:{outcome:"win",margin:12,column:"plus",apparentQualifier:false},claimB:{outcome:"loss",margin:null,column:"blank",apparentQualifier:false},qualificationChanged:true,affectedParticipantId:id(5),reason:"paper card cross-check",operationId:id(4)};const client={async rpc(name,args){calls.push({name,args});return{data:{status:"pending",correctionId:input.correctionId,gameId:input.gameId,gameVersion:2,correctionSequence:2,policyVersion:1,reasonRequired:false,requiredApprovals:1,qualificationChanged:true},error:null}}};assert.equal((await createRule12Correction(client,input)).status,"pending");assert.equal(calls[0].name,"create_rule12_correction_v2");assert.equal(calls[0].args.p_affected_participant_id,id(5));assert.deepEqual(calls[0].args.p_claim_b,input.claimB)});
