"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { PaymentRosterEntry } from "../../../../lib/api/payment";
import { isPaymentRecordRequest, isPaymentRecoveryRequest, isPaymentVoidRequest, isRecordedPayment, isRejectedPayment, isVoidedPayment, type PaymentRecordRequest, type PaymentRecoveryRequest, type PaymentVoidRequest } from "../../../../lib/api/payment";

type Envelope = PaymentRecoveryRequest & { kind: "payment"; digest: string };
type RecordFields = Omit<PaymentRecordRequest, "rosterEntryId" | "expectedPaymentVersion" | "idempotencyKey">;
type VoidFields = Omit<PaymentVoidRequest, "rosterEntryId" | "expectedPaymentVersion" | "paymentEventId" | "idempotencyKey">;

function validEnvelope(value: unknown): value is Envelope { if (!value || typeof value !== "object") return false; const item = value as Record<string, unknown>; const digestValue = item.digest; return item.kind === "payment" && typeof digestValue === "string" && /^[a-f0-9]{64}$/.test(digestValue) && isPaymentRecoveryRequest(item); }
function readEnvelope(key: string) { try { const raw = window.sessionStorage.getItem(key); const value: unknown = raw ? JSON.parse(raw) : null; return validEnvelope(value) ? value : null; } catch { return null; } }
function writeEnvelope(key: string, value: Envelope) { try { window.sessionStorage.setItem(key, JSON.stringify(value)); return true; } catch { return false; } }
function clearEnvelope(key: string) { try { window.sessionStorage.removeItem(key); } catch { /* Server state is authoritative. */ } }
function clearOtherActors(storage: Storage, actorId: string) { for (let index = storage.length - 1; index >= 0; index -= 1) { const key = storage.key(index); if (key?.startsWith("payment-operation:") && !key.startsWith(`payment-operation:${actorId}:`)) storage.removeItem(key); } }
async function digest(value: unknown) { const bytes = new TextEncoder().encode(JSON.stringify(value)); const hash = await crypto.subtle.digest("SHA-256", bytes); return Array.from(new Uint8Array(hash), (byte) => byte.toString(16).padStart(2, "0")).join(""); }
const now = () => new Date().toISOString();
function dollarsToMinor(value: string) { const match = /^(0|[1-9]\d*)(?:\.(\d{1,2}))?$/.exec(value.trim()); if (!match || match[1].length > 8) return null; const cents = Number(match[1]) * 100 + Number((match[2] ?? "").padEnd(2, "0") || "0"); return Number.isSafeInteger(cents) && cents > 0 && cents <= 2147483647 ? cents : null; }

function PaymentRow({ entry, disabled, unavailableReason, acceptedMethods, onRecord, onVoid }: { entry: PaymentRosterEntry; disabled: boolean; unavailableReason: string | null; acceptedMethods: readonly ("cash" | "check")[]; onRecord: (entry: PaymentRosterEntry, fields: RecordFields) => void; onVoid: (entry: PaymentRosterEntry, fields: VoidFields) => void }) {
  const [amount, setAmount] = useState(""); const [method, setMethod] = useState<"cash" | "check">(acceptedMethods[0] ?? "cash"); const [receivedAt, setReceivedAt] = useState(now); const [note, setNote] = useState(""); const [voidReason, setVoidReason] = useState("");
  const receipt = entry.currentReceiptEventId;
  function submitRecord() { const amountMinor = dollarsToMinor(amount); const activeMethod = acceptedMethods.includes(method) ? method : acceptedMethods[0]; if (amountMinor === null || !activeMethod) return; onRecord(entry, { amountMinor, paymentMethod: activeMethod, paymentReceivedAt: receivedAt, note }); }
  return <li className="correction-item"><h2>{entry.displayName}</h2><p><strong>Player planned:</strong> {entry.plannedPaymentMethod === "cash" ? "Cash" : entry.plannedPaymentMethod === "check" ? "Check" : "Not specified"}</p><p><strong>Evidence status:</strong> {entry.paymentState === "unrecorded" ? "No receipt recorded" : entry.paymentState === "received" ? "Current receipt recorded" : "Most recent receipt voided"} · history version {entry.paymentVersion}</p>{entry.history.length ? <ol>{entry.history.map((item) => <li key={item.paymentEventId}><strong>{item.eventType === "received" ? "Receipt recorded" : "Receipt voided"}</strong> · ${" "}{(item.amountMinor / 100).toFixed(2)} USD · {item.paymentMethod === "cash" ? "Cash" : item.paymentMethod === "check" ? "Check" : "Historical manual payment"}</li>)}</ol> : null}{disabled && unavailableReason ? <p className="auth-note">{unavailableReason}</p> : null}{entry.paymentState !== "received" ? <fieldset disabled={disabled}><legend>Record cash or check received</legend><label>Amount in USD<input inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0.00" /></label><label>Payment method<select value={method} onChange={(event) => setMethod(event.target.value as "cash" | "check")}>{acceptedMethods.includes("cash") ? <option value="cash">Cash</option> : null}{acceptedMethods.includes("check") ? <option value="check">Check</option> : null}</select></label><label>Received at (UTC)<input value={receivedAt} onChange={(event) => setReceivedAt(event.target.value)} aria-describedby={`${entry.rosterEntryId}-received-help`} /></label><p id={`${entry.rosterEntryId}-received-help`}>Keep the supplied UTC date/time format. Do not enter card, bank-account, or full check details.</p><label>Optional receipt note<textarea value={note} maxLength={500} onChange={(event) => setNote(event.target.value)} /></label><button className="primary" type="button" onClick={submitRecord}>Record receipt evidence</button></fieldset> : <fieldset disabled={disabled}><legend>Void current receipt</legend><label>Reason for void<textarea value={voidReason} maxLength={500} onChange={(event) => setVoidReason(event.target.value)} /></label><button className="secondary" type="button" onClick={() => receipt && onVoid(entry, { voidReason })}>Void current receipt</button></fieldset>}</li>;
}

export default function PaymentClient({ actorId, tournamentId, rosterEntries, acceptedMethods }: { actorId: string; tournamentId: string; rosterEntries: PaymentRosterEntry[]; acceptedMethods: readonly ("cash" | "check")[] }) {
  const router = useRouter(); const storageKey = `payment-operation:${actorId}:${tournamentId}`; const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [locked, setLocked] = useState<Envelope | null>(null); const [message, setMessage] = useState<string | null>(null); const inFlight = useRef(false);
  const reconcile = useCallback(async (envelope: Envelope) => { try { const response = await fetch(`/api/v1/tournaments/${tournamentId}/payments/reconciliation`, { method: "POST", headers: { "content-type": "application/json" }, credentials: "same-origin", cache: "no-store", body: JSON.stringify(envelope) }); const payload: unknown = response.ok ? await response.json().catch(() => null) : null; if (!payload || typeof payload !== "object" || !("result" in (payload as Record<string, unknown>))) return "unresolved"; const result = (payload as Record<string, unknown>).result; if (result === null) return "none"; if (envelope.operationType === "record_manual_roster_payment" ? isRecordedPayment(result, { rosterEntryId: envelope.rosterEntryId, expectedPaymentVersion: envelope.expectedPaymentVersion, amountMinor: 1, paymentMethod: "cash", paymentReceivedAt: now(), note: "", idempotencyKey: envelope.idempotencyKey }) : isVoidedPayment(result, { rosterEntryId: envelope.rosterEntryId, expectedPaymentVersion: envelope.expectedPaymentVersion, paymentEventId: envelope.paymentEventId!, voidReason: "x", idempotencyKey: envelope.idempotencyKey })) return "accepted"; return isRejectedPayment(result, envelope.rosterEntryId, envelope.operationType) ? "rejected" : "unresolved"; } catch { return "unresolved"; } }, [tournamentId]);
  useEffect(() => { clearOtherActors(window.sessionStorage, actorId); void (async () => { const saved = readEnvelope(storageKey); if (!saved) { setReady(true); return; } const state = await reconcile(saved); if (state === "accepted") { clearEnvelope(storageKey); setReady(true); router.refresh(); return; } if (state === "rejected") { clearEnvelope(storageKey); setMessage("The prior payment action was rejected by the tournament server; no payment evidence was changed."); setReady(true); router.refresh(); return; } if (state === "none") { clearEnvelope(storageKey); setMessage("A previous payment action did not reach the tournament server. Re-enter the details before trying again."); setReady(true); return; } setLocked(saved); setMessage("A prior payment action is still unresolved. Re-enter its original details exactly before retrying; other payment actions are locked."); setReady(true); })(); }, [actorId, reconcile, router, storageKey]);
  async function submit(kind: Envelope["operationType"], entry: PaymentRosterEntry, fields: RecordFields | VoidFields) { if (!ready || busy || inFlight.current) return; inFlight.current = true; try { const paymentEventId = kind === "void_manual_roster_payment" ? entry.currentReceiptEventId : null; if (kind === "void_manual_roster_payment" && !paymentEventId) return; const provisionalKey = locked?.idempotencyKey ?? crypto.randomUUID(); const body = kind === "record_manual_roster_payment" ? { ...fields, rosterEntryId: entry.rosterEntryId, expectedPaymentVersion: entry.paymentVersion, idempotencyKey: provisionalKey } : { ...fields, rosterEntryId: entry.rosterEntryId, expectedPaymentVersion: entry.paymentVersion, paymentEventId, idempotencyKey: provisionalKey }; if (kind === "record_manual_roster_payment" ? !isPaymentRecordRequest(body) : !isPaymentVoidRequest(body)) { setMessage("Enter a valid amount, UTC date/time, and required reason before recording payment evidence."); return; } const operationDigest = await digest({ kind, rosterEntryId: entry.rosterEntryId, expectedPaymentVersion: entry.paymentVersion, paymentEventId, fields }); let envelope = locked; if (envelope) { if (envelope.operationType !== kind || envelope.rosterEntryId !== entry.rosterEntryId || envelope.expectedPaymentVersion !== entry.paymentVersion || envelope.paymentEventId !== paymentEventId || envelope.digest !== operationDigest) { setMessage("This action is locked. Re-enter the original details exactly or refresh after the prior action resolves."); return; } } else { envelope = { kind: "payment", operationType: kind, rosterEntryId: entry.rosterEntryId, expectedPaymentVersion: entry.paymentVersion, paymentEventId, idempotencyKey: provisionalKey, digest: operationDigest }; if (!writeEnvelope(storageKey, envelope)) { setMessage("This browser cannot safely retain a payment request for recovery. Enable session storage before continuing."); return; } }
    setBusy(true); setLocked(envelope); setMessage(null); const path = kind === "record_manual_roster_payment" ? "record" : "void"; const response = await fetch(`/api/v1/tournaments/${tournamentId}/payments/${path}`, { method: "POST", headers: { "content-type": "application/json" }, credentials: "same-origin", cache: "no-store", body: JSON.stringify(body) }); const result: unknown = await response.json().catch(() => null); const accepted = response.ok && (kind === "record_manual_roster_payment" ? isRecordedPayment(result, body as PaymentRecordRequest) : isVoidedPayment(result, body as PaymentVoidRequest)); if (accepted) { clearEnvelope(storageKey); setLocked(null); router.refresh(); return; } if (response.status === 409 && isRejectedPayment(result, entry.rosterEntryId, kind)) { clearEnvelope(storageKey); setLocked(null); setMessage("The tournament server rejected that payment action; no payment evidence was changed."); router.refresh(); return; } setMessage("The payment action is unresolved. It remains locked until safely reconciled."); } catch { setMessage("The payment action is unresolved. It remains locked until safely reconciled."); } finally { inFlight.current = false; setBusy(false); }
  }
  // One pending payment locks every other row. Name the player holding it, so
  // a desk looking at a page of greyed rows knows which one to resolve.
  const lockedName = locked ? rosterEntries.find((row) => row.rosterEntryId === locked.rosterEntryId)?.displayName ?? "Another player" : null;
  return <section className="policy-settings" aria-label="Manual payment history"><p>Record only cash or check that the director has actually received. This evidence remains separate from check-in, seating, enrollment, scoring, and final reconciliation.</p>{rosterEntries.length ? <ul className="correction-list">{rosterEntries.map((entry) => <PaymentRow key={entry.rosterEntryId} entry={entry} acceptedMethods={acceptedMethods} disabled={!ready || busy || (!!locked && locked.rosterEntryId !== entry.rosterEntryId)} unavailableReason={locked && locked.rosterEntryId !== entry.rosterEntryId ? `${lockedName} has a payment action waiting to resolve. Finish or refresh that one, then this row can be used again.` : null} onRecord={(row, fields) => void submit("record_manual_roster_payment", row, fields)} onVoid={(row, fields) => void submit("void_manual_roster_payment", row, fields)} />)}</ul> : <p>No private roster entries are available yet.</p>}{message ? <p className="error-text" role="alert">{message}</p> : null}</section>;
}
