import { NextRequest } from "next/server";
import { isAddedSidePool, isAddSidePoolRequest, isRejectedSidePool, isSidePoolWorkspace } from "../../../../../../lib/api/side-pools";
import { apiJson, readLargeJson, requireVerifiedSubject, withApiFailureBoundary } from "../../../../../../lib/api/route-boundary";
import { isSameOriginRequest } from "../../../../../../lib/api/same-origin";
import { isUuid } from "../../../../../../lib/api/validation";
import { createServerOnlyAdminClient } from "../../../../../../lib/supabase/private-admin";
import { createClient } from "../../../../../../lib/supabase/server";
export async function GET(_request: NextRequest,{params}:{params:Promise<{id:string}>}){return withApiFailureBoundary(async()=>{const{id}=await params;if(!isUuid(id))return apiJson({error:"invalid_tournament"},{status:400});const actor=await requireVerifiedSubject(await createClient());if(!actor)return apiJson({error:"unauthorized"},{status:401});const{data,error}=await createServerOnlyAdminClient().rpc("get_event_side_pool_workspace_v1",{p_actor_id:actor,p_tournament_id:id});if(error)return apiJson({error:"operation_unavailable"},{status:503});if(data===null)return apiJson({error:"not_found"},{status:404});return isSidePoolWorkspace(data)?apiJson(data):apiJson({error:"operation_unavailable"},{status:503});});}
export async function POST(request:NextRequest,{params}:{params:Promise<{id:string}>}){return withApiFailureBoundary(async()=>{if(!isSameOriginRequest(request))return apiJson({error:"invalid_origin"},{status:403});const{id}=await params;const body=await readLargeJson(request);if(!isUuid(id)||!isAddSidePoolRequest(body))return apiJson({error:"invalid_side_pool"},{status:400});const actor=await requireVerifiedSubject(await createClient());if(!actor)return apiJson({error:"unauthorized"},{status:401});const{data,error}=await createServerOnlyAdminClient().rpc("add_event_side_pool_v1",{p_actor_id:actor,p_tournament_id:id,p_event_id:body.eventId,p_pool_id:body.poolId,p_category_code:body.categoryCode,p_display_name:body.displayName,p_entry_fee_minor:body.entryFeeMinor,p_idempotency_key:body.idempotencyKey});if(error)return apiJson({error:"operation_unavailable"},{status:503});if(isAddedSidePool(data,body))return apiJson(data);if(isRejectedSidePool(data))return apiJson(data,{status:409});return apiJson({error:"operation_unavailable"},{status:503});});}
