import { NextRequest } from "next/server";
import { isRejectedTeamMutation,isTeamMutation,isTeamMutationResult,isTeamWorkspace } from "../../../../../../lib/api/team-operations";
import { apiJson,readLargeJson,requireVerifiedSubject,withApiFailureBoundary } from "../../../../../../lib/api/route-boundary";
import { isSameOriginRequest } from "../../../../../../lib/api/same-origin";
import { isUuid } from "../../../../../../lib/api/validation";
import { createServerOnlyAdminClient } from "../../../../../../lib/supabase/private-admin";
import { createClient } from "../../../../../../lib/supabase/server";

export async function GET(_r:NextRequest,{params}:{params:Promise<{id:string}>}){return withApiFailureBoundary(async()=>{const{id}=await params;if(!isUuid(id))return apiJson({error:"invalid_tournament"},{status:400});const actor=await requireVerifiedSubject(await createClient());if(!actor)return apiJson({error:"unauthorized"},{status:401});const{data,error}=await createServerOnlyAdminClient().rpc("get_event_team_workspace_v1",{p_actor_id:actor,p_tournament_id:id});if(error)return apiJson({error:"operation_unavailable"},{status:503});const workspace=data&&typeof data==="object"&&!Array.isArray(data)?{...data as Record<string,unknown>,actorId:actor}:data;if(!isTeamWorkspace(workspace))return apiJson({error:"not_found"},{status:404});return apiJson(workspace);});}
export async function POST(request:NextRequest,{params}:{params:Promise<{id:string}>}){return withApiFailureBoundary(async()=>{if(!isSameOriginRequest(request))return apiJson({error:"invalid_origin"},{status:403});const{id}=await params,body=await readLargeJson(request);if(!isUuid(id)||!isTeamMutation(body))return apiJson({error:"invalid_team_operation"},{status:400});const actor=await requireVerifiedSubject(await createClient());if(!actor)return apiJson({error:"unauthorized"},{status:401});const admin=createServerOnlyAdminClient();let result;
 if(body.action==="create_team")result=await admin.rpc("create_event_team_v1",{p_actor_id:actor,p_tournament_id:id,p_event_id:body.eventId,p_team_id:body.teamId,p_team_entry_id:body.teamEntryId,p_captain_roster_entry_id:body.captainRosterEntryId,p_partner_roster_entry_id:body.partnerRosterEntryId,p_scorecard_type:body.scorecardType,p_operation_id:body.operationId});
 else if(body.action==="claim_partner")result=await admin.rpc("claim_event_team_partner_v1",{p_actor_id:actor,p_tournament_id:id,p_event_id:body.eventId,p_team_id:body.teamId,p_roster_entry_id:body.rosterEntryId,p_claim_id:body.claimId,p_operation_id:body.operationId});
 else if(body.action==="configure_team")result=await admin.rpc("configure_event_team_v1",{p_actor_id:actor,p_tournament_id:id,p_event_id:body.eventId,p_team_entry_id:body.teamEntryId,p_scorecard_type:body.scorecardType,p_designated_scorer_profile_id:body.designatedScorerProfileId,p_expected_version:body.expectedVersion,p_reason:body.reason,p_operation_id:body.operationId});
 else if(body.action==="publish_seating")result=await admin.rpc("publish_event_team_seating_v1",{p_actor_id:actor,p_tournament_id:id,p_event_id:body.eventId,p_publication_id:body.publicationId,p_assignments:body.assignments,p_operation_id:body.operationId});
 else if(body.action==="publish_schedule")result=await admin.rpc("publish_event_team_schedule_v1",{p_actor_id:actor,p_tournament_id:id,p_event_id:body.eventId,p_publication_id:body.publicationId,p_game_count:body.gameCount,p_matches:body.games,p_operation_id:body.operationId});
 else if(body.action==="start_play")result=await admin.rpc("start_event_team_play_v1",{p_actor_id:actor,p_tournament_id:id,p_event_id:body.eventId,p_start_id:body.startId,p_schedule_publication_id:body.schedulePublicationId,p_operation_id:body.operationId});
 else if(body.action==="submit_score")result=await admin.rpc("submit_event_team_score_v1",{p_actor_id:actor,p_tournament_id:id,p_game_id:body.gameId,p_submission_id:body.submissionId,p_winner_side:body.winnerSide,p_margin:body.margin,p_operation_id:body.operationId});
 else if(body.action==="submit_paper_score")result=await admin.rpc("submit_event_team_paper_score_v1",{p_actor_id:actor,p_tournament_id:id,p_game_id:body.gameId,p_side:body.side,p_submission_id:body.submissionId,p_paper_card_reference:body.paperCardReference,p_winner_side:body.winnerSide,p_margin:body.margin,p_operation_id:body.operationId});
 else if(body.action==="review_paper_score")result=await admin.rpc("review_event_team_paper_score_v1",{p_actor_id:actor,p_tournament_id:id,p_game_id:body.gameId,p_submission_id:body.submissionId,p_review_id:body.reviewId,p_paper_card_reference:body.paperCardReference,p_winner_side:body.winnerSide,p_margin:body.margin,p_operation_id:body.operationId});
 else if(body.action==="confirm_score")result=await admin.rpc("confirm_event_team_score_v1",{p_actor_id:actor,p_tournament_id:id,p_game_id:body.gameId,p_submission_id:body.submissionId,p_confirmation_id:body.confirmationId,p_operation_id:body.operationId});
 else if(body.action==="correct_score")result=await admin.rpc("propose_event_team_score_correction_v1",{p_actor_id:actor,p_tournament_id:id,p_game_id:body.gameId,p_correction_id:body.correctionId,p_expected_game_version:body.expectedGameVersion,p_winner_side:body.winnerSide,p_margin:body.margin,p_reason:body.reason,p_operation_id:body.operationId});
 else if(body.action==="review_correction")result=await admin.rpc("review_event_team_score_correction_v1",{p_actor_id:actor,p_tournament_id:id,p_correction_id:body.correctionId,p_review_id:body.reviewId,p_approved:body.approved,p_operation_id:body.operationId});
 else if(body.action==="resolve_mismatch")result=await admin.rpc("propose_event_team_mismatch_resolution_v1",{p_actor_id:actor,p_tournament_id:id,p_game_id:body.gameId,p_resolution_id:body.resolutionId,p_expected_game_version:body.expectedGameVersion,p_winner_side:body.winnerSide,p_margin:body.margin,p_reason:body.reason,p_operation_id:body.operationId});
 else result=await admin.rpc("review_event_team_mismatch_resolution_v1",{p_actor_id:actor,p_tournament_id:id,p_resolution_id:body.resolutionId,p_review_id:body.reviewId,p_approved:body.approved,p_operation_id:body.operationId});
 if(result.error)return apiJson({error:"operation_unavailable"},{status:503});if(isTeamMutationResult(result.data))return apiJson(result.data);if(isRejectedTeamMutation(result.data))return apiJson(result.data,{status:409});return apiJson({error:"operation_unavailable"},{status:503});});}
