-- Cover every settlement foreign-key prefix reported by the Supabase advisor.
-- These indexes support referential checks and scoped joins without changing access.

create index standard_singles_settlement_awards_draft_scope_idx on app.standard_singles_settlement_awards(settlement_draft_id,tournament_id,event_id);
create index standard_singles_settlement_conflicts_tournament_idx on app.standard_singles_settlement_conflicts(tournament_id);
create index standard_singles_settlement_drafts_receipt_scope_idx on app.standard_singles_settlement_drafts(operation_receipt_id,tournament_id);
create index standard_singles_settlement_drafts_qualification_scope_idx on app.standard_singles_settlement_drafts(qualification_result_version_id,tournament_id,event_id);
create index standard_singles_settlement_drafts_setup_event_scope_idx on app.standard_singles_settlement_drafts(setup_event_version_id,tournament_id,setup_revision_id);
create index standard_singles_settlement_drafts_supersedes_idx on app.standard_singles_settlement_drafts(supersedes_draft_id);
create index standard_singles_settlement_expense_sources_event_scope_idx on app.standard_singles_settlement_expense_sources(expense_event_id,expense_id,tournament_id);
create index standard_singles_settlement_expense_sources_draft_scope_idx on app.standard_singles_settlement_expense_sources(settlement_draft_id,tournament_id);
create index standard_singles_settlement_payment_sources_draft_scope_idx on app.standard_singles_settlement_payment_sources(settlement_draft_id,tournament_id);
create index standard_singles_settlement_payment_sources_event_scope_idx on app.standard_singles_settlement_payment_sources(payment_event_id,roster_entry_id,tournament_id);
create index standard_singles_settlement_placements_draft_scope_idx on app.standard_singles_settlement_placements(settlement_draft_id,tournament_id,event_id);
