-- Side Pool beneficiaries for digitally or paper-scored team entries. Singles
-- remain in their original append-only tables; team money is isolated here.
create table app.event_side_pool_team_election_versions(
 id uuid primary key default extensions.gen_random_uuid(), election_id uuid not null, pool_id uuid not null,
 tournament_id uuid not null, event_id uuid not null, team_entry_id uuid not null, version integer not null check(version>0),
 elected boolean not null, amount_due_minor integer not null check(amount_due_minor>=0), amount_received_minor integer not null check(amount_received_minor between 0 and amount_due_minor),
 payment_method text check(payment_method in('cash','check')), payment_reference text check(payment_reference is null or length(payment_reference)<=100), reason text not null check(length(trim(reason)) between 1 and 500),
 actor_profile_id uuid not null references app.profiles(id) on delete restrict, operation_receipt_id uuid not null, created_at timestamptz not null default clock_timestamp(),
 foreign key(pool_id,tournament_id,event_id) references app.event_side_pools(id,tournament_id,event_id) on delete restrict,
 foreign key(team_entry_id) references app.event_team_entries(id) on delete restrict,
 foreign key(operation_receipt_id,tournament_id) references app.operation_receipts(id,tournament_id) on delete restrict, unique(election_id,version)
);
create table app.event_side_pool_team_payout_versions(
 id uuid primary key default extensions.gen_random_uuid(), payout_id uuid not null, pool_id uuid not null, tournament_id uuid not null, event_id uuid not null, team_entry_id uuid not null, version integer not null check(version>0), placement integer not null check(placement>0), amount_minor integer not null check(amount_minor>=0), voided boolean not null default false,
 reason text not null check(length(trim(reason)) between 1 and 500), actor_profile_id uuid not null references app.profiles(id) on delete restrict, operation_receipt_id uuid not null, created_at timestamptz not null default clock_timestamp(),
 foreign key(pool_id,tournament_id,event_id) references app.event_side_pools(id,tournament_id,event_id) on delete restrict, foreign key(team_entry_id) references app.event_team_entries(id) on delete restrict, foreign key(operation_receipt_id,tournament_id) references app.operation_receipts(id,tournament_id) on delete restrict, unique(payout_id,version)
);
create table app.event_side_pool_payout_reviews(
 id uuid primary key default extensions.gen_random_uuid(), payout_id uuid not null, beneficiary_kind text not null check(beneficiary_kind in('participant','team_entry')), tournament_id uuid not null, event_id uuid not null, reviewer_profile_id uuid not null references app.profiles(id) on delete restrict, approved boolean not null, evidence_reference text not null check(length(trim(evidence_reference)) between 1 and 500), reviewed_at timestamptz not null default clock_timestamp(), operation_receipt_id uuid not null,
 foreign key(operation_receipt_id,tournament_id) references app.operation_receipts(id,tournament_id) on delete restrict, unique(payout_id,beneficiary_kind,reviewer_profile_id)
);
do $$ declare n text; begin foreach n in array array['event_side_pool_team_election_versions','event_side_pool_team_payout_versions','event_side_pool_payout_reviews'] loop execute format('alter table app.%I enable row level security',n); execute format('alter table app.%I force row level security',n); execute format('revoke all on table app.%I from public,anon,authenticated',n); end loop; end $$;

create or replace function public.set_event_side_pool_team_election_v1(p_actor_id uuid,p_tournament_id uuid,p_event_id uuid,p_pool_id uuid,p_team_entry_id uuid,p_election_id uuid,p_elected boolean,p_amount_received_minor integer,p_payment_method text,p_payment_reference text,p_reason text,p_idempotency_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare d app.event_side_pool_definition_versions%rowtype; prior app.operation_receipts%rowtype; rid uuid:=extensions.gen_random_uuid(); v integer; response jsonb; h text;
begin
 if p_actor_id is null or p_election_id is null or p_idempotency_key is null or p_amount_received_minor<0 or p_payment_method not in('cash','check') or length(trim(p_reason)) not between 1 and 500 then return jsonb_build_object('status','rejected','code','invalid_request'); end if;
 select * into d from app.event_side_pool_definition_versions where pool_id=p_pool_id and event_id=p_event_id order by version desc limit 1;
 if not found or not d.active or not exists(select 1 from app.event_team_entries where id=p_team_entry_id and event_id=p_event_id and tournament_id=p_tournament_id) then return jsonb_build_object('status','rejected','code','pool_unavailable'); end if;
 if p_elected and p_amount_received_minor>d.entry_fee_minor then return jsonb_build_object('status','rejected','code','received_exceeds_due'); end if;
 if not p_elected and p_amount_received_minor<>0 then return jsonb_build_object('status','rejected','code','removed_election_requires_zero'); end if;
 h:=encode(extensions.digest(convert_to(jsonb_build_array('set_event_side_pool_team_election_v1',p_actor_id,p_tournament_id,p_event_id,p_pool_id,p_team_entry_id,p_election_id,p_elected,p_amount_received_minor,p_payment_method,p_payment_reference,p_reason)::text,'utf8'),'sha256'),'hex'); perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('side-pool-team-election:'||p_pool_id||':'||p_team_entry_id,0)); select * into prior from app.operation_receipts where actor_profile_id=p_actor_id and client_operation_id=p_idempotency_key; if found then if prior.request_hash<>h then return jsonb_build_object('status','rejected','code','idempotency_conflict'); end if; return prior.response_payload; end if;
 select coalesce(max(version),0)+1 into v from app.event_side_pool_team_election_versions where election_id=p_election_id; response:=jsonb_build_object('status','side_pool_team_election_recorded','poolId',p_pool_id,'teamEntryId',p_team_entry_id,'electionId',p_election_id,'version',v,'elected',p_elected);
 insert into app.operation_receipts(id,actor_profile_id,tournament_id,operation_type,target_id,request_hash,client_operation_id,outcome,response_payload,applied_at) values(rid,p_actor_id,p_tournament_id,'set_event_side_pool_team_election_v1',p_election_id,h,p_idempotency_key,'accepted',response,clock_timestamp());
 insert into app.event_side_pool_team_election_versions(election_id,pool_id,tournament_id,event_id,team_entry_id,version,elected,amount_due_minor,amount_received_minor,payment_method,payment_reference,reason,actor_profile_id,operation_receipt_id) values(p_election_id,p_pool_id,p_tournament_id,p_event_id,p_team_entry_id,v,p_elected,case when p_elected then d.entry_fee_minor else 0 end,p_amount_received_minor,p_payment_method,nullif(trim(p_payment_reference),''),trim(p_reason),p_actor_id,rid); return response;
end $$;
revoke all on function public.set_event_side_pool_team_election_v1(uuid,uuid,uuid,uuid,uuid,uuid,boolean,integer,text,text,text,uuid) from public,anon,authenticated; grant execute on function public.set_event_side_pool_team_election_v1(uuid,uuid,uuid,uuid,uuid,uuid,boolean,integer,text,text,text,uuid) to service_role;

create or replace function public.review_event_side_pool_payout_v1(p_actor_id uuid,p_tournament_id uuid,p_event_id uuid,p_payout_id uuid,p_beneficiary_kind text,p_approved boolean,p_evidence_reference text,p_idempotency_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare rid uuid:=extensions.gen_random_uuid(); h text; prior app.operation_receipts%rowtype; response jsonb;
begin
 if p_beneficiary_kind not in('participant','team_entry') or p_evidence_reference is null or length(trim(p_evidence_reference)) not between 1 and 500 or p_idempotency_key is null then return jsonb_build_object('status','rejected','code','invalid_request'); end if;
 if not exists(select 1 from app.tournament_roles where tournament_id=p_tournament_id and profile_id=p_actor_id and role in('director','co_director','cross_checker','judge')) then return jsonb_build_object('status','rejected','code','not_reviewer'); end if;
 h:=encode(extensions.digest(convert_to(jsonb_build_array('review_event_side_pool_payout_v1',p_actor_id,p_tournament_id,p_event_id,p_payout_id,p_beneficiary_kind,p_approved,p_evidence_reference)::text,'utf8'),'sha256'),'hex'); select * into prior from app.operation_receipts where actor_profile_id=p_actor_id and client_operation_id=p_idempotency_key; if found then return prior.response_payload; end if;
 if p_beneficiary_kind='participant' and not exists(select 1 from app.event_side_pool_payout_versions where payout_id=p_payout_id and event_id=p_event_id) then return jsonb_build_object('status','rejected','code','payout_unavailable'); end if;
 if p_beneficiary_kind='team_entry' and not exists(select 1 from app.event_side_pool_team_payout_versions where payout_id=p_payout_id and event_id=p_event_id) then return jsonb_build_object('status','rejected','code','payout_unavailable'); end if;
 if exists(select 1 from app.event_side_pool_payout_versions where payout_id=p_payout_id and actor_profile_id=p_actor_id) or exists(select 1 from app.event_side_pool_team_payout_versions where payout_id=p_payout_id and actor_profile_id=p_actor_id) then return jsonb_build_object('status','rejected','code','self_review_forbidden'); end if;
 response:=jsonb_build_object('status','side_pool_payout_reviewed','payoutId',p_payout_id,'beneficiaryKind',p_beneficiary_kind,'approved',p_approved); insert into app.operation_receipts(id,actor_profile_id,tournament_id,operation_type,target_id,request_hash,client_operation_id,outcome,response_payload,applied_at) values(rid,p_actor_id,p_tournament_id,'review_event_side_pool_payout_v1',p_payout_id,h,p_idempotency_key,'accepted',response,clock_timestamp()); insert into app.event_side_pool_payout_reviews(payout_id,beneficiary_kind,tournament_id,event_id,reviewer_profile_id,approved,evidence_reference,operation_receipt_id) values(p_payout_id,p_beneficiary_kind,p_tournament_id,p_event_id,p_actor_id,p_approved,trim(p_evidence_reference),rid) on conflict(payout_id,beneficiary_kind,reviewer_profile_id) do update set approved=excluded.approved,evidence_reference=excluded.evidence_reference,reviewed_at=clock_timestamp(),operation_receipt_id=excluded.operation_receipt_id; return response;
end $$;
revoke all on function public.review_event_side_pool_payout_v1(uuid,uuid,uuid,uuid,text,boolean,text,uuid) from public,anon,authenticated; grant execute on function public.review_event_side_pool_payout_v1(uuid,uuid,uuid,uuid,text,boolean,text,uuid) to service_role;

create or replace function public.set_event_side_pool_team_payout_v1(p_actor_id uuid,p_tournament_id uuid,p_event_id uuid,p_pool_id uuid,p_team_entry_id uuid,p_payout_id uuid,p_placement integer,p_amount_minor integer,p_voided boolean,p_reason text,p_idempotency_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare prior app.operation_receipts%rowtype; rid uuid:=extensions.gen_random_uuid(); v integer; collected integer; paid integer; response jsonb; h text;
begin
 if p_payout_id is null or p_idempotency_key is null or p_placement<1 or p_amount_minor<0 or length(trim(p_reason)) not between 1 and 500 then return jsonb_build_object('status','rejected','code','invalid_request'); end if;
 if not exists(select 1 from app.tournament_roles where tournament_id=p_tournament_id and profile_id=p_actor_id and role in('director','co_director')) or not exists(select 1 from app.event_side_pools where id=p_pool_id and event_id=p_event_id and tournament_id=p_tournament_id) or not exists(select 1 from app.event_team_entries where id=p_team_entry_id and event_id=p_event_id and tournament_id=p_tournament_id) then return jsonb_build_object('status','rejected','code','pool_unavailable'); end if;
 h:=encode(extensions.digest(convert_to(jsonb_build_array('set_event_side_pool_team_payout_v1',p_actor_id,p_tournament_id,p_event_id,p_pool_id,p_team_entry_id,p_payout_id,p_placement,p_amount_minor,p_voided,p_reason)::text,'utf8'),'sha256'),'hex'); perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('side-pool-team-payout:'||p_pool_id,0)); select * into prior from app.operation_receipts where actor_profile_id=p_actor_id and client_operation_id=p_idempotency_key; if found then return prior.response_payload; end if;
 select coalesce(sum(x.amount_received_minor),0) into collected from (select distinct on(participant_id) amount_received_minor,elected from app.event_side_pool_election_versions where pool_id=p_pool_id order by participant_id,version desc) x where elected; select collected+coalesce(sum(x.amount_received_minor),0) into collected from (select distinct on(team_entry_id) amount_received_minor,elected from app.event_side_pool_team_election_versions where pool_id=p_pool_id order by team_entry_id,version desc) x where elected;
 select coalesce(sum(x.amount_minor),0) into paid from (select distinct on(payout_id) amount_minor,voided from app.event_side_pool_payout_versions where pool_id=p_pool_id order by payout_id,version desc) x where not voided; select paid+coalesce(sum(x.amount_minor),0) into paid from (select distinct on(payout_id) amount_minor,voided from app.event_side_pool_team_payout_versions where pool_id=p_pool_id order by payout_id,version desc) x where not voided; if not p_voided and paid+p_amount_minor>collected then return jsonb_build_object('status','rejected','code','payout_exceeds_collected'); end if;
 select coalesce(max(version),0)+1 into v from app.event_side_pool_team_payout_versions where payout_id=p_payout_id; response:=jsonb_build_object('status','side_pool_team_payout_recorded','poolId',p_pool_id,'teamEntryId',p_team_entry_id,'payoutId',p_payout_id,'version',v,'amountMinor',p_amount_minor,'voided',p_voided); insert into app.operation_receipts(id,actor_profile_id,tournament_id,operation_type,target_id,request_hash,client_operation_id,outcome,response_payload,applied_at) values(rid,p_actor_id,p_tournament_id,'set_event_side_pool_team_payout_v1',p_payout_id,h,p_idempotency_key,'accepted',response,clock_timestamp()); insert into app.event_side_pool_team_payout_versions(payout_id,pool_id,tournament_id,event_id,team_entry_id,version,placement,amount_minor,voided,reason,actor_profile_id,operation_receipt_id) values(p_payout_id,p_pool_id,p_tournament_id,p_event_id,p_team_entry_id,v,p_placement,p_amount_minor,p_voided,trim(p_reason),p_actor_id,rid); return response;
end $$;
revoke all on function public.set_event_side_pool_team_payout_v1(uuid,uuid,uuid,uuid,uuid,uuid,integer,integer,boolean,text,uuid) from public,anon,authenticated; grant execute on function public.set_event_side_pool_team_payout_v1(uuid,uuid,uuid,uuid,uuid,uuid,integer,integer,boolean,text,uuid) to service_role;

-- Reconciliation is blocked unless every current payout (singles or teams) has
-- an approved, independent review and combined cents reconcile exactly.
create or replace function app.check_side_pool_reconciliation_v2() returns trigger language plpgsql security definer set search_path='' as $$
declare expected integer; paid integer;
begin
 select coalesce(sum(x.amount_received_minor),0) into expected from (select distinct on(participant_id) amount_received_minor,elected from app.event_side_pool_election_versions where pool_id=new.pool_id order by participant_id,version desc) x where x.elected;
 select expected+coalesce(sum(x.amount_received_minor),0) into expected from (select distinct on(team_entry_id) amount_received_minor,elected from app.event_side_pool_team_election_versions where pool_id=new.pool_id order by team_entry_id,version desc) x where x.elected;
 select coalesce(sum(x.amount_minor),0) into paid from (select distinct on(payout_id) payout_id,amount_minor,voided from app.event_side_pool_payout_versions where pool_id=new.pool_id order by payout_id,version desc) x where not x.voided;
 select paid+coalesce(sum(x.amount_minor),0) into paid from (select distinct on(payout_id) payout_id,amount_minor,voided from app.event_side_pool_team_payout_versions where pool_id=new.pool_id order by payout_id,version desc) x where not x.voided;
 if expected<>paid then raise exception 'side_pool_combined_unreconciled'; end if;
 if exists(select 1 from (select payout_id,'participant' beneficiary_kind from app.event_side_pool_payout_versions where pool_id=new.pool_id and not voided union select payout_id,'team_entry' from app.event_side_pool_team_payout_versions where pool_id=new.pool_id and not voided) p where not exists(select 1 from app.event_side_pool_payout_reviews r where r.payout_id=p.payout_id and r.beneficiary_kind=p.beneficiary_kind and r.approved and r.reviewer_profile_id<>new.actor_profile_id)) then raise exception 'side_pool_payout_review_required'; end if;
 return new;
end $$;
create trigger event_side_pool_reconciliation_team_guard before insert on app.event_side_pool_reconciliations for each row execute function app.check_side_pool_reconciliation_v2();
notify pgrst,'reload schema';
