-- A desk official may record a presence check-in only after the existing
-- roster, payment-obligation, and event-enrollment boundaries say the player
-- is ready. This is deliberately not a shortcut around cash/check evidence.

create or replace function public.desk_check_in_event_v1(
  p_actor_id uuid,p_tournament_id uuid,p_event_id uuid,p_roster_entry_id uuid,p_idempotency_key uuid
) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_hash text;v_existing app.operation_receipts%rowtype;v_receipt uuid;v_version integer;v_response jsonb;
begin
 if p_actor_id is null or p_tournament_id is null or p_event_id is null or p_roster_entry_id is null or p_idempotency_key is null then return jsonb_build_object('status','rejected','code','invalid_request');end if;
 if not exists(select 1 from app.tournament_roles r where r.tournament_id=p_tournament_id and r.profile_id=p_actor_id and r.role in('director','co_director')) then return jsonb_build_object('status','rejected','code','not_director');end if;
 if not exists(select 1 from app.event_check_in_windows w where w.tournament_id=p_tournament_id and w.event_id=p_event_id and w.state='open') then return jsonb_build_object('status','rejected','code','window_not_open');end if;
 if not exists(select 1 from app.tournament_roster_entries r left join lateral(select l.event_type from app.roster_entry_lifecycle_events l where l.roster_entry_id=r.id order by l.version desc limit 1) lifecycle on true where r.id=p_roster_entry_id and r.tournament_id=p_tournament_id and coalesce(lifecycle.event_type,'active')<>'withdrawn') then return jsonb_build_object('status','rejected','code','roster_entry_unavailable');end if;
 if not app.event_qr_player_is_paid_and_enrolled(p_tournament_id,p_event_id,p_roster_entry_id) then return jsonb_build_object('status','rejected','code','payment_or_enrollment_required');end if;
 v_hash:=encode(extensions.digest(convert_to(jsonb_build_array('desk_check_in_event_v1',p_tournament_id::text,p_event_id::text,p_roster_entry_id::text)::text,'utf8'),'sha256'),'hex');perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_actor_id::text||':'||p_idempotency_key::text,0));select * into v_existing from app.operation_receipts where actor_profile_id=p_actor_id and client_operation_id=p_idempotency_key;if found then if v_existing.request_hash=v_hash then return v_existing.response_payload;else return jsonb_build_object('status','rejected','code','idempotency_conflict');end if;end if;
 if exists(select 1 from app.event_check_in_events e where e.event_id=p_event_id and e.roster_entry_id=p_roster_entry_id and e.state='checked_in') then return jsonb_build_object('status','already_checked_in','eventId',p_event_id,'rosterEntryId',p_roster_entry_id);end if;
 select coalesce(max(version),0)+1 into v_version from app.event_check_in_events where event_id=p_event_id and roster_entry_id=p_roster_entry_id for update;
 v_response:=jsonb_build_object('status','checked_in','eventId',p_event_id,'rosterEntryId',p_roster_entry_id,'source','desk');insert into app.operation_receipts(tournament_id,actor_profile_id,operation_type,target_id,request_hash,client_operation_id,outcome,response_payload,applied_at)values(p_tournament_id,p_actor_id,'desk_check_in_event_v1',p_roster_entry_id,v_hash,p_idempotency_key,'accepted',v_response,now())returning id into v_receipt;
 insert into app.event_check_in_events(tournament_id,event_id,roster_entry_id,version,state,source,actor_profile_id,operation_receipt_id)values(p_tournament_id,p_event_id,p_roster_entry_id,v_version,'checked_in','desk',p_actor_id,v_receipt);
 update app.event_check_in_requests set request_state='checked_in',resolved_at=now(),resolved_by_profile_id=p_actor_id where event_id=p_event_id and roster_entry_id=p_roster_entry_id and request_state='pending_desk';
 insert into app.audit_events(tournament_id,actor_profile_id,operation_receipt_id,entity_type,entity_id,action,after_state)values(p_tournament_id,p_actor_id,v_receipt,'event_check_in',p_roster_entry_id,'event_check_in_recorded_at_desk',v_response);return v_response;
end $$;

create or replace function public.get_event_check_in_workspace_v1(p_actor_id uuid,p_tournament_id uuid)
returns jsonb language sql stable security definer set search_path='' as $$
 select case when exists(select 1 from app.tournament_roles r where r.tournament_id=p_tournament_id and r.profile_id=p_actor_id and r.role in('director','co_director')) then jsonb_build_object(
  'events',coalesce((select jsonb_agg(jsonb_build_object('eventId',e.id,'name',e.name,'eventType',e.event_type,'format',e.format,'windowState',coalesce(w.state,'closed'),'checkedInCount',coalesce((select count(*) from app.event_check_in_events x where x.event_id=e.id and x.state='checked_in'),0),'pendingDeskCount',coalesce((select count(*) from app.event_check_in_requests q where q.event_id=e.id and q.request_state='pending_desk'),0)) order by v.ordinal) from app.tournament_setup_activations a join app.events e on e.id=a.event_id and e.tournament_id=a.tournament_id join app.tournament_setup_event_versions v on v.id=a.setup_event_version_id left join app.event_check_in_windows w on w.event_id=e.id where a.tournament_id=p_tournament_id),'[]'::jsonb),
  'requests',coalesce((select jsonb_agg(jsonb_build_object('requestId',q.id,'eventId',q.event_id,'rosterEntryId',q.roster_entry_id,'firstName',q.requested_first_name,'lastName',q.requested_last_name,'email',q.requested_email,'accNumber',q.requested_acc_number,'createdAt',q.created_at) order by q.created_at desc) from app.event_check_in_requests q where q.tournament_id=p_tournament_id and q.request_state='pending_desk'),'[]'::jsonb),
  'roster',coalesce((select jsonb_agg(jsonb_build_object('rosterEntryId',r.id,'displayName',r.claimed_display_name,'accNumber',r.claimed_acc_number,'eventIds',coalesce((select jsonb_agg(p.event_id) from app.event_participants p where p.tournament_id=r.tournament_id and p.roster_entry_id=r.id),'[]'::jsonb),'paid',exists(select 1 from lateral(select x.amount_owed_minor from app.roster_payment_obligation_versions x where x.roster_entry_id=r.id order by x.version desc limit 1)owed left join lateral(select x.amount_minor from app.roster_payment_events x where x.roster_entry_id=r.id order by x.version desc limit 1)received on true where coalesce(received.amount_minor,0)>=owed.amount_owed_minor),'checkedInEventIds',coalesce((select jsonb_agg(x.event_id) from app.event_check_in_events x where x.roster_entry_id=r.id and x.state='checked_in'),'[]'::jsonb)) order by r.claimed_normalized_name,r.id)from app.tournament_roster_entries r left join lateral(select l.event_type from app.roster_entry_lifecycle_events l where l.roster_entry_id=r.id order by l.version desc limit 1)lifecycle on true where r.tournament_id=p_tournament_id and coalesce(lifecycle.event_type,'active')<>'withdrawn'),'[]'::jsonb)
 ) else null end
$$;
revoke all on function public.desk_check_in_event_v1(uuid,uuid,uuid,uuid,uuid) from public,anon,authenticated;
grant execute on function public.desk_check_in_event_v1(uuid,uuid,uuid,uuid,uuid) to service_role;
notify pgrst,'reload schema';
