-- Retired/replaced events remain immutable history, but they must never be
-- offered for event-day check-in or reopened through a direct API request.

create or replace function public.open_event_check_in_window_v1(
  p_actor_id uuid,p_tournament_id uuid,p_event_id uuid,p_idempotency_key uuid
) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_receipt uuid;v_hash text;v_existing app.operation_receipts%rowtype;v_version integer;v_response jsonb;
begin
  if p_actor_id is null or p_tournament_id is null or p_event_id is null or p_idempotency_key is null then return jsonb_build_object('status','rejected','code','invalid_request');end if;
  if not exists(select 1 from app.tournament_roles r where r.tournament_id=p_tournament_id and r.profile_id=p_actor_id and r.role in('director','co_director')) then return jsonb_build_object('status','rejected','code','not_director');end if;
  perform 1 from app.tournaments t where t.id=p_tournament_id and t.registration_status in('open','closed') for update;if not found then return jsonb_build_object('status','rejected','code','tournament_unavailable');end if;
  perform 1 from app.events e where e.id=p_event_id and e.tournament_id=p_tournament_id and e.operational_state='active' and exists(select 1 from app.tournament_setup_activations a where a.tournament_id=e.tournament_id and a.event_id=e.id);if not found then return jsonb_build_object('status','rejected','code','event_unavailable');end if;
  if app.event_play_state_v1(p_event_id) in ('in_progress','completed','finalized') then return jsonb_build_object('status','rejected','code','event_already_started');end if;
  if exists(select 1 from app.events e where e.id=p_event_id and e.event_type='consolation') and not exists(select 1 from app.qualification_result_versions q join app.events main on main.id=q.event_id where q.tournament_id=p_tournament_id and main.event_type='main') then return jsonb_build_object('status','rejected','code','consolation_not_eligible');end if;
  v_hash:=encode(extensions.digest(convert_to(jsonb_build_array('open_event_check_in_window_v1',p_tournament_id::text,p_event_id::text)::text,'utf8'),'sha256'),'hex');
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_actor_id::text||':'||p_idempotency_key::text,0));
  select * into v_existing from app.operation_receipts where actor_profile_id=p_actor_id and client_operation_id=p_idempotency_key;if found then if v_existing.request_hash=v_hash then return v_existing.response_payload;else return jsonb_build_object('status','rejected','code','idempotency_conflict');end if;end if;
  if exists(select 1 from app.event_check_in_windows where event_id=p_event_id and state='open') then return jsonb_build_object('status','rejected','code','window_already_open');end if;
  select coalesce((select version from app.event_check_in_windows where event_id=p_event_id for update),0)+1 into v_version;
  v_response:=jsonb_build_object('status','event_check_in_opened','eventId',p_event_id,'version',v_version,'reopened',v_version>1);
  insert into app.operation_receipts(tournament_id,actor_profile_id,operation_type,target_id,request_hash,client_operation_id,outcome,response_payload,applied_at) values(p_tournament_id,p_actor_id,'open_event_check_in_window_v1',p_event_id,v_hash,p_idempotency_key,'accepted',v_response,now()) returning id into v_receipt;
  insert into app.event_check_in_windows(event_id,tournament_id,state,opened_at,opened_by_profile_id,version) values(p_event_id,p_tournament_id,'open',now(),p_actor_id,v_version) on conflict(event_id) do update set state='open',opened_at=excluded.opened_at,opened_by_profile_id=excluded.opened_by_profile_id,closed_at=null,closed_by_profile_id=null,version=excluded.version;
  insert into app.audit_events(tournament_id,actor_profile_id,operation_receipt_id,entity_type,entity_id,action,after_state) values(p_tournament_id,p_actor_id,v_receipt,'event_check_in_window',p_event_id,case when v_version>1 then 'event_check_in_reopened' else 'event_check_in_opened' end,v_response);return v_response;
end $$;

create or replace function public.get_event_check_in_workspace_v1(p_actor_id uuid,p_tournament_id uuid)
returns jsonb language sql stable security definer set search_path='' as $$
 select case when exists(select 1 from app.tournament_roles r where r.tournament_id=p_tournament_id and r.profile_id=p_actor_id and r.role in('director','co_director')) then jsonb_build_object(
  'events',coalesce((select jsonb_agg(jsonb_build_object('eventId',e.id,'name',e.name,'eventType',e.event_type,'format',e.format,'playState',app.event_play_state_v1(e.id),'windowState',coalesce(w.state,'closed'),'checkedInCount',(select count(*) from app.event_participants p left join lateral(select x.state from app.event_check_in_events x where x.event_id=p.event_id and x.roster_entry_id=p.roster_entry_id order by x.version desc limit 1)latest on true where p.event_id=e.id and latest.state='checked_in'),'noShowCount',(select count(*) from app.event_participants p left join lateral(select x.state from app.event_check_in_events x where x.event_id=p.event_id and x.roster_entry_id=p.roster_entry_id order by x.version desc limit 1)latest on true where p.event_id=e.id and latest.state='no_show'),'unresolvedCount',app.event_attendance_unresolved_count_v1(e.id),'pendingDeskCount',coalesce((select count(*) from app.event_check_in_requests q where q.event_id=e.id and q.request_state='pending_desk'),0)) order by v.ordinal) from app.tournament_setup_activations a join app.events e on e.id=a.event_id and e.tournament_id=a.tournament_id and e.operational_state='active' join app.tournament_setup_event_versions v on v.id=a.setup_event_version_id left join app.event_check_in_windows w on w.event_id=e.id where a.tournament_id=p_tournament_id),'[]'::jsonb),
  'requests',coalesce((select jsonb_agg(jsonb_build_object('requestId',q.id,'eventId',q.event_id,'rosterEntryId',q.roster_entry_id,'firstName',q.requested_first_name,'lastName',q.requested_last_name,'email',q.requested_email,'accNumber',q.requested_acc_number,'createdAt',q.created_at) order by q.created_at desc) from app.event_check_in_requests q join app.events e on e.id=q.event_id and e.tournament_id=q.tournament_id and e.operational_state='active' where q.tournament_id=p_tournament_id and q.request_state='pending_desk'),'[]'::jsonb),
  'roster',coalesce((select jsonb_agg(jsonb_build_object('rosterEntryId',r.id,'displayName',r.claimed_display_name,'accNumber',r.claimed_acc_number,'events',coalesce((select jsonb_agg(jsonb_build_object('eventId',p.event_id,'participantStatus',p.status,'attendanceState',coalesce(latest.state,'unresolved')) order by p.event_id) from app.event_participants p join app.events e on e.id=p.event_id and e.tournament_id=p.tournament_id and e.operational_state='active' left join lateral(select x.state from app.event_check_in_events x where x.event_id=p.event_id and x.roster_entry_id=p.roster_entry_id order by x.version desc limit 1)latest on true where p.tournament_id=r.tournament_id and p.roster_entry_id=r.id),'[]'::jsonb),'paid',coalesce(payment.event_type='received' and payment.amount_minor>=obligation.amount_owed_minor,false),'amountOwedMinor',coalesce(obligation.amount_owed_minor,0),'amountReceivedMinor',case when payment.event_type='received' then payment.amount_minor else 0 end,'paymentMethod',case when payment.event_type='received' then payment.payment_method else null end) order by r.claimed_normalized_name,r.id) from app.tournament_roster_entries r left join lateral(select l.event_type from app.roster_entry_lifecycle_events l where l.roster_entry_id=r.id order by l.version desc limit 1)lifecycle on true left join lateral(select x.amount_owed_minor from app.roster_payment_obligation_versions x where x.roster_entry_id=r.id order by x.version desc limit 1)obligation on true left join lateral(select x.event_type,x.amount_minor,x.payment_method from app.roster_payment_events x where x.roster_entry_id=r.id order by x.version desc limit 1)payment on true where r.tournament_id=p_tournament_id and coalesce(lifecycle.event_type,'active')<>'withdrawn'),'[]'::jsonb)
 ) else null end
$$;

revoke all on function public.open_event_check_in_window_v1(uuid,uuid,uuid,uuid) from public,anon,authenticated;
revoke all on function public.get_event_check_in_workspace_v1(uuid,uuid) from public,anon,authenticated;
grant execute on function public.open_event_check_in_window_v1(uuid,uuid,uuid,uuid) to service_role;
grant execute on function public.get_event_check_in_workspace_v1(uuid,uuid) to service_role;

notify pgrst,'reload schema';
