"use client";

import Image from "next/image";
import { useMemo, useState } from "react";
import { deriveScore, formatSignedNet, isScoreEntryReady } from "../lib/score";

const keypad = [1, 2, 3, 4, 5, 6, 7, 8, 9, "clear", 0, "backspace"] as const;
const eventGames = 12;
type Screen = "score" | "review" | "card" | "operations" | "setup" | "players" | "seating" | "tablePlan" | "playThrough" | "corrections" | "judge" | "flyer" | "flyerEditor" | "flyerPreview" | "finance" | "results" | "qualifiers" | "rulebook" | "rulebookQuick";
type SeatingSort = "first" | "last" | "card" | "table";
const configuredEvents = ["Main", "Consy", "Canadian Doubles", "Topaz Satellite"];

const seatingAssignments = [
  { first: "Alex", last: "Morgan", card: "Paper", table: "A", seat: 5, id: "C-2" },
  { first: "Barb", last: "Stevens", card: "Digital", table: "A", seat: 7, id: "A-7" },
  { first: "Robin", last: "Lee", card: "Paper", table: "B", seat: 3, id: "B-3" },
  { first: "Steve", last: "Hall", card: "Digital", table: "A", seat: 8, id: "A-8" },
];

function Context() { return <p className="context">Grass Roots · Honolulu, HI<br />Apr. 25, 2025 · Main ({eventGames} games)</p>; }
function Skunk({ level }: { level: 0 | 1 | 2 | 3 }) { if (!level) return null; return <span className="skunk" role="status">{"🦨".repeat(level)} {level === 1 ? "Skunk" : level === 2 ? "Double skunk" : "Triple skunk"}</span>; }
function Heading({ label, title, children }: { label: string; title: string; children?: React.ReactNode }) { return <header className="heading"><div><p className="eyebrow">{label}</p><h1>{title}</h1></div>{children ?? <Context />}</header>; }

export function TournamentDashboard() {
  const [screen, setScreen] = useState<Screen>("score");
  const [winner, setWinner] = useState<"player" | "opponent" | null>(null);
  const [marginText, setMarginText] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [tables, setTables] = useState(6);
  const [seatsPerTable, setSeatsPerTable] = useState(8);
  const [seatingSort, setSeatingSort] = useState<SeatingSort>("table");
  const [seatingSearch, setSeatingSearch] = useState("");
  const [resultsEvent, setResultsEvent] = useState("Main");
  const margin = Number(marginText);
  const score = useMemo(() => { if (!isScoreEntryReady(margin, winner)) return null; try { return deriveScore(margin, winner); } catch { return null; } }, [margin, winner]);
  const winnerName = winner === "player" ? "Barb Stevens" : "Steve Hall";
  const loserName = winner === "player" ? "Steve Hall" : "Barb Stevens";
  const winnerPoints = winner === "player" ? score?.playerGamePoints : score?.opponentGamePoints;
  const loserPoints = winner === "player" ? score?.opponentGamePoints : score?.playerGamePoints;
  const choose = (value: "player" | "opponent") => { setWinner(value); setSubmitted(false); };
  const key = (value: (typeof keypad)[number]) => { setSubmitted(false); if (value === "clear") return setMarginText(""); if (value === "backspace") return setMarginText((old) => old.slice(0, -1)); setMarginText((old) => old.length >= 3 ? old : old === "0" ? String(value) : `${old}${value}`); };
  const nav = (["score", "card", "operations", "results", "rulebook"] as const);
  const visibleAssignments = seatingAssignments
    .filter(({ first, last }) => `${first} ${last}`.toLowerCase().includes(seatingSearch.toLowerCase().trim()))
    .sort((left, right) => {
      if (seatingSort === "first") return left.first.localeCompare(right.first);
      if (seatingSort === "last") return left.last.localeCompare(right.last);
      if (seatingSort === "card") return left.card.localeCompare(right.card) || left.last.localeCompare(right.last);
      return left.table.localeCompare(right.table) || left.seat - right.seat;
    });

  const resultRows = score && <div className="result-rows"><div><strong>{winnerName} won by {score.margin}</strong><dl><div><dt>Game Points</dt><dd>{winnerPoints}</dd></div><div><dt>Spread Points</dt><dd>+{score.margin}</dd></div></dl></div><div><strong>{loserName} lost by {score.margin}</strong><dl><div><dt>Game Points</dt><dd>{loserPoints}</dd></div><div><dt>Spread Points</dt><dd>-{score.margin}</dd></div></dl></div></div>;

  return <main className="shell">
    <header className="topbar"><div className="brand"><Image className="brand-logo" src="/branding/acc-logo.jpg" alt="American Cribbage Congress logo" width={1080} height={510} priority /><div><strong>AMERICAN<br />CRIBBAGE CONGRESS</strong><small>TOURNAMENT DESK</small></div></div><div className="top-meta"><b>GAME 3</b><span>Grass Roots · April 25, 2025</span></div></header>
    <nav className="nav" aria-label="Tournament sections">{nav.map((item) => <button type="button" key={item} className={screen === item || (screen === "review" && item === "score") ? "active" : ""} aria-current={screen === item ? "page" : undefined} onClick={() => setScreen(item)}>{item === "score" ? "Score Entry" : item === "card" ? "Scorecard" : item === "rulebook" ? "Rulebook" : item[0].toUpperCase() + item.slice(1)}</button>)}</nav>
    <div className="content">
      {screen === "score" && <section className="panel score"><Heading label="SCORE ENTRY" title="Current Game Results"><Context /></Heading><div className="matchup"><div><span>Player</span><strong>Barb Stevens <em>(ID#: A-7)</em></strong><small>Table A · Seat 7</small></div><b>VS</b><div><span>Opponent</span><strong>Steve Hall <em>(ID#: A-8)</em></strong><small>Table A · Seat 8</small></div></div><fieldset><legend>Game Winner:</legend><button type="button" className={winner === "player" ? "pick selected" : "pick"} aria-pressed={winner === "player"} onClick={() => choose("player")}>Barb won</button><button type="button" className={winner === "opponent" ? "pick selected" : "pick"} aria-pressed={winner === "opponent"} onClick={() => choose("opponent")}>Steve won</button></fieldset><div className="entry"><label htmlFor="margin">Spread Points:</label><output id="margin" className={score ? "number" : "number invalid"}>{marginText || "—"}</output><Skunk level={score?.skunkLevel ?? 0} /></div><div className="keypad" aria-label="Spread points keypad">{keypad.map((value) => <button type="button" key={value} onClick={() => key(value)} aria-label={value === "clear" ? "Clear spread points" : value === "backspace" ? "Delete last digit" : `Enter ${value}`}>{value === "clear" ? "Clear" : value === "backspace" ? "⌫" : value}</button>)}</div><div className="result">{resultRows ?? <p>{winner ? (marginText ? "Enter a possible spread point number." : "Enter spread points.") : "Choose the winner to begin score entry."}</p>}</div><button type="button" className="primary full" disabled={!score} onClick={() => setScreen("review")}>Review Result</button></section>}
      {screen === "review" && <section className="panel review"><Heading label="SCORE ENTRY" title="Review Current Game Result"><Context /></Heading>{score ? <><p className="game-line">Game 3 · Barb: Table A / Seat 7 · Steve: Table A / Seat 8</p><div className="review-cards">{resultRows}</div><Skunk level={score.skunkLevel} /><div className="actions"><button type="button" className="secondary" onClick={() => setScreen("score")}>Edit Result</button><button type="button" className="primary" onClick={() => setSubmitted(true)}>{submitted ? "Entry Submitted" : "Submit My Entry"}</button></div>{submitted && <p className="status" role="status">Your entry is waiting for Steve’s independent entry.</p>}</> : <p>Return to Score Entry to enter this result.</p>}</section>}
      {screen === "card" && <section className="panel card"><Heading label="SCORECARD" title="Barb Stevens, HI-296"><div className="card-state"><p className="seat">ID #<strong>A-7</strong></p><strong className={submitted ? "verification-pending" : "verification-current"}>{submitted ? "Verification Pending Opponent Entry" : "Current and Verified"}</strong></div></Heading><p className="card-context">Grass Roots · Honolulu, HI · Apr. 25, 2025 · Main ({eventGames} games)</p><Scorecard score={score} pending={submitted} /></section>}
      {screen === "operations" && <section className="panel operations"><Heading label="TOURNAMENT OPERATIONS" title="Grass Roots"><Context /></Heading><div className="option-grid"><button type="button" onClick={() => setScreen("setup")}><b>⚙</b><strong>Tournament Setup</strong><span>Dates, venue, rules, and capacity</span></button><button type="button" onClick={() => setScreen("players")}><b>♙</b><strong>Players & Check-In</strong><span>Roster and scorecard type</span></button><button type="button" onClick={() => setScreen("seating")}><b>⌘</b><strong>Seating</strong><span>Seating Assignments and Table Plan</span></button><button type="button" onClick={() => setScreen("corrections")}><b>♢</b><strong>Cross Check</strong><span>Review scorecards and corrections</span></button><button type="button" onClick={() => setScreen("judge")}><b>⚖</b><strong>Judge Desk</strong><span>Rules and disputes</span></button><button type="button" onClick={() => setScreen("flyer")}><b>✦</b><strong>Flyer & Events</strong><span>Main, Consy, and Satellites</span></button><button type="button" onClick={() => setScreen("finance")}><b>$</b><strong>Financials</strong><span>Fees, pools, expenses, and results</span></button></div></section>}
      {screen === "setup" && <Feature label="OPERATIONS" title="Tournament Setup" back={() => setScreen("operations")} action="Save Tournament Setup"><List rows={[["Tournament", "Grass Roots · Honolulu, HI", "April 25, 2025"], ["Layout", `${tables} tables · ${seatsPerTable} seats each`, `${tables * seatsPerTable} seats`], ["Events", configuredEvents.join(" · "), "Configure"], ["Staff", "Director · Co-directors (repeatable)", "Configure"]]} /></Feature>}
      {screen === "players" && <Feature label="OPERATIONS" title="Players & Check-In" back={() => setScreen("operations")} action="Close Registration & Assign Seating"><p className="registration-note">Table/Seat and permanent verification IDs are generated only after registration closes.</p><List rows={[["Barb Stevens", "Digital scorecard · Checked in", "Awaiting assignment"], ["Steve Hall", "Digital scorecard · Checked in", "Awaiting assignment"], ["Robin Lee", "Paper scorecard · Checked in", "Awaiting assignment"], ["Alex Morgan", "Paper scorecard · Checked in", "Awaiting assignment"]]} /></Feature>}
      {screen === "seating" && <section className="panel feature"><Heading label="OPERATIONS" title="Seating" /><div className="seating-actions"><button type="button" className="secondary" onClick={() => setScreen("operations")}>Back to Operations</button><button type="button" className="secondary" onClick={() => setScreen("tablePlan")}>Table Plan</button><button type="button" className="primary" onClick={() => window.print()}>Print Seating List</button></div><div className="seating-setup"><label>Tables<input type="number" min="1" value={tables} onChange={(event) => setTables(Math.max(1, Number(event.target.value) || 1))} /></label><label>Seats per table<input type="number" min="2" value={seatsPerTable} onChange={(event) => setSeatsPerTable(Math.max(2, Number(event.target.value) || 2))} /></label><p><strong>{tables * seatsPerTable}</strong> seats available</p></div><div className="seating-tools"><label className="search">Search player name<input type="search" value={seatingSearch} onChange={(event) => setSeatingSearch(event.target.value)} placeholder="Find a player" /></label><div className="sort-controls" aria-label="Sort seating assignments"><span>Sort by</span>{([ ["first", "First name"], ["last", "Last name"], ["card", "Scorecard type"], ["table", "Table/seat"] ] as const).map(([value, label]) => <button type="button" key={value} className={seatingSort === value ? "selected" : ""} onClick={() => setSeatingSort(value)}>{label}</button>)}</div></div><div className="seating-list" aria-live="polite"><div className="seating-list-head"><span>Player</span><span>Scorecard</span><span>Assigned Table - Seat</span></div>{visibleAssignments.map(({ first, last, card, table, seat, id }) => <div key={id}><strong>{first} {last}</strong><span>{card}</span><b>{table}-{seat}</b></div>)}{visibleAssignments.length === 0 && <p>No player found.</p>}</div><PrintableSeatingList assignments={visibleAssignments} /></section>}
      {screen === "tablePlan" && <Feature label="SEATING" title="Table Plan" back={() => setScreen("seating")} backLabel="Previous Screen" action="Review Table C Constraints" actionClick={() => setScreen("playThrough")}><List rows={[["Table A", "2 assigned · Sample roster", "Review"], ["Table B", "1 assigned · Sample roster", "Review"], ["Table C / Last Table", "1 assigned · Example exception", "Review"]]} /></Feature>}
      {screen === "playThrough" && <Feature label="SEATING" title="Table C Exception Review" back={() => setScreen("tablePlan")} backLabel="Previous Screen" action="Record Director Note"><List rows={[["Table C", "Example exception only", "Draft"], ["Affected players", "Player, opponent, and playing table", "Director enters"], ["ACC rotation fixture", "Required before official schedule", "Not configured"]]} /></Feature>}
      {screen === "corrections" && <Feature label="CROSS CHECK" title="Scorecard Review" back={() => setScreen("operations")} action="Open Selected Card"><List rows={[["Table A · Game 3", "Barb Stevens / Steve Hall", "Waiting for opponent entry"], ["Table C · Game 2", "Jordan Patel / Casey Kim", "Correction applied"]]} /></Feature>}
      {screen === "judge" && <Feature label="JUDGE DESK" title="Rules & Disputes" back={() => setScreen("operations")} action="Open Rulebook"><List rows={[["Open disputes", "No active disputes", "0"], ["Rulebook", "Tournament rules", "Open"], ["Judge assignments", "Table coverage", "View"]]} /></Feature>}
      {screen === "flyer" && <section className="panel feature"><Heading label="FLYER & EVENTS" title="Tournament Events" /><div className="actions"><button type="button" className="secondary" onClick={() => setScreen("operations")}>Back to Operations</button><button type="button" className="primary" onClick={() => setScreen("flyerEditor")}>Create Flyer</button></div><List rows={[["Main", "12 games · April 25", "Edit event"], ["Consy", "9 games · April 25", "Edit event"], ["Canadian Doubles", "Team scorecard configuration", "Edit event"], ["Topaz Satellite", "Custom satellite event", "Edit event"]]} /></section>}
      {screen === "flyerEditor" && <Feature label="FLYER & EVENTS" title="Tournament Flyer" back={() => setScreen("flyer")} backLabel="Previous Screen" action="Preview Flyer" actionClick={() => setScreen("flyerPreview")}><List rows={[["Tournament", "Grass Roots · Honolulu, HI", "April 25, 2025"], ["Events", configuredEvents.join(" · "), "4 events"], ["Sanctioning", "ACC Sanctioning Fee", "Financials"], ["Results", "Placements · Qualifiers · Q Pool", "Post-event"]]} /></Feature>}
      {screen === "flyerPreview" && <section className="panel flyer-preview"><div className="actions"><button type="button" className="secondary" onClick={() => setScreen("flyerEditor")}>Previous Screen</button></div><p className="eyebrow">ACC TOURNAMENT FLYER</p><h1>Grass Roots</h1><p className="flyer-place">Honolulu, Hawaii · April 25, 2025</p><div className="flyer-events"><section><h2>Main</h2><p>12 games · Registration and schedule details</p></section><section><h2>Consy</h2><p>9 games · Consolation event details</p></section><section><h2>Canadian Doubles</h2><p>Team event · Team registration and format details</p></section><section><h2>Topaz Satellite</h2><p>Custom satellite · Event details</p></section></div><p className="flyer-footer">ACC Sanctioning Fee · Prize and Q Pool details are configured before publishing.</p></section>}
      {screen === "finance" && <Feature label="FINANCIALS" title="Tournament Financials" back={() => setScreen("operations")} action="Add Expense"><div className="money"><div><span>Registration received</span><b>$1,200.00</b></div><div><span>ACC Sanctioning Fee</span><b>$120.00</b></div><div><span>Prize pool</span><b>$960.00</b></div><div><span>Unreconciled</span><b>$0.00</b></div></div></Feature>}
      {screen === "results" && <section className="panel results"><Heading label="RESULTS" title="Tournament Results" /><div className="event-tabs" aria-label="Tournament event results">{configuredEvents.map((event) => <button type="button" key={event} className={resultsEvent === event ? "selected" : ""} onClick={() => setResultsEvent(event)}>{event}</button>)}</div><div className="results-head"><div><span>{resultsEvent}</span><strong>Results not published</strong></div><button type="button" className="secondary" onClick={() => setScreen("qualifiers")}>View Qualifiers</button></div><List rows={[["Winner", "—", "—"], ["Runner-up", "—", "—"], ["High Non-Qualifier", "—", "—"]]} /></section>}
      {screen === "qualifiers" && <section className="panel results"><Heading label="RESULTS" title={`${resultsEvent} Qualification Preview`} /><div className="results-head"><div><span>Current qualification setup</span><strong>Not yet finalized</strong></div><a className="primary pdf-link" href="/sample/qualifiers-summary.pdf" target="_blank">Open Main Sample PDF</a></div><List rows={[["Winner", "Shown after event finalization", "—"], ["Runner-up", "Shown after event finalization", "—"], ["High Non-Qualifier", "Shown after event finalization", "—"], ["Qualifiers", "Name · MRP · Q Pool award", "Configure"], ["Q Pool", "Amount received to date", "$0.00"]]} /></section>}
      {screen === "rulebook" && <section className="panel results"><Heading label="REFERENCE" title="ACC Rulebook" /><List rows={[["ACC Quick Reference", "App-organized tournament reference", "Open"], ["ACC Tournament Rules", "2025 edition · cached Sep. 7, 2026", "Open"]]} /><div className="actions"><button type="button" className="secondary" onClick={() => setScreen("rulebookQuick")}>Open Quick Reference</button><a className="primary pdf-link" href="/rulebook/acc-rulebook-2025.pdf" target="_blank">Open Full ACC Rulebook</a><a className="secondary pdf-link" href="https://www.cribbage.org/NewSite/rules/rulebook_2025.pdf" target="_blank">Official ACC Source</a></div></section>}
      {screen === "rulebookQuick" && <Feature label="REFERENCE" title="ACC Quick Reference" back={() => setScreen("rulebook")} backLabel="Previous Screen" action="Open Full Rulebook"><List rows={[["Tournament Rules", "Use the dated full ACC Rulebook for official text", "2025"], ["Cross-Checking", "Check assigned scorecards and record corrections", "Appendix A"], ["Judge Protocols", "Use the current dated source during a ruling", "Rules"], ["Playoffs & Byes", "Qualification and bracket reference", "ACC source"]]} /></Feature>}
    </div><footer><span>ACC Tournament Desk</span><span>Grass Roots · Honolulu, HI · April 25, 2025</span></footer>
  </main>;
}

function Feature({ label, title, action, actionClick, back, backLabel = "Back to Operations", children }: { label: string; title: string; action: string; actionClick?: () => void; back: () => void; backLabel?: string; children: React.ReactNode }) { return <section className="panel feature"><Heading label={label} title={title} /><div className="actions"><button type="button" className="secondary" onClick={back}>{backLabel}</button><button type="button" className="primary" onClick={actionClick}>{action}</button></div>{children}</section>; }
function List({ rows }: { rows: string[][] }) { return <div className="list">{rows.map((row) => <div key={row.join("|")}><strong>{row[0]}</strong><span>{row[1]}</span><b>{row[2]}</b></div>)}</div>; }

function Scorecard({ score, pending }: { score: ReturnType<typeof deriveScore> | null; pending: boolean }) {
  const columns = <colgroup><col className="game-number" /><col className="game-points" /><col className="spread-plus" /><col className="spread-minus" /><col className="opponent-name" /><col className="verification-id" /></colgroup>;
  const rows = Array.from({ length: eventGames }, (_, index) => {
    const number = index + 1;
    const saved = number === 1 ? [2, 10, "—", "Steve Hall", "A-8"] : number === 2 ? [2, 11, "—", "Robin Lee", "B-3"] : null;
    const current = number === 3;
    return <tr key={number} className={current ? "current" : undefined}><th scope="row">{number}</th><td>{current && score ? score.playerGamePoints : saved?.[0] ?? "—"}</td><td>{current && score ? score.playerPlus || "—" : saved?.[1] ?? "—"}</td><td>{current && score ? score.playerMinus || "—" : saved?.[2] ?? "—"}</td><td>{current ? "Steve Hall" : saved?.[3] ?? "—"}</td><td>{current ? "A-8" : saved?.[4] ?? "—"}</td></tr>;
  });
  return (
    <div className="scorecard-frame">
      <table className="scorecard-header"><caption className="sr-only">Barb Stevens digital scorecard</caption>{columns}<thead><tr><th colSpan={2} scope="colgroup">Game</th><th colSpan={2} scope="colgroup">Spread Points</th><th rowSpan={2} scope="col">Opponent<span>Name</span></th><th rowSpan={2} scope="col">Verification<span>ID #</span></th></tr><tr><th scope="col">#</th><th scope="col">Points</th><th scope="col">(+)</th><th scope="col">(−)</th></tr></thead></table>
      <div className="table-scroll"><table className="scorecard-body">{columns}<tbody>{rows}</tbody></table></div>
      <table className="scorecard-footer">{columns}<tbody>
        <tr><th>Total</th><td>4</td><td>+21</td><td>−0</td><td colSpan={2} className="total-pending-cell">{pending && <span role="status" aria-live="polite">Updated Total Calculations Pending Opponent Entry</span>}</td></tr>
        <tr className="summary-row"><td colSpan={2}><strong>2</strong> Games Won</td><td colSpan={2}><strong>{formatSignedNet(21)}</strong> Net Spread Points</td><td colSpan={2}></td></tr>
      </tbody></table>
    </div>
  );
}

function PrintableSeatingList({ assignments }: { assignments: typeof seatingAssignments }) {
  const columnSize = 28;
  const pageSize = columnSize * 2;
  const pages = Array.from({ length: Math.max(1, Math.ceil(assignments.length / pageSize)) }, (_, index) => assignments.slice(index * pageSize, (index + 1) * pageSize));
  const entry = ({ first, last, card, table, seat, id }: (typeof seatingAssignments)[number]) => <li key={id}><strong>{first} {last}</strong><span>{card}</span><span>{table}-{seat}</span></li>;
  const column = (entries: typeof seatingAssignments, start: number) => <div className="seating-print-column"><div className="seating-print-head"><span>Player</span><span>Scorecard</span><span>Assigned Table - Seat</span></div><ol start={start}>{entries.map(entry)}</ol></div>;
  return <section className="print-only seating-print">{pages.map((page, pageIndex) => <div className="seating-print-page" key={pageIndex}><h1>Seating Assignments</h1><div className="seating-print-columns">{column(page.slice(0, columnSize), pageIndex * pageSize + 1)}{column(page.slice(columnSize), pageIndex * pageSize + columnSize + 1)}</div></div>)}</section>;
}
