"use client";

import Image from "next/image";
import { useMemo, useState } from "react";
import { deriveScore, formatSignedNet, isScoreEntryReady } from "../lib/score";

const keypad = [1, 2, 3, 4, 5, 6, 7, 8, 9, "clear", 0, "backspace"] as const;
const eventGames = 12;
type Screen = "score" | "review" | "card" | "operations" | "seating" | "corrections" | "flyer" | "finance" | "results";

function Context() { return <p className="context">Grass Roots · Honolulu, HI<br />Apr. 25, 2025 · Main ({eventGames} games)</p>; }
function Skunk({ level }: { level: 0 | 1 | 2 | 3 }) { if (!level) return null; return <span className="skunk" role="status">{"🦨".repeat(level)} {level === 1 ? "Skunk" : level === 2 ? "Double skunk" : "Triple skunk"}</span>; }
function Heading({ label, title, children }: { label: string; title: string; children?: React.ReactNode }) { return <header className="heading"><div><p className="eyebrow">{label}</p><h1>{title}</h1></div>{children ?? <Context />}</header>; }

export function TournamentDashboard() {
  const [screen, setScreen] = useState<Screen>("score");
  const [winner, setWinner] = useState<"player" | "opponent" | null>(null);
  const [marginText, setMarginText] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const margin = Number(marginText);
  const score = useMemo(() => { if (!isScoreEntryReady(margin, winner)) return null; try { return deriveScore(margin, winner); } catch { return null; } }, [margin, winner]);
  const winnerName = winner === "player" ? "Barb Stevens" : "Steve Hall";
  const loserName = winner === "player" ? "Steve Hall" : "Barb Stevens";
  const winnerPoints = winner === "player" ? score?.playerGamePoints : score?.opponentGamePoints;
  const loserPoints = winner === "player" ? score?.opponentGamePoints : score?.playerGamePoints;
  const choose = (value: "player" | "opponent") => { setWinner(value); setSubmitted(false); };
  const key = (value: (typeof keypad)[number]) => { setSubmitted(false); if (value === "clear") return setMarginText(""); if (value === "backspace") return setMarginText((old) => old.slice(0, -1)); setMarginText((old) => old === "0" ? String(value) : `${old}${value}`); };
  const nav = (["score", "card", "operations", "results"] as const);

  const resultRows = score && <div className="result-rows"><div><strong>{winnerName} won by {score.margin}</strong><dl><div><dt>Game Points</dt><dd>{winnerPoints}</dd></div><div><dt>Spread Points</dt><dd>+{score.margin}</dd></div></dl></div><div><strong>{loserName} lost by {score.margin}</strong><dl><div><dt>Game Points</dt><dd>{loserPoints}</dd></div><div><dt>Spread Points</dt><dd>-{score.margin}</dd></div></dl></div></div>;

  return <main className="shell">
    <header className="topbar"><div className="brand"><Image className="brand-logo" src="/branding/acc-logo.jpg" alt="American Cribbage Congress logo" width={1080} height={510} priority /><div><strong>AMERICAN<br />CRIBBAGE CONGRESS</strong><small>TOURNAMENT DESK</small></div></div><div className="top-meta"><b>ROUND 3</b><span>Grass Roots · April 25, 2025</span></div></header>
    <nav className="nav" aria-label="Tournament sections">{nav.map((item) => <button type="button" key={item} className={screen === item || (screen === "review" && item === "score") ? "active" : ""} aria-current={screen === item ? "page" : undefined} onClick={() => setScreen(item)}>{item === "score" ? "Score Entry" : item === "card" ? "Scorecard" : item[0].toUpperCase() + item.slice(1)}</button>)}</nav>
    <div className="content">
      {screen === "score" && <section className="panel score" aria-labelledby="score-title"><Heading label="SCORE ENTRY" title="Current Game Results"><Context /></Heading><div className="matchup"><div><span>Player</span><strong>Barb Stevens</strong><small>Table A · Seat 7</small></div><b>VS</b><div><span>Opponent</span><strong>Steve Hall</strong><small>Table A · Seat 8</small></div></div><fieldset><legend>Game Winner:</legend><button type="button" className={winner === "player" ? "pick selected" : "pick"} aria-pressed={winner === "player"} onClick={() => choose("player")}>Barb won</button><button type="button" className={winner === "opponent" ? "pick selected" : "pick"} aria-pressed={winner === "opponent"} onClick={() => choose("opponent")}>Steve won</button></fieldset><div className="entry"><label htmlFor="margin">Spread Points</label><Skunk level={score?.skunkLevel ?? 0} /><output id="margin" className={score ? "number" : "number invalid"}>{marginText || "—"}</output></div><div className="keypad" aria-label="Spread points keypad">{keypad.map((value) => <button type="button" key={value} onClick={() => key(value)} aria-label={value === "clear" ? "Clear spread points" : value === "backspace" ? "Delete last digit" : `Enter ${value}`}>{value === "clear" ? "Clear" : value === "backspace" ? "⌫" : value}</button>)}</div><div className="result">{resultRows ?? <p>{winner ? "Enter a possible spread point number." : "Choose the winner to begin score entry."}</p>}</div><button type="button" className="primary full" disabled={!score} onClick={() => setScreen("review")}>Review Result</button></section>}
      {screen === "review" && <section className="panel review"><Heading label="SCORE ENTRY" title="Review Current Game Result"><Context /></Heading>{score ? <><p className="game-line">Game 3 · Table/Seat A-7 · Barb Stevens and Steve Hall</p><div className="review-cards">{resultRows}</div><Skunk level={score.skunkLevel} /><div className="actions"><button type="button" className="secondary" onClick={() => setScreen("score")}>Edit Result</button><button type="button" className="primary" onClick={() => setSubmitted(true)}>{submitted ? "Entry Submitted" : "Submit My Entry"}</button></div>{submitted && <p className="status" role="status">Your entry is waiting for Steve’s independent entry.</p>}</> : <p>Return to Score Entry to enter this result.</p>}</section>}
      {screen === "card" && <section className="panel card"><Heading label="SCORECARD" title="Barb Stevens, HI-296"><p className="seat">TABLE/SEAT<strong>A-7</strong></p></Heading><p className="card-context">Grass Roots · Honolulu, HI · Apr. 25, 2025 · Main ({eventGames} games)</p><div className="table-scroll"><table><caption className="sr-only">Barb Stevens digital scorecard</caption><thead><tr><th colSpan={2} scope="colgroup">Game</th><th colSpan={2} scope="colgroup">Spread Points</th><th scope="col">Opponent</th><th scope="col">Verification</th></tr><tr><th scope="col">#</th><th scope="col">Points</th><th scope="col">+</th><th scope="col">−</th><th scope="col">Name</th><th scope="col">ID Number</th></tr></thead><tbody>{Array.from({ length: eventGames }, (_, index) => { const n = index + 1; const saved = n === 1 ? [2, 10, "—", "Steve Hall", "A-8"] : n === 2 ? [2, 11, "—", "Robin Lee", "B-3"] : null; const current = n === 3; return <tr key={n} className={current ? "current" : undefined}><th scope="row">{n}</th><td>{current && score ? score.playerGamePoints : saved?.[0] ?? "—"}</td><td>{current && score ? score.playerPlus || "—" : saved?.[1] ?? "—"}</td><td>{current && score ? score.playerMinus || "—" : saved?.[2] ?? "—"}</td><td>{current ? "Steve Hall" : saved?.[3] ?? "—"}</td><td>{current ? "A-8" : saved?.[4] ?? "—"}</td></tr>; })}</tbody><tfoot><tr><th>Total</th><td>4</td><td>21</td><td>—</td><td colSpan={2}></td></tr></tfoot></table></div><div className="totals"><div><span>Net Points</span><strong>{formatSignedNet(21)}</strong></div><div><span>Games Won</span><strong>2</strong></div><div><span>Verification</span><strong className="pending">Pending Entry</strong></div></div></section>}
      {screen === "operations" && <section className="panel operations"><Heading label="TOURNAMENT OPERATIONS" title="Grass Roots"><Context /></Heading><div className="option-grid"><button type="button" onClick={() => setScreen("seating")}><b>⌘</b><strong>Seating & Paper Cards</strong><span>Publish Table/Seat assignments</span></button><button type="button" onClick={() => setScreen("corrections")}><b>♢</b><strong>Cross Check</strong><span>Review scorecards and corrections</span></button><button type="button" onClick={() => setScreen("flyer")}><b>✦</b><strong>Flyer & Events</strong><span>Main, Consy, and satellites</span></button><button type="button" onClick={() => setScreen("finance")}><b>$</b><strong>Financials</strong><span>Fees, pools, expenses, and results</span></button></div></section>}
      {screen === "seating" && <Feature label="OPERATIONS" title="Seating & Paper Cards" back={() => setScreen("operations")} action="Print Paper Seating List"><List rows={[["Barb Stevens", "Digital scorecard", "A-7"], ["Steve Hall", "Digital scorecard", "A-8"], ["Robin Lee", "Paper scorecard", "B-3"], ["Alex Morgan", "Paper scorecard", "B-4"]]} /></Feature>}
      {screen === "corrections" && <Feature label="CROSS CHECK" title="Scorecard Review" back={() => setScreen("operations")} action="Open Selected Card"><List rows={[["Table A · Game 3", "Barb Stevens / Steve Hall", "Waiting for entry"], ["Table C · Game 2", "Jordan Patel / Casey Kim", "Correction ready"]]} /></Feature>}
      {screen === "flyer" && <Feature label="FLYER & EVENTS" title="Tournament Events" back={() => setScreen("operations")} action="Add Satellite Event"><List rows={[["Main", "12 games · April 25", "ACC Sanctioning Fee"], ["Consy", "9 games · April 25", "Ready to publish"], ["Canadian Doubles", "Satellite · April 26", "Ready to publish"]]} /></Feature>}
      {screen === "finance" && <Feature label="FINANCIALS" title="Tournament Financials" back={() => setScreen("operations")} action="Add Expense"><div className="money"><div><span>Registration received</span><b>$1,200.00</b></div><div><span>ACC Sanctioning Fee</span><b>$120.00</b></div><div><span>Prize pool</span><b>$960.00</b></div><div><span>Unreconciled</span><b>$0.00</b></div></div></Feature>}
      {screen === "results" && <section className="panel results"><Heading label="RESULTS" title="Grass Roots Results" /><div className="results-head"><div><span>Main</span><strong>Results not published</strong></div><button type="button" className="secondary">View Qualifiers</button></div><List rows={[["Winner", "—", "—"], ["Runner-up", "—", "—"], ["High Non-Qualifier", "—", "—"]]} /></section>}
    </div><footer><span>ACC Tournament Desk</span><span>Grass Roots · Honolulu, HI · April 25, 2025</span></footer>
  </main>;
}

function Feature({ label, title, action, back, children }: { label: string; title: string; action: string; back: () => void; children: React.ReactNode }) { return <section className="panel feature"><Heading label={label} title={title} /><div className="actions"><button type="button" className="secondary" onClick={back}>Back to Operations</button><button type="button" className="primary">{action}</button></div>{children}</section>; }
function List({ rows }: { rows: string[][] }) { return <div className="list">{rows.map((row) => <div key={row.join("|")}><strong>{row[0]}</strong><span>{row[1]}</span><b>{row[2]}</b></div>)}</div>; }
