"use client";
import { useEffect,useMemo,useState } from "react";
import { isSeatingDirectory,type SeatingDirectory } from "../../../../lib/api/team-operations";
export default function SeatingDirectoryClient({tournamentId}:{tournamentId:string}){
 const[data,setData]=useState<SeatingDirectory|null>(null),[eventId]=useState(()=>new URLSearchParams(window.location.search).get("event")??""),[query,setQuery]=useState(""),[card,setCard]=useState("all"),[entryKind,setEntryKind]=useState("all"),[table,setTable]=useState("all"),[message,setMessage]=useState(eventId?"Loading published seating…":"Choose a specific event to open its published seating directory.");
 useEffect(()=>{if(!eventId)return;const controller=new AbortController(),timer=window.setTimeout(()=>{const params=new URLSearchParams({event:eventId});if(query.trim())params.set("q",query.trim());void fetch(`/api/v1/tournaments/${tournamentId}/seating-directory?${params}`,{cache:"no-store",signal:controller.signal}).then(async r=>({ok:r.ok,value:await r.json()})).then(({ok,value}:{ok:boolean;value:unknown})=>{if(ok&&isSeatingDirectory(value)){setData(value);setMessage("");}else{setData(null);setMessage("Published seating is not available for this event yet.");}}).catch(()=>{if(!controller.signal.aborted)setMessage("Seating lookup is temporarily unavailable.");});},250);return()=>{controller.abort();window.clearTimeout(timer);};},[eventId,query,tournamentId]);
 const tables=useMemo(()=>[...new Set((data?.entries??[]).map(r=>r.assignedTableSeat.split("-")[0]))].sort(),[data]);
 const rows=useMemo(()=>(data?.entries??[]).filter(r=>(card==="all"||r.scorecardType===card)&&(entryKind==="all"||r.entryKind===entryKind)&&(table==="all"||r.assignedTableSeat.startsWith(`${table}-`))),[data,card,entryKind,table]);
 return <section className="seating-directory"><div className="setup-grid"><label>Search player, team, or exact ACC #<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or ACC number"/></label><label>Scorecard<select value={card} onChange={e=>setCard(e.target.value)}><option value="all">All</option><option value="digital">Digital</option><option value="paper">Paper</option></select></label><label>Entry type<select value={entryKind} onChange={e=>setEntryKind(e.target.value)}><option value="all">Singles and Teams</option><option value="player">Singles</option><option value="team_member">Teams</option></select></label><label>Table<select value={table} onChange={e=>setTable(e.target.value)}><option value="all">All Tables</option>{tables.map(t=><option key={t}>{t}</option>)}</select></label></div><button className="secondary no-print" type="button" onClick={()=>window.print()} disabled={!data}>Print Current List</button>{data?<><p className="card-context print-title">Seating Assignments · {data.tournamentName}</p><div className="table-wrap"><table><thead><tr><th>Event</th><th>Player</th><th>Team</th><th>Scorecard</th><th>Assigned Table/Seat</th><th>Verification ID</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.eventId}-${r.displayName}-${i}`} className={r.isSelf?"current-row":undefined}><td>{r.eventName}</td><td>{r.displayName}{r.isSelf?" (You)":""}</td><td>{r.teamName??"—"}</td><td>{r.scorecardType}</td><td>{r.assignedTableSeat}</td><td><strong>{r.verificationId}</strong></td></tr>)}</tbody></table></div><p className="auth-note no-print">{rows.length} published assignment{rows.length===1?"":"s"} shown.</p></>:<p className="auth-note" role="status">{message}</p>}</section>}
