import { NextRequest } from "next/server";
import { apiJson,readSmallJson,requireVerifiedIdentity,withApiFailureBoundary } from "../../../../lib/api/route-boundary";
import { isSameOriginRequest } from "../../../../lib/api/same-origin";
import { canonicalOfflineSubmissionPayload,isOfflineQueueIntent,type OfflineReplayReceipt,type OfflineSubmissionIntent,type UnsignedOfflineSubmission } from "../../../../lib/offline-score-queue-contract";
import { createServerOnlyAdminClient } from "../../../../lib/supabase/private-admin";
import { createClient } from "../../../../lib/supabase/server";

function base64UrlBytes(value:string){if(!/^[A-Za-z0-9_-]{1,256}$/.test(value))throw new Error("invalid_signature");const padded=value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"=");return Uint8Array.from(Buffer.from(padded,"base64"));}
function unsigned(intent:OfflineSubmissionIntent):UnsignedOfflineSubmission{return{version:intent.version,queueId:intent.queueId,createdAtMs:intent.createdAtMs,clientOperationId:intent.clientOperationId,verifiedActorId:intent.verifiedActorId,sessionBindingId:intent.sessionBindingId,deviceKeyId:intent.deviceKeyId,tournamentId:intent.tournamentId,eventId:intent.eventId,gameId:intent.gameId,assignedSide:intent.assignedSide,expectedGameVersion:intent.expectedGameVersion,capabilityId:intent.capabilityId,capabilityExpiresAtMs:intent.capabilityExpiresAtMs,kind:"submission",submissionId:intent.submissionId,submissionSlot:intent.submissionSlot,winnerSide:intent.winnerSide,margin:intent.margin};}
function hex(bytes:Uint8Array){return[...bytes].map((value)=>value.toString(16).padStart(2,"0")).join("");}
async function verifyIntent(intent:OfflineSubmissionIntent,publicJwk:JsonWebKey){const bytes=new TextEncoder().encode(canonicalOfflineSubmissionPayload(unsigned(intent))),digest=hex(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes)));if(digest!==intent.payloadDigest)return false;const key=await crypto.subtle.importKey("jwk",publicJwk,{name:"ECDSA",namedCurve:"P-256"},false,["verify"]);return crypto.subtle.verify({name:"ECDSA",hash:"SHA-256"},key,base64UrlBytes(intent.signature),bytes);}

export async function POST(request:NextRequest){return withApiFailureBoundary(async()=>{
  if(!isSameOriginRequest(request))return apiJson({error:"invalid_origin"},{status:403});const raw=await readSmallJson(request);if(!isOfflineQueueIntent(raw)||raw.kind!=="submission")return apiJson({error:"invalid_offline_submission"},{status:400});
  const identity=await requireVerifiedIdentity(await createClient());if(!identity||raw.verifiedActorId!==identity.subject)return apiJson({error:"unauthorized"},{status:401});const admin=createServerOnlyAdminClient();
  const capabilityRead=await admin.rpc("get_event_team_offline_capability_v2",{p_actor_id:identity.subject,p_session_binding_id:raw.sessionBindingId,p_capability_id:raw.capabilityId,p_queue_id:raw.queueId});
  if(capabilityRead.error||!capabilityRead.data||typeof capabilityRead.data!=="object")return apiJson({error:"capability_unavailable"},{status:409});const capability=capabilityRead.data as Record<string,unknown>;
  const matches=capability.capabilityId===raw.capabilityId&&capability.deviceKeyId===raw.deviceKeyId&&capability.verifiedActorId===raw.verifiedActorId&&capability.sessionBindingId===raw.sessionBindingId&&capability.tournamentId===raw.tournamentId&&capability.eventId===raw.eventId&&capability.gameId===raw.gameId&&capability.assignedSide===raw.assignedSide&&capability.submissionSlot===raw.submissionSlot&&capability.expectedGameVersion===raw.expectedGameVersion&&capability.capabilityExpiresAtMs===raw.capabilityExpiresAtMs;
  if(!matches||!capability.publicJwk||typeof capability.publicJwk!=="object"||!await verifyIntent(raw,capability.publicJwk as JsonWebKey))return apiJson({error:"invalid_offline_evidence"},{status:409});
  if(capability.priorReceipt&&typeof capability.priorReceipt==="object")return apiJson(capability.priorReceipt);
  const{data,error}=await admin.rpc("replay_event_team_offline_score_v2",{p_actor_id:identity.subject,p_session_binding_id:raw.sessionBindingId,p_queue_id:raw.queueId,p_client_operation_id:raw.clientOperationId,p_capability_id:raw.capabilityId,p_device_key_id:raw.deviceKeyId,p_tournament_id:raw.tournamentId,p_event_id:raw.eventId,p_game_id:raw.gameId,p_assigned_side:raw.assignedSide,p_expected_game_version:raw.expectedGameVersion,p_submission_id:raw.submissionId,p_submission_slot:raw.submissionSlot,p_winner_side:raw.winnerSide,p_margin:raw.margin,p_payload_digest:raw.payloadDigest,p_signature:raw.signature});
  if(error||!data||typeof data!=="object")return apiJson({error:"operation_unavailable"},{status:503});const result=data as Record<string,unknown>;if(!["accepted","rejected","quarantined","conflict"].includes(String(result.disposition)))return apiJson({error:"operation_unavailable"},{status:503});const receipt:OfflineReplayReceipt={version:1,queueId:raw.queueId,clientOperationId:raw.clientOperationId,kind:"submission",gameId:raw.gameId,submissionId:raw.submissionId,payloadDigest:raw.payloadDigest,disposition:result.disposition as OfflineReplayReceipt["disposition"]};return apiJson(receipt,{status:receipt.disposition==="accepted"?200:409});
});}
