"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import type { PromotionCandidate, RosterEntry } from "../../../../lib/roster/workspace";
import { isAcceptedManualRosterEntry, isAcceptedRosterPromotion, isRejectedManualRosterEntry, isRejectedRosterPromotion, isUuid, type ManualRosterEntryRequest } from "../../../../lib/api/roster";

type Envelope = { kind: "roster-promotion"; approvalDecisionId: string; idempotencyKey: string };
type ManualRecovery = { kind: "manual-roster"; idempotencyKey: string };
type ManualPending = ManualRosterEntryRequest & { kind: "manual-roster" };
const valid = (value: unknown): value is Envelope => !!value && typeof value === "object" && (value as Envelope).kind === "roster-promotion" && isUuid((value as Envelope).approvalDecisionId) && isUuid((value as Envelope).idempotencyKey);
const validManualRecovery = (value: unknown): value is ManualRecovery => !!value && typeof value === "object" && (value as ManualRecovery).kind === "manual-roster" && isUuid((value as ManualRecovery).idempotencyKey);
function read(key: string) { try { const raw = window.sessionStorage.getItem(key); const parsed: unknown = raw ? JSON.parse(raw) : null; return valid(parsed) ? parsed : null; } catch { return null; } }
function readManual(key: string) { try { const raw = window.sessionStorage.getItem(key); const parsed: unknown = raw ? JSON.parse(raw) : null; return validManualRecovery(parsed) ? parsed : null; } catch { return null; } }
function write(key: string, value: Envelope | ManualRecovery) { try { window.sessionStorage.setItem(key, JSON.stringify(value)); return true; } catch { return false; } }
function clear(key: string) { try { window.sessionStorage.removeItem(key); } catch { /* Server receipt remains authoritative. */ } }

export default function RosterClient({ actorId, tournamentId, rosterEntries, promotionCandidates }: { actorId: string; tournamentId: string; rosterEntries: RosterEntry[]; promotionCandidates: PromotionCandidate[] }) {
  const router = useRouter(), key = `registration-operation:roster:${actorId}:${tournamentId}`, manualKey = `manual-roster-operation:${actorId}:${tournamentId}`;
  const [locked, setLocked] = useState<Envelope | null>(null), [manualPending, setManualPending] = useState<ManualPending | null>(null);
  const [displayName, setDisplayName] = useState(""), [email, setEmail] = useState(""), [accNumber, setAccNumber] = useState("");
  const [ready, setReady] = useState(false), [busy, setBusy] = useState(false), [message, setMessage] = useState<string | null>(null);
  const reconcile = useCallback(async (envelope: Envelope) => {
    try { const response = await fetch(`/api/v1/tournaments/${tournamentId}/roster-promotions/reconciliation`, { method: "POST", headers: { "content-type": "application/json" }, credentials: "same-origin", body: JSON.stringify(envelope) }); const payload: unknown = response.ok ? await response.json().catch(() => null) : null; const result = payload && typeof payload === "object" ? (payload as Record<string, unknown>).result : null; return response.ok && isAcceptedRosterPromotion(result, envelope.approvalDecisionId) ? "accepted" : response.ok && isRejectedRosterPromotion(result, envelope.approvalDecisionId) ? "rejected" : "unresolved"; } catch { return "unresolved"; }
  }, [tournamentId]);
  const reconcileManual = useCallback(async (envelope: ManualRecovery) => {
    try { const response = await fetch(`/api/v1/tournaments/${tournamentId}/roster-manual/reconciliation`, { method: "POST", headers: { "content-type": "application/json" }, credentials: "same-origin", body: JSON.stringify({ idempotencyKey: envelope.idempotencyKey }) }); const payload: unknown = response.ok ? await response.json().catch(() => null) : null; const result = payload && typeof payload === "object" ? (payload as Record<string, unknown>).result : null; return response.ok && isAcceptedManualRosterEntry(result) ? "accepted" : response.ok && isRejectedManualRosterEntry(result) ? "rejected" : "unresolved"; } catch { return "unresolved"; }
  }, [tournamentId]);
  useEffect(() => { void (async () => {
    const saved = read(key);
    if (saved) { const state = await reconcile(saved); if (state === "accepted") { clear(key); setReady(true); router.refresh(); return; } if (state === "rejected") { clear(key); setMessage("The server did not create that roster entry. The current list is shown."); } else { setLocked(saved); setMessage("A prior roster request needs a safe retry. Its target is locked until resolved."); } }
    const savedManual = readManual(manualKey);
    if (savedManual) { const state = await reconcileManual(savedManual); clear(manualKey); if (state === "accepted") { setReady(true); router.refresh(); return; } if (state === "unresolved") setMessage("A previous manual entry has no server receipt. Check the roster before entering that player again."); }
    setReady(true);
  })(); }, [key, manualKey, router, reconcile, reconcileManual]);
  async function promote(envelope: Envelope) {
    if (busy) return; setBusy(true); setLocked(envelope); setMessage(null);
    try { const response = await fetch(`/api/v1/tournaments/${tournamentId}/roster-promotions`, { method: "POST", headers: { "content-type": "application/json" }, credentials: "same-origin", body: JSON.stringify(envelope) }); const payload: unknown = await response.json().catch(() => null); if (response.ok && isAcceptedRosterPromotion(payload, envelope.approvalDecisionId)) { clear(key); setLocked(null); router.refresh(); return; } if (response.status === 409 && isRejectedRosterPromotion(payload, envelope.approvalDecisionId)) { clear(key); setLocked(null); setMessage("The tournament server did not accept that roster action."); return; } setMessage("The roster request is unresolved. Retry uses the same protected request."); } catch { setMessage("The roster request is unresolved. Retry uses the same protected request."); } finally { setBusy(false); }
  }
  async function createManual(request: ManualPending) {
    if (busy) return; setBusy(true); setManualPending(request); setMessage(null);
    try { const { kind: _kind, ...body } = request; void _kind; const response = await fetch(`/api/v1/tournaments/${tournamentId}/roster-manual`, { method: "POST", headers: { "content-type": "application/json" }, credentials: "same-origin", body: JSON.stringify(body) }); const payload: unknown = await response.json().catch(() => null);
      if (response.ok && isAcceptedManualRosterEntry(payload)) { clear(manualKey); setManualPending(null); setDisplayName(""); setEmail(""); setAccNumber(""); setMessage("Player added to the roster."); router.refresh(); return; }
      if (response.status === 409 && isRejectedManualRosterEntry(payload)) { clear(manualKey); setManualPending(null); const code = (payload as { code: string }).code; setMessage(code === "duplicate_roster_entry" ? "That player is already on this tournament roster." : code === "initial_seating_already_published" ? "The roster is locked because initial seating has already been published." : "The tournament server did not accept that manual roster entry."); return; }
      setMessage("The manual entry is unresolved. Retry uses the same protected request.");
    } catch { setMessage("The manual entry is unresolved. Retry uses the same protected request."); } finally { setBusy(false); }
  }
  function start(decisionId: string) { if (!ready || locked || busy) return; const envelope = { kind: "roster-promotion" as const, approvalDecisionId: decisionId, idempotencyKey: crypto.randomUUID() }; if (!write(key, envelope)) { setMessage("This browser cannot safely retain a roster request for recovery. Enable session storage before continuing."); return; } setLocked(envelope); void promote(envelope); }
  function submitManual(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!ready || locked || busy || manualPending || !displayName.trim()) return; const request: ManualPending = { kind: "manual-roster", displayName: displayName.trim(), email: email.trim(), accNumber: accNumber.trim(), idempotencyKey: crypto.randomUUID() }; if (!write(manualKey, { kind: request.kind, idempotencyKey: request.idempotencyKey })) { setMessage("This browser cannot safely retain a roster request for recovery. Enable session storage before continuing."); return; } void createManual(request); }
  return <section className="policy-settings">
    <section className="manual-roster-panel" aria-labelledby="manual-roster-title"><h2 id="manual-roster-title">Add Player Manually</h2><p>Use this fallback for a phone, paper list, or spreadsheet entry. Email and ACC number are optional. Payment, check-in, scorecard type, and seating are recorded separately.</p><form className="manual-roster-form" onSubmit={submitManual}><label>Player name<input required maxLength={160} autoComplete="name" value={displayName} onChange={(event) => setDisplayName(event.target.value)} /></label><label>Email (optional)<input maxLength={320} inputMode="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>ACC # (optional)<input maxLength={64} autoCapitalize="characters" value={accNumber} onChange={(event) => setAccNumber(event.target.value)} /></label><button className="primary" type="submit" disabled={!ready || !!locked || busy || !!manualPending || !displayName.trim()}>Add Player</button></form>{manualPending ? <button className="primary" type="button" disabled={busy} onClick={() => void createManual(manualPending)}>Retry manual entry</button> : null}</section>
    <h2>Approved registration candidates</h2><p>Payment preference is unverified and is not payment. Promoting a candidate creates only a private roster identity snapshot.</p>{promotionCandidates.length ? <ul>{promotionCandidates.map((candidate) => <li key={candidate.approvalDecisionId}><strong>{candidate.displayName}</strong> · {candidate.email}{candidate.accNumber ? ` · ${candidate.accNumber}` : ""} · planned {candidate.intendedPaymentMethod}<button className="primary" type="button" disabled={!ready || !!locked || busy} onClick={() => start(candidate.approvalDecisionId)}>{locked?.approvalDecisionId === candidate.approvalDecisionId ? "Retry roster entry" : "Create roster identity"}</button></li>)}</ul> : <p>No reviewed registrations are waiting for roster creation.</p>}
    <h2>Roster identities</h2>{rosterEntries.length ? <ul>{rosterEntries.map((entry) => <li key={entry.rosterEntryId}><strong>{entry.displayName}</strong>{entry.email ? ` · ${entry.email}` : ""}{entry.accNumber ? ` · ${entry.accNumber}` : ""} <span className="status-pill">{entry.source === "director_manual" ? "Manual" : "Registration"}</span></li>)}</ul> : <p>No roster identities have been created.</p>}{locked && <button className="primary" type="button" disabled={busy} onClick={() => void promote(locked)}>Retry roster request</button>}{message && <p className="error-text" role="status">{message}</p>}
  </section>;
}
