import{NextRequest}from"next/server";
import{isPublicRegistrationOptions}from"../../../../../lib/api/public-registration-options";
import{publicRegistrationEnabled}from"../../../../../lib/api/public-registration-v2";
import{apiJson,readSmallJson,withApiFailureBoundary}from"../../../../../lib/api/route-boundary";
import{isSameOriginRequest}from"../../../../../lib/api/same-origin";
import{digestRegistrationLinkCredential,parseRegistrationLinkCredential}from"../../../../../lib/registration-link-token";
import{createServerOnlyAdminClient}from"../../../../../lib/supabase/private-admin";
function bytea(value:Uint8Array){return`\\x${Buffer.from(value).toString("hex")}`;}function material(value:unknown):{salt:string}|null{return!!value&&typeof value==="object"&&Object.keys(value).length===3&&typeof(value as Record<string,unknown>).salt==="string"?{salt:(value as Record<string,unknown>).salt as string}:null;}
export async function POST(request:NextRequest){return withApiFailureBoundary(async()=>{if(!publicRegistrationEnabled())return apiJson({error:"not_found"},{status:404});if(!isSameOriginRequest(request))return apiJson({error:"invalid_origin"},{status:403});const body=await readSmallJson(request);if(!body||typeof body!=="object"||Object.keys(body).length!==1||typeof(body as Record<string,unknown>).credential!=="string")return apiJson({error:"unavailable"},{status:404});const credential=parseRegistrationLinkCredential((body as{credential:string}).credential);if(!credential)return apiJson({error:"unavailable"},{status:404});const admin=createServerOnlyAdminClient();const redemption=await admin.rpc("get_registration_link_redemption_material_v2",{p_link_id:credential.linkId});const current=material(redemption.data);const salt=current?Buffer.from(current.salt,"base64"):null;if(redemption.error||!salt||salt.byteLength!==32)return apiJson({error:"unavailable"},{status:404});const digest=digestRegistrationLinkCredential(salt,credential.canonicalToken);const{data,error}=await admin.rpc("get_public_registration_payment_options_v1",{p_link_id:credential.linkId,p_digest:bytea(digest)});if(error||!isPublicRegistrationOptions(data))return apiJson({error:"unavailable"},{status:404});return apiJson(data);});}
