"use client";

import { useEffect, useRef, useState } from "react";

declare global { interface Window { __accRegistrationCredential?: string } }
const payment = ["cash", "check", "other", "unspecified"] as const;

export default function RegistrationForm() {
  const [canRegister, setCanRegister] = useState(false); const [message, setMessage] = useState("Checking registration link…");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [acc, setAcc] = useState(""); const [method, setMethod] = useState<typeof payment[number]>("unspecified");
  const credentialRef = useRef<string | null>(null); const requestRef = useRef<AbortController | null>(null); const mountedRef = useRef(false);
  function dropCredential() { credentialRef.current = null; delete window.__accRegistrationCredential; setCanRegister(false); }
  useEffect(() => { mountedRef.current = true; const timer = window.setTimeout(() => { const value = window.__accRegistrationCredential; delete window.__accRegistrationCredential; if (!value) { setMessage("This registration link is unavailable."); return; } credentialRef.current = value; setCanRegister(true); setMessage(""); }, 0); const onPageHide = () => { requestRef.current?.abort(); requestRef.current = null; dropCredential(); }; window.addEventListener("pagehide", onPageHide); return () => { mountedRef.current = false; window.clearTimeout(timer); window.removeEventListener("pagehide", onPageHide); requestRef.current?.abort(); requestRef.current = null; credentialRef.current = null; delete window.__accRegistrationCredential; }; }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); const currentCredential = credentialRef.current; if (!currentCredential || requestRef.current) return; setMessage("Submitting registration…"); const controller = new AbortController(); requestRef.current = controller; try { const response = await fetch("/api/v1/registration/claims", { method: "POST", credentials: "same-origin", cache: "no-store", signal: controller.signal, headers: { "content-type": "application/json" }, body: JSON.stringify({ credential: currentCredential, displayName: name, email, accNumber: acc, intendedPaymentMethod: method, operationId: crypto.randomUUID() }) }); const result: unknown = await response.json().catch(() => null); dropCredential(); if (response.ok && !!result && typeof result === "object" && (result as Record<string, unknown>).status === "received") { setMessage("Your registration was received for review."); return; } setMessage("This registration link is unavailable. Please contact the tournament director."); } catch { dropCredential(); if (mountedRef.current) setMessage("This registration link is unavailable. Please contact the tournament director."); } finally { if (requestRef.current === controller) requestRef.current = null; } }
  return <section className="auth-card" aria-labelledby="registration-title"><p className="eyebrow">TOURNAMENT REGISTRATION</p><h1 id="registration-title">Register for Tournament</h1>{canRegister ? <form onSubmit={submit}><label>Name<input required value={name} maxLength={160} onChange={e => setName(e.target.value)} /></label><label>Email<input required type="email" value={email} maxLength={320} onChange={e => setEmail(e.target.value)} /></label><label>ACC Number (if known)<input value={acc} maxLength={64} onChange={e => setAcc(e.target.value)} /></label><label>Planned payment<select value={method} onChange={e => setMethod(e.target.value as typeof method)}>{payment.map(value => <option key={value} value={value}>{value}</option>)}</select></label><button className="primary" type="submit">Submit Registration</button></form> : null}<p className="auth-note" role="status">{message}</p></section>;
}
