"use client";

import { useEffect, useRef, useState } from "react";
import { isPublicRegistrationOptions, type TournamentRegistrationContact } from "../../lib/api/public-registration-options";

declare global { interface Window { __accRegistrationCredential?: string } }
type PaymentMethod = "cash" | "check";

export default function RegistrationForm() {
  const [canRegister, setCanRegister] = useState(false); const [message, setMessage] = useState("Checking registration link…");
  const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [email, setEmail] = useState(""); const [acc, setAcc] = useState(""); const [method, setMethod] = useState<PaymentMethod>("cash");
  const [acceptedMethods, setAcceptedMethods] = useState<readonly PaymentMethod[]>([]); const [tournamentName, setTournamentName] = useState(""); const [tournamentContact, setTournamentContact] = useState<TournamentRegistrationContact | null>(null);
  const [scorecardType, setScorecardType] = useState<"digital" | "paper">("digital");
  const credentialRef = useRef<string | null>(null); const requestRef = useRef<AbortController | null>(null); const mountedRef = useRef(false);
  function dropCredential() { credentialRef.current = null; delete window.__accRegistrationCredential; setCanRegister(false); }
  useEffect(() => { mountedRef.current = true; const timer = window.setTimeout(async () => { const value = window.__accRegistrationCredential; delete window.__accRegistrationCredential; if (!value) { setMessage("This registration link is unavailable."); return; } try { const response = await fetch("/api/v1/registration/options", { method: "POST", credentials: "same-origin", cache: "no-store", headers: { "content-type": "application/json" }, body: JSON.stringify({ credential: value }) }); const options: unknown = await response.json().catch(() => null); if (!response.ok || !isPublicRegistrationOptions(options)) { setMessage("This registration link is unavailable."); return; } credentialRef.current = value; setAcceptedMethods(options.acceptedMethods); setMethod(options.acceptedMethods[0]); setTournamentName(options.tournamentName); setTournamentContact(options.tournamentContact); setCanRegister(true); setMessage(""); } catch { setMessage("This registration link is unavailable."); } }, 0); const onPageHide = () => { requestRef.current?.abort(); requestRef.current = null; dropCredential(); }; window.addEventListener("pagehide", onPageHide); return () => { mountedRef.current = false; window.clearTimeout(timer); window.removeEventListener("pagehide", onPageHide); requestRef.current?.abort(); requestRef.current = null; credentialRef.current = null; delete window.__accRegistrationCredential; }; }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); const currentCredential = credentialRef.current; if (!currentCredential || requestRef.current) return; const welcomeName = `${firstName.trim()} ${lastName.trim()}`; const welcomeAcc = acc.trim() ? ` (${acc.trim()})` : ""; setMessage("Submitting registration…"); const controller = new AbortController(); requestRef.current = controller; try { const response = await fetch("/api/v1/registration/claims", { method: "POST", credentials: "same-origin", cache: "no-store", signal: controller.signal, headers: { "content-type": "application/json" }, body: JSON.stringify({ credential: currentCredential, firstName, lastName, email, accNumber: acc, intendedPaymentMethod: method, scorecardType, operationId: crypto.randomUUID() }) }); const result: unknown = await response.json().catch(() => null); dropCredential(); if (response.ok && !!result && typeof result === "object" && (result as Record<string, unknown>).status === "received") { setMessage(`Thank you and welcome ${welcomeName}${welcomeAcc}! Your registration was received for review.`); return; } setMessage("This registration link is unavailable. Please contact the tournament director."); } catch { dropCredential(); if (mountedRef.current) setMessage("This registration link is unavailable. Please contact the tournament director."); } finally { if (requestRef.current === controller) requestRef.current = null; } }
  return <section className="auth-card" aria-labelledby="registration-title"><p className="eyebrow">TOURNAMENT REGISTRATION</p><h1 id="registration-title">Register for Tournament</h1>{tournamentName ? <p className="auth-note">{tournamentName}</p> : null}{tournamentContact ? <address className="auth-note tournament-contact"><strong>Tournament contact</strong><br /><strong>Tournament Director: {tournamentContact.directorName}</strong><br />Phone: <a href={`tel:${tournamentContact.phone}`}>{tournamentContact.phone}</a><br /><a href={`mailto:${tournamentContact.email}`}>{tournamentContact.email}</a>{tournamentContact.mailingAddress ? <><br /><span>{tournamentContact.mailingAddress}</span></> : null}</address> : null}{canRegister ? <form onSubmit={submit}><label>First name<input required value={firstName} maxLength={80} autoComplete="given-name" onChange={e => setFirstName(e.target.value)} /></label><label>Last name<input required value={lastName} maxLength={80} autoComplete="family-name" onChange={e => setLastName(e.target.value)} /></label><label>Email<input required type="email" value={email} maxLength={320} autoComplete="email" onChange={e => setEmail(e.target.value)} /></label><label>ACC Number (if known)<input value={acc} maxLength={64} onChange={e => setAcc(e.target.value)} /></label><label>Scorecard Type<select value={scorecardType} onChange={e => setScorecardType(e.target.value as "digital" | "paper")}><option value="digital">Digital</option><option value="paper">Paper</option></select></label><label>How will you pay?<select value={method} onChange={e => setMethod(e.target.value as typeof method)}>{acceptedMethods.map(value => <option key={value} value={value}>{value === "cash" ? "Cash" : "Check"}</option>)}</select></label><p className="auth-note">Your selection tells the tournament director how you plan to pay. It does not mark the payment received.</p><button className="primary" type="submit">Submit Registration</button></form> : null}<p className="auth-note" role="status">{message}</p></section>;
}
